// [English, हिन्दी, ગુજરાતી]: navigation, shared labels, dialogs, interview questions
export const APP = [
  ['121–180 AD', 'ईस्वी 121–180', 'ઈ.સ. 121–180'],
  ['A colleague, about them', 'कोई सहकर्मी, उनके बारे में', 'કોઈ સહકર્મી, તેમના વિશે'],
  ['A friend, about them', 'कोई दोस्त, उनके बारे में', 'કોઈ મિત્ર, તેમના વિશે'],
  ['Access code', 'एक्सेस कोड', 'એક્સેસ કોડ'],
  ['Actions', 'काम', 'ક્રિયાઓ'],
  ['Back to top', 'ऊपर जाएँ', 'ઉપર જાઓ'],
  ['Beliefs', 'मान्यताएँ', 'માન્યતાઓ'],
  ['Beliefs and values', 'मान्यताएँ और मूल्य', 'માન્યતાઓ અને મૂલ્યો'],
  ['Born 1971', 'जन्म 1971', 'જન્મ 1971'],
  ['Business', 'व्यापार', 'વ્યાપાર'],
  ['CHRONUS home', 'CHRONUS होम', 'CHRONUS હોમ'],
  ['CHRONUS says “I don’t know” when it has nothing to go on. So does this address.', 'जब CHRONUS के पास कुछ नहीं होता, तो वह कहता है “मुझे नहीं पता।” यह पता भी यही कह रहा है।', 'જ્યારે CHRONUS પાસે કંઈ ન હોય, ત્યારે તે કહે છે “મને ખબર નથી.” આ સરનામું પણ એ જ કહે છે.'],
  ['Chart', 'चार्ट', 'ચાર્ટ'],
  ['Chat', 'चैट', 'ચેટ'],
  ['Checking…', 'जाँच हो रही है…', 'તપાસ થઈ રહી છે…'],
  ['Close', 'बंद करें', 'બંધ કરો'],
  ['Close a dialog', 'डायलॉग बंद करें', 'ડાયલોગ બંધ કરો'],
  ['Close search', 'खोज बंद करें', 'શોધ બંધ કરો'],
  ['Colleague', 'सहकर्मी', 'સહકર્મી'],
  ['Core memories', 'मुख्य यादें', 'મુખ્ય યાદો'],
  ['Dark', 'डार्क', 'ડાર્ક'],
  ['Each person sees only the models they created.', 'हर व्यक्ति सिर्फ़ अपने बनाए मॉडल देखता है।', 'દરેક વ્યક્તિ ફક્ત પોતે બનાવેલા મોડેલ જુએ છે.'],
  ['Enter the access code', 'एक्सेस कोड डालें', 'એક્સેસ કોડ દાખલ કરો'],
  ['Explore', 'देखें', 'જુઓ'],
  ['Family', 'परिवार', 'પરિવાર'],
  ['Family, about them', 'परिवार, उनके बारे में', 'પરિવાર, તેમના વિશે'],
  ['Features', 'सुविधाएँ', 'સુવિધાઓ'],
  ['Friend', 'दोस्त', 'મિત્ર'],
  ['Go home', 'होम पर जाएँ', 'હોમ પર જાઓ'],
  ['How an answer is made', 'जवाब कैसे बनता है', 'જવાબ કેવી રીતે બને છે'],
  ['How it works', 'यह कैसे काम करता है', 'તે કેવી રીતે કામ કરે છે'],
  ['How preserving works', 'सहेजना कैसे काम करता है', 'સાચવવું કેવી રીતે કામ કરે છે'],
  ['Insights', 'इनसाइट्स', 'ઇનસાઇટ્સ'],
  ['Jump', 'जाएँ', 'જાઓ'],
  ['Jump to the chat box (on a chat page)', 'चैट बॉक्स पर जाएँ (चैट पेज पर)', 'ચેટ બૉક્સ પર જાઓ (ચેટ પેજ પર)'],
  ['Keyboard', 'कीबोर्ड', 'કીબોર્ડ'],
  ['Language', 'भाषा', 'ભાષા'],
  ['Language: {name}', 'भाषा: {name}', 'ભાષા: {name}'],
  ['Light', 'लाइट', 'લાઇટ'],
  ['Literature', 'साहित्य', 'સાહિત્ય'],
  ['Loading…', 'लोड हो रहा है…', 'લોડ થઈ રહ્યું છે…'],
  ['Main', 'मुख्य', 'મુખ્ય'],
  ['Memories', 'यादें', 'યાદો'],
  ['Memory field', 'यादों का मैदान', 'યાદોનું ક્ષેત્ર'],
  ['Menu', 'मेनू', 'મેનુ'],
  ['Myself', 'मैं ख़ुद', 'હું પોતે'],
  ['Name', 'नाम', 'નામ'],
  ['Nothing matches “{q}”.', '“{q}” से कुछ नहीं मिला।', '“{q}” સાથે કંઈ મળ્યું નહીં.'],
  ['Nothing yet.', 'अभी कुछ नहीं।', 'હજી કંઈ નથી.'],
  ['On the home page', 'होम पेज पर', 'હોમ પેજ પર'],
  ['Other', 'अन्य', 'અન્ય'],
  ['Page', 'पेज', 'પેજ'],
  ['Pages', 'पेज', 'પેજ'],
  ['Passions', 'शौक़', 'શોખ'],
  ['Personality', 'व्यक्तित्व', 'વ્યક્તિત્વ'],
  ['Philosophy', 'दर्शन', 'દર્શન'],
  ['Politics', 'राजनीति', 'રાજકારણ'],
  ['Preserve', 'सहेजें', 'સાચવો'],
  ['Preserve a person’s personality, memories and voice from their own words, with their consent.', 'किसी के व्यक्तित्व, यादों और आवाज़ को उनके अपने शब्दों से, उनकी सहमति के साथ सहेजें।', 'કોઈના વ્યક્તિત્વ, યાદો અને અવાજને તેમના પોતાના શબ્દોમાંથી, તેમની સંમતિ સાથે સાચવો.'],
  ['Preserve someone', 'किसी को सहेजें', 'કોઈને સાચવો'],
  ['Preserve someone you love', 'किसी अपने को सहेजें', 'કોઈ પોતાનાને સાચવો'],
  ['Pretrained', 'पहले से तैयार', 'પહેલેથી તૈયાર'],
  ['Pretrained models', 'पहले से तैयार मॉडल', 'પહેલેથી તૈયાર મોડેલ'],
  ['Private archive', 'निजी संग्रह', 'ખાનગી સંગ્રહ'],
  ['Questions', 'सवाल', 'પ્રશ્નો'],
  ['Relationships', 'रिश्ते', 'સંબંધો'],
  ['Roundtable', 'गोलमेज़', 'ગોળમેજી'],
  ['Runs on your machine · consent first', 'आपके कंप्यूटर पर चलता है · पहले सहमति', 'તમારા કમ્પ્યુટર પર ચાલે છે · પહેલા સંમતિ'],
  ['Science', 'विज्ञान', 'વિજ્ઞાન'],
  ['Search', 'खोजें', 'શોધો'],
  ['Search CHRONUS', 'CHRONUS में खोजें', 'CHRONUS માં શોધો'],
  ['Search pages, sections and models', 'पेज, हिस्से और मॉडल खोजें', 'પેજ, વિભાગો અને મોડેલ શોધો'],
  ['Search pages, sections, models…', 'पेज, हिस्से, मॉडल खोजें…', 'પેજ, વિભાગો, મોડેલ શોધો…'],
  ['Shortcuts', 'शॉर्टकट', 'શૉર્ટકટ'],
  ['Show these shortcuts', 'ये शॉर्टकट दिखाएँ', 'આ શૉર્ટકટ બતાવો'],
  ['Sign in', 'साइन इन करें', 'સાઇન ઇન કરો'],
  ['Sign in to your models', 'अपने मॉडल में साइन इन करें', 'તમારા મોડેલમાં સાઇન ઇન કરો'],
  ['Skip to content', 'सामग्री पर जाएँ', 'સામગ્રી પર જાઓ'],
  ['Someone', 'कोई', 'કોઈ'],
  ['Start', 'शुरू करें', 'શરૂ કરો'],
  ['Switch light and dark theme', 'लाइट और डार्क थीम बदलें', 'લાઇટ અને ડાર્ક થીમ બદલો'],
  ['Switch to dark theme', 'डार्क थीम पर जाएँ', 'ડાર્ક થીમ પર જાઓ'],
  ['Switch to light theme', 'लाइट थीम पर जाएँ', 'લાઇટ થીમ પર જાઓ'],
  ['System', 'सिस्टम', 'સિસ્ટમ'],
  ['Table', 'तालिका', 'કોષ્ટક'],
  ['Talk to {name}', '{name} से बात करें', '{name} સાથે વાત કરો'],
  ['Theme', 'थीम', 'થીમ'],
  ['They are answering', 'वे ख़ुद जवाब दे रहे हैं', 'તેઓ પોતે જવાબ આપી રહ્યા છે'],
  ['This CHRONUS server is protected. Ask whoever runs it for the code.', 'यह CHRONUS सर्वर सुरक्षित है। कोड के लिए इसे चलाने वाले से पूछें।', 'આ CHRONUS સર્વર સુરક્ષિત છે. કોડ માટે તેને ચલાવનારને પૂછો.'],
  ['This page wasn’t|preserved.', 'यह पेज|सहेजा नहीं गया।', 'આ પેજ|સચવાયું નથી.'],
  ['Voice', 'आवाज़', 'અવાજ'],
  ['Voice studio', 'वॉइस स्टूडियो', 'વૉઇસ સ્ટુડિયો'],
  ['Your models', 'आपके मॉडल', 'તમારા મોડેલ'],
  ['Yours', 'आपका', 'તમારું'],
  ['close', 'बंद करें', 'બંધ કરો'],
  ['move', 'चलें', 'ખસો'],
  ['open', 'खोलें', 'ખોલો'],
  ['preserved.', 'सहेजा हुआ।', 'સચવાયેલું.'],
  ['{name}’s memories', '{name} की यादें', '{name}ની યાદો'],
  ['{n} questions', '{n} सवाल', '{n} પ્રશ્નો'],
  // Company website links in the nav, footer and search (the pages themselves are English only for now)
  ['About us', 'हमारे बारे में', 'અમારા વિશે'],
  ['All policies', 'सभी नीतियाँ', 'બધી નીતિઓ'],
  ['CHRONUS Lab', 'CHRONUS लैब', 'CHRONUS લેબ'],
  ['Company', 'कंपनी', 'કંપની'],
  ['Contact', 'संपर्क', 'સંપર્ક'],
  ['For partners', 'साझेदारों के लिए', 'ભાગીદારો માટે'],
  ['Join the waitlist', 'प्रतीक्षा सूची में जुड़ें', 'રાહ યાદીમાં જોડાઓ'],
  ['Lab', 'लैब', 'લેબ'],
  ['Pricing', 'क़ीमतें', 'કિંમતો'],
  ['Privacy', 'निजता', 'ગોપનીયતા'],
  ['Product', 'उत्पाद', 'ઉત્પાદન'],
  ['Registered in {where}, company no. {number}', '{where} में पंजीकृत, कंपनी संख्या {number}', '{where}માં નોંધાયેલ, કંપની નંબર {number}'],
  ['Report a model', 'मॉडल की शिकायत करें', 'મોડેલની ફરિયાદ કરો'],
  ['Research', 'शोध', 'સંશોધન'],
  ['Terms', 'शर्तें', 'શરતો'],
  ['Trust & legal', 'भरोसा और क़ानूनी', 'ભરોસો અને કાનૂની'],
  ['Trust centre', 'भरोसा केंद्र', 'ભરોસા કેન્દ્ર'],
  ['Vision', 'दृष्टि', 'દ્રષ્ટિ'],
  ['Wellbeing and support', 'भलाई और सहायता', 'સુખાકારી અને સહાય'],
  ['Your account', 'आपका खाता', 'તમારું ખાતું'],
  // The guided interview, exactly as the server sends it (data/interview_protocol.py)
  ['How would you describe your core personality in a few sentences?', 'आप अपने मूल व्यक्तित्व को कुछ वाक्यों में कैसे बताएँगे?', 'તમે તમારા મૂળ વ્યક્તિત્વને થોડાં વાક્યોમાં કેવી રીતે વર્ણવશો?'],
  ['What are your most distinctive habits or quirks that people notice about you?', 'आपकी कौन-सी ख़ास आदतें या अनोखी बातें लोग आपमें नोटिस करते हैं?', 'તમારી કઈ ખાસ આદતો કે અનોખી વાતો લોકો તમારામાં નોંધે છે?'],
  ['How do you typically react under extreme pressure or stress?', 'बहुत ज़्यादा दबाव या तनाव में आप आमतौर पर कैसी प्रतिक्रिया देते हैं?', 'ખૂબ દબાણ કે તણાવમાં તમે સામાન્ય રીતે કેવી પ્રતિક્રિયા આપો છો?'],
  ["Would you say you're more of an optimist or a realist? How does that shape your worldview?", 'आप ख़ुद को ज़्यादा आशावादी मानते हैं या यथार्थवादी? इससे दुनिया को देखने का आपका नज़रिया कैसे बनता है?', 'તમે તમારી જાતને વધુ આશાવાદી માનો છો કે વાસ્તવવાદી? તેનાથી દુનિયાને જોવાની તમારી દૃષ્ટિ કેવી રીતે ઘડાય છે?'],
  ['What experience or period in your life most fundamentally shaped who you are today?', 'आपके जीवन के किस अनुभव या दौर ने आपको सबसे ज़्यादा वैसा बनाया जैसे आप आज हैं?', 'તમારા જીવનના કયા અનુભવ કે સમયગાળાએ તમને સૌથી વધુ આજે જેવા છો તેવા બનાવ્યા?'],
  ["What's a decision you made that most people thought was crazy, but you knew was right?", 'आपका कौन-सा फ़ैसला ज़्यादातर लोगों को पागलपन लगा, पर आप जानते थे कि वह सही था?', 'તમારો કયો નિર્ણય મોટાભાગના લોકોને ગાંડપણ લાગ્યો, પણ તમે જાણતા હતા કે તે સાચો હતો?'],
  ["What's the hardest thing you've ever had to do professionally or personally?", 'काम में या निजी जीवन में आपको अब तक सबसे मुश्किल काम कौन-सा करना पड़ा?', 'કામમાં કે અંગત જીવનમાં તમારે અત્યાર સુધી સૌથી મુશ્કેલ કામ કયું કરવું પડ્યું?'],
  ['Is there a moment that still affects you deeply when you think about it?', 'क्या कोई ऐसा पल है जिसके बारे में सोचकर आप आज भी गहराई से भावुक हो जाते हैं?', 'શું કોઈ એવી ક્ષણ છે જેના વિશે વિચારીને તમે આજે પણ ઊંડે સુધી ભાવુક થઈ જાઓ છો?'],
  ['Who has been the most influential person in your life and why?', 'आपके जीवन में सबसे ज़्यादा असर किसका रहा है, और क्यों?', 'તમારા જીવનમાં સૌથી વધુ પ્રભાવ કોનો રહ્યો છે, અને શા માટે?'],
  ['How would your closest friends or family describe you?', 'आपके सबसे क़रीबी दोस्त या परिवार वाले आपको कैसे बताएँगे?', 'તમારા સૌથી નજીકના મિત્રો કે પરિવારજનો તમને કેવી રીતે વર્ણવશે?'],
  ['What do you value most in your relationships with people?', 'लोगों के साथ अपने रिश्तों में आप किस बात को सबसे ज़्यादा अहमियत देते हैं?', 'લોકો સાથેના તમારા સંબંધોમાં તમે કઈ વાતને સૌથી વધુ મહત્ત્વ આપો છો?'],
  ['How has your approach to collaboration or partnerships evolved over time?', 'साथ मिलकर काम करने या साझेदारी को लेकर आपका तरीक़ा समय के साथ कैसे बदला है?', 'સાથે મળીને કામ કરવા કે ભાગીદારી અંગેનો તમારો અભિગમ સમય સાથે કેવી રીતે બદલાયો છે?'],
  ['What gets you genuinely excited to wake up in the morning?', 'कौन-सी बात आपको सुबह उठने के लिए सच में उत्साहित करती है?', 'કઈ વાત તમને સવારે ઊઠવા માટે ખરેખર ઉત્સાહિત કરે છે?'],
  ['Outside of your main work, what do you spend time thinking about or doing?', 'अपने मुख्य काम के अलावा, आप किस बारे में सोचने या क्या करने में समय बिताते हैं?', 'તમારા મુખ્ય કામ સિવાય, તમે શેના વિશે વિચારવામાં કે શું કરવામાં સમય વિતાવો છો?'],
  ['What topic could you talk about for hours without getting bored?', 'किस विषय पर आप घंटों बिना ऊबे बात कर सकते हैं?', 'કયા વિષય પર તમે કલાકો સુધી કંટાળ્યા વિના વાત કરી શકો?'],
  ["What's something you've always wanted to explore but haven't had the chance to?", 'ऐसा क्या है जिसे आप हमेशा से जानना या आज़माना चाहते थे, पर मौक़ा नहीं मिला?', 'એવું શું છે જે તમે હંમેશાં જાણવા કે અજમાવવા માગતા હતા, પણ તક ન મળી?'],
  ['What principle or belief would you never compromise on, no matter the cost?', 'ऐसा कौन-सा सिद्धांत या विश्वास है जिस पर आप किसी भी क़ीमत पर समझौता नहीं करेंगे?', 'એવો કયો સિદ્ધાંત કે વિશ્વાસ છે જેના પર તમે કોઈ પણ કિંમતે સમાધાન નહીં કરો?'],
  ['How do you think about ethics when making difficult decisions?', 'मुश्किल फ़ैसले लेते समय आप नैतिकता के बारे में कैसे सोचते हैं?', 'મુશ્કેલ નિર્ણયો લેતી વખતે તમે નૈતિકતા વિશે કેવી રીતે વિચારો છો?'],
  ["What's your view on the purpose of human existence or civilization?", 'मानव अस्तित्व या सभ्यता के उद्देश्य पर आपकी क्या राय है?', 'માનવ અસ્તિત્વ કે સભ્યતાના હેતુ વિશે તમારો શું મત છે?'],
  ['What do you think people fundamentally misunderstand about you?', 'आपके बारे में लोग बुनियादी तौर पर क्या ग़लत समझते हैं?', 'તમારા વિશે લોકો મૂળભૂત રીતે શું ખોટું સમજે છે?'],
  ['How would you describe your communication style?', 'आप अपने बात करने के तरीक़े को कैसे बताएँगे?', 'તમે તમારી વાત કરવાની રીતને કેવી રીતે વર્ણવશો?'],
  ["What words or phrases do you use frequently that feel distinctly 'you'?", 'आप कौन-से शब्द या वाक्यांश अक्सर बोलते हैं जो ख़ास आपके लगते हैं?', 'તમે કયા શબ્દો કે વાક્યો વારંવાર બોલો છો જે ખાસ તમારા લાગે છે?'],
  ['Do you tend to be more direct or more diplomatic? Give an example.', 'आप ज़्यादा सीधी बात करते हैं या ज़्यादा सोच-समझकर? एक उदाहरण दें।', 'તમે વધુ સીધી વાત કરો છો કે વધુ વિચારીને? એક ઉદાહરણ આપો.'],
  ['How do you usually end a conversation or close a thought?', 'आप आमतौर पर कोई बातचीत या कोई विचार कैसे ख़त्म करते हैं?', 'તમે સામાન્ય રીતે કોઈ વાતચીત કે વિચાર કેવી રીતે પૂરો કરો છો?'],
  ['What tone do you naturally default to — serious, humorous, sarcastic, philosophical?', 'आपका स्वाभाविक लहजा कैसा होता है — गंभीर, मज़ाकिया, व्यंग्यात्मक या दार्शनिक?', 'તમારો સ્વાભાવિક લહેકો કેવો હોય છે — ગંભીર, રમૂજી, કટાક્ષભર્યો કે તત્ત્વજ્ઞાની?'],
  ['What words or phrases do you use frequently that feel distinctly “you”?', 'आप कौन-से शब्द या वाक्यांश अक्सर बोलते हैं जो ख़ास आपके लगते हैं?', 'તમે કયા શબ્દો કે વાક્યો વારંવાર બોલો છો જે ખાસ તમારા લાગે છે?'],
]
