// The chat page and its parts (sources, feedback, time travel, "About this
// model") in English, Hindi and Gujarati (merged into i18n.jsx). Names of
// server values (mode, confidence, reason, voice) are looked up with t.label.
// The Hindi and Gujarati were drafted for CHRONUS; have a native speaker check them.

export const CHAT = {
  en: {
    'mode.natural': 'AI voice', 'mode.mix_method': 'Verbatim quotes', 'mode.mix_method_fallback': 'Verbatim quotes, AI answer not used',
    'mode.basic_info': 'Profile fact', 'mode.fallback': 'Not enough evidence', 'mode.support': 'Support information',
    'conf.high': 'high', 'conf.medium': 'medium', 'conf.low': 'low', 'conf.label': '{level} confidence',
    'reason.not_their_words': 'Not their words', 'reason.wrong_attribution': 'Wrong source', 'reason.incorrect': 'Factually wrong',
    'reason.unhelpful': "Didn't answer", 'reason.other': 'Something else',
    'voices.first_person': 'own words', 'voices.third_party': 'written by others', 'voices.synthesized': 'synthesized',
    'elonVoices.first_person': 'his words', 'elonVoices.third_party': 'about him', 'elonVoices.synthesized': 'synthesized',
    'aboutVoices.first_person': 'in their own words', 'aboutVoices.third_party': 'written by others', 'aboutVoices.synthesized': 'synthesized summaries',
    'chat.speakerInferred': "AI told this transcript's speakers apart, so a line may now and then be the interviewer's.",
    'chat.you': 'You','chat.match': 'match {pct}%', 'chat.listenStandIn': '▶ Listen (stand-in voice, not theirs)', 'chat.listenTheirs': '▶ Listen in their voice',
    'chat.standInTip': "A synthetic voice chosen for this model. It is not a recording or copy of the real person's voice.", 'chat.generating': 'Generating voice…',
    'chat.readAloud': '🔊 Read aloud', 'chat.originalEnglish': 'Original (English)', 'chat.whyConfidence': 'Why this confidence?',
    'chat.whyEmpty': 'This model has no memories to search yet.',
    'chat.whyRefused': "The closest memory matched {best}%, and this model only answers above {threshold}%. So instead of guessing, it says it doesn't know.",
    'chat.whyAnswered': 'The best source matches the question {best}% (this model answers from {threshold}% up). Sources used: {sources}, {own} in their own words. Higher matches and own words mean higher confidence.',
    'chat.copied': '✓ Copied', 'chat.copy': 'Copy', 'chat.greetingMeta': 'Model initialization', 'chat.error': 'Error: {message}',
    'chat.clearConfirm': 'Clear this conversation from this browser?',
    'chat.voiceBrowser': "Uses your browser's speech recognition, which may send audio to its provider", 'chat.voiceLocal': 'Transcribed on this computer',
    'chat.offline': 'Offline', 'chat.live': 'Live', 'chat.connecting': 'Connecting', 'chat.options': 'Chat options', 'chat.timeTravel': 'Time travel',
    'chat.langTip': 'Answer language (translated by AI)', 'chat.langNeedsAi': 'Other languages need AI voice for this model',
    'chat.answerLanguage': 'Answer language', 'chat.sameAsQuestion': 'Same as question',
    'chat.lengthTip': 'How long answers should be', 'chat.answerLength': 'Answer length', 'chat.short': 'Short', 'chat.normal': 'Normal length', 'chat.detailed': 'Detailed',
    'chat.conversationTip': 'Talk hands-free: it listens, answers aloud, then listens again. {note}.',
    'chat.endConversation': '■ End conversation', 'chat.voiceConversation': '🎧 Voice conversation',
    'chat.save': '⋯ Save', 'chat.markdown': 'Download as Markdown', 'chat.print': 'Print / save as PDF', 'chat.clear': 'Clear conversation',
    'chat.keptHere': 'Conversations are kept in this browser only.', 'chat.notSaved': 'This demo conversation is not saved.',
    'chat.conversationWith': 'Conversation with {name}',
    'chat.nudge': "You've been talking with {name}'s memories for a while. This is an archive, not the person. It's okay to take a break, or to talk to someone close to you.",
    'chat.nudgeMemorial': "You've been talking with {name}'s remembered words for a while. This is an archive, not the person. It's okay to take a break, or to talk to someone close to you.",
    'chat.takeBreak': 'Take a break', 'chat.keepGoing': 'Keep going',
    'chat.aiTip': 'AI answers in their voice, built from their own words', 'chat.aiOffTip': 'Off for this model: it would send excerpts to a cloud AI service',
    'chat.quotesTip': 'Only verbatim quotes from the sources, no AI writing',
    'chat.listening': 'Listening…', 'chat.transcribing': 'Transcribing…', 'chat.stopDictating': 'Stop dictating', 'chat.dictate': 'Dictate a question', 'chat.send': 'Send',
    'chat.greet.elon': "Hi, I'm a CHRONUS model of Elon Musk, built from his public interviews, tweets and biographies. Every answer is grounded in those sources, and you can check them under each reply.\n\nAsk me anything.",
    'chat.greet.pretrained': "I'm a CHRONUS model of {name}. {description} I answer only from these texts, and you can check the source of every reply.",
    'chat.greet.memorial': "These are {name}'s words, kept by the people who loved them. I can only share what they wrote or said, or what family remembered, and I'll show you where each answer comes from.",
    'chat.greet.custom': "Hi, I'm a CHRONUS model of {name}. I only answer from the documents and interview answers added to this model, and you can check the source of every reply.",
    'chat.disc.elon': "AI simulation built from Elon Musk's public interviews, tweets and biographies. It is not the real person and is not affiliated with him.",
    'chat.disc.pretrained': "AI simulation built from {name}'s public-domain writings ({titles}; Project Gutenberg). It is not the real person.",
    'chat.disc.memorial': "A memorial archive of {name}'s words, built with consent. It is not {name}, and it is not a substitute for grief support or the people around you.",
    'chat.disc.custom': 'AI simulation built from memories shared with consent. It is not the real person, and it is not a substitute for grief support or professional help.',
    'chat.allModels': '← All models', 'chat.yourModel': 'Your model', 'chat.pretrainedModel': 'Pretrained model', 'chat.notFound': 'Model not found',
    'chat.notBuilt': "{name} isn't built yet.", 'chat.finish': 'Finish building it',
    'fb.good': 'Good answer', 'fb.report': 'Report a problem', 'fb.thanks': 'Thanks, sent for review', 'fb.whatsWrong': "What's wrong", 'fb.note': 'Optional note for the reviewer',
    'viewer.source': 'Source {n}', 'viewer.inContext': 'In context', 'viewer.neighbouring': 'Neighbouring pages', 'viewer.p': 'p. {page}',
    'viewer.browse': 'Browse all memories of this model →',
    'tt.loading': 'Loading the timeline…', 'tt.undated': "None of this model's memories are dated, so time travel isn't available.",
    'tt.chart': 'Dated memories per year ({dated} dated, {undated} undated)', 'tt.tip': 'memories from {year}', 'tt.from': 'From', 'tt.to': 'to', 'tt.any': 'Any time',
    'tt.note': 'Undated memories (most interviews and books) are left out while a range is set.',
    'about.title': 'About this model', 'about.span': 'Dated memories span {first}–{last}.', 'about.sources': 'Main sources', 'about.interview': 'Interview answers',
    'about.texts': 'Texts:', 'about.careful': 'How careful it is',
    'about.threshold': "It answers only when a memory matches the question at least {pct}%; otherwise it says “I don't know”.",
    'about.consent': 'Consent recorded {date}: “{statement}”', 'about.aiOn': 'AI voice is on (excerpts are sent to a cloud AI service).',
    'about.aiOff': 'AI voice is off (verbatim quotes only; nothing leaves this computer).', 'about.memorial': 'Memorial mode is on.',
    'voiceIn.denied': 'Microphone access was denied.', 'voiceIn.error': 'Speech recognition: {error}', 'voiceIn.unavailable': 'Voice input is not available in this browser',
  },
  hi: {
    'mode.natural': 'AI आवाज़', 'mode.mix_method': 'शब्दशः उद्धरण', 'mode.mix_method_fallback': 'शब्दशः उद्धरण, AI जवाब इस्तेमाल नहीं हुआ',
    'mode.basic_info': 'प्रोफ़ाइल तथ्य', 'mode.fallback': 'पर्याप्त सबूत नहीं', 'mode.support': 'सहायता जानकारी',
    'conf.high': 'ऊँचा', 'conf.medium': 'मध्यम', 'conf.low': 'कम', 'conf.label': 'भरोसा: {level}',
    'reason.not_their_words': 'उनके शब्द नहीं', 'reason.wrong_attribution': 'गलत स्रोत', 'reason.incorrect': 'तथ्य गलत',
    'reason.unhelpful': 'जवाब नहीं दिया', 'reason.other': 'कुछ और',
    'voices.first_person': 'अपने शब्द', 'voices.third_party': 'दूसरों का लिखा', 'voices.synthesized': 'संश्लेषित',
    'elonVoices.first_person': 'उनके शब्द', 'elonVoices.third_party': 'उनके बारे में', 'elonVoices.synthesized': 'संश्लेषित',
    'aboutVoices.first_person': 'उनके अपने शब्दों में', 'aboutVoices.third_party': 'दूसरों का लिखा', 'aboutVoices.synthesized': 'संश्लेषित सारांश',
    'chat.speakerInferred': 'इस ट्रांसक्रिप्ट में बोलने वालों को AI ने अलग पहचाना है, इसलिए कभी-कभार कोई पंक्ति साक्षात्कारकर्ता की हो सकती है।',
    'chat.you': 'आप','chat.match': 'मेल {pct}%', 'chat.listenStandIn': '▶ सुनें (स्टैंड-इन आवाज़, उनकी नहीं)', 'chat.listenTheirs': '▶ उनकी आवाज़ में सुनें',
    'chat.standInTip': 'इस मॉडल के लिए चुनी गई एक कृत्रिम आवाज़। यह असली व्यक्ति की आवाज़ की रिकॉर्डिंग या नक़ल नहीं है।', 'chat.generating': 'आवाज़ बन रही है…',
    'chat.readAloud': '🔊 ज़ोर से पढ़ें', 'chat.originalEnglish': 'मूल (अंग्रेज़ी)', 'chat.whyConfidence': 'यह भरोसा क्यों?',
    'chat.whyEmpty': 'इस मॉडल में अभी खोजने के लिए कोई याद नहीं है।',
    'chat.whyRefused': 'सबसे करीबी याद {best}% मेल खाती थी, और यह मॉडल सिर्फ़ {threshold}% से ऊपर जवाब देता है। इसलिए अंदाज़ा लगाने के बजाय वह कहता है कि उसे नहीं पता।',
    'chat.whyAnswered': 'सबसे अच्छा स्रोत सवाल से {best}% मेल खाता है (यह मॉडल {threshold}% से ऊपर जवाब देता है)। इस्तेमाल हुए स्रोत: {sources}, जिनमें {own} उनके अपने शब्दों में। ज़्यादा मेल और अपने शब्द, यानी ज़्यादा भरोसा।',
    'chat.copied': '✓ कॉपी हुआ', 'chat.copy': 'कॉपी करें', 'chat.greetingMeta': 'मॉडल की शुरुआत', 'chat.error': 'त्रुटि: {message}',
    'chat.clearConfirm': 'यह बातचीत इस ब्राउज़र से हटाएँ?',
    'chat.voiceBrowser': 'आपके ब्राउज़र की आवाज़ पहचान इस्तेमाल होती है, जो ऑडियो उसके प्रदाता को भेज सकती है', 'chat.voiceLocal': 'इसी कंप्यूटर पर लिखा गया',
    'chat.offline': 'ऑफ़लाइन', 'chat.live': 'लाइव', 'chat.connecting': 'जुड़ रहा है', 'chat.options': 'चैट विकल्प', 'chat.timeTravel': 'टाइम ट्रैवल',
    'chat.langTip': 'जवाब की भाषा (AI द्वारा अनुवाद)', 'chat.langNeedsAi': 'इस मॉडल के लिए दूसरी भाषाओं में AI आवाज़ चाहिए',
    'chat.answerLanguage': 'जवाब की भाषा', 'chat.sameAsQuestion': 'सवाल वाली भाषा',
    'chat.lengthTip': 'जवाब कितने लंबे हों', 'chat.answerLength': 'जवाब की लंबाई', 'chat.short': 'छोटा', 'chat.normal': 'सामान्य लंबाई', 'chat.detailed': 'विस्तृत',
    'chat.conversationTip': 'बिना हाथ लगाए बात करें: यह सुनता है, ज़ोर से जवाब देता है, फिर से सुनता है। {note}।',
    'chat.endConversation': '■ बातचीत खत्म करें', 'chat.voiceConversation': '🎧 आवाज़ से बातचीत',
    'chat.save': '⋯ सहेजें', 'chat.markdown': 'Markdown के रूप में डाउनलोड करें', 'chat.print': 'प्रिंट / PDF के रूप में सहेजें', 'chat.clear': 'बातचीत हटाएँ',
    'chat.keptHere': 'बातचीत सिर्फ़ इसी ब्राउज़र में रखी जाती है।', 'chat.notSaved': 'यह डेमो बातचीत सहेजी नहीं जाती।',
    'chat.conversationWith': '{name} के साथ बातचीत',
    'chat.nudge': 'आप काफ़ी देर से {name} की यादों से बात कर रहे हैं। यह एक संग्रह है, वह व्यक्ति नहीं। थोड़ा आराम करना, या किसी अपने से बात करना ठीक है।',
    'chat.nudgeMemorial': 'आप काफ़ी देर से {name} के याद किए गए शब्दों से बात कर रहे हैं। यह एक संग्रह है, वह व्यक्ति नहीं। थोड़ा आराम करना, या किसी अपने से बात करना ठीक है।',
    'chat.takeBreak': 'आराम करें', 'chat.keepGoing': 'जारी रखें',
    'chat.aiTip': 'AI उनके अपने शब्दों से, उनकी आवाज़ में जवाब देता है', 'chat.aiOffTip': 'इस मॉडल के लिए बंद: यह अंश एक क्लाउड AI सेवा को भेजता',
    'chat.quotesTip': 'सिर्फ़ स्रोतों से शब्दशः उद्धरण, कोई AI लेखन नहीं',
    'chat.listening': 'सुन रहा है…', 'chat.transcribing': 'लिखा जा रहा है…', 'chat.stopDictating': 'बोलकर लिखना बंद करें', 'chat.dictate': 'सवाल बोलकर लिखें', 'chat.send': 'भेजें',
    'chat.greet.elon': 'नमस्ते, मैं एलन मस्क का CHRONUS मॉडल हूँ, जो उनके सार्वजनिक साक्षात्कारों, ट्वीट्स और जीवनियों से बना है। हर जवाब उन्हीं स्रोतों पर आधारित है, और आप हर जवाब के नीचे उन्हें जाँच सकते हैं।\n\nकुछ भी पूछें।',
    'chat.greet.pretrained': 'मैं {name} का CHRONUS मॉडल हूँ। {description} मैं सिर्फ़ इन्हीं पाठों से जवाब देता हूँ, और आप हर जवाब का स्रोत जाँच सकते हैं।',
    'chat.greet.memorial': 'ये {name} के शब्द हैं, जिन्हें उनसे प्यार करने वालों ने सहेजा है। मैं सिर्फ़ वही बता सकता हूँ जो उन्होंने लिखा या कहा, या जो परिवार को याद है, और मैं दिखाऊँगा कि हर जवाब कहाँ से आया।',
    'chat.greet.custom': 'नमस्ते, मैं {name} का CHRONUS मॉडल हूँ। मैं सिर्फ़ इस मॉडल में जोड़े गए दस्तावेज़ों और साक्षात्कार के जवाबों से जवाब देता हूँ, और आप हर जवाब का स्रोत जाँच सकते हैं।',
    'chat.disc.elon': 'एलन मस्क के सार्वजनिक साक्षात्कारों, ट्वीट्स और जीवनियों से बना AI सिमुलेशन। यह असली व्यक्ति नहीं है और उनसे संबद्ध नहीं है।',
    'chat.disc.pretrained': '{name} के सार्वजनिक डोमेन लेखन ({titles}; Project Gutenberg) से बना AI सिमुलेशन। यह असली व्यक्ति नहीं है।',
    'chat.disc.memorial': 'सहमति से बना {name} के शब्दों का एक स्मृति-संग्रह। यह {name} नहीं है, और यह शोक में सहारे या आपके आसपास के लोगों की जगह नहीं ले सकता।',
    'chat.disc.custom': 'सहमति से साझा की गई यादों से बना AI सिमुलेशन। यह असली व्यक्ति नहीं है, और यह शोक में सहारे या पेशेवर मदद की जगह नहीं ले सकता।',
    'chat.allModels': '← सभी मॉडल', 'chat.yourModel': 'आपका मॉडल', 'chat.pretrainedModel': 'पहले से बना मॉडल', 'chat.notFound': 'मॉडल नहीं मिला',
    'chat.notBuilt': '{name} अभी बना नहीं है।', 'chat.finish': 'इसे पूरा बनाएँ',
    'fb.good': 'अच्छा जवाब', 'fb.report': 'समस्या बताएँ', 'fb.thanks': 'धन्यवाद, समीक्षा के लिए भेजा गया', 'fb.whatsWrong': 'क्या गलत है', 'fb.note': 'समीक्षक के लिए वैकल्पिक नोट',
    'viewer.source': 'स्रोत {n}', 'viewer.inContext': 'संदर्भ में', 'viewer.neighbouring': 'आसपास के पेज', 'viewer.p': 'पृ. {page}',
    'viewer.browse': 'इस मॉडल की सारी यादें देखें →',
    'tt.loading': 'टाइमलाइन लोड हो रही है…', 'tt.undated': 'इस मॉडल की किसी याद पर तारीख़ नहीं है, इसलिए टाइम ट्रैवल उपलब्ध नहीं है।',
    'tt.chart': 'हर साल की तारीख़ वाली यादें ({dated} तारीख़ वाली, {undated} बिना तारीख़)', 'tt.tip': '{year} की यादें', 'tt.from': 'शुरुआत', 'tt.to': 'अंत', 'tt.any': 'कभी भी',
    'tt.note': 'सीमा तय रहने पर बिना तारीख़ वाली यादें (ज़्यादातर साक्षात्कार और किताबें) छोड़ दी जाती हैं।',
    'about.title': 'इस मॉडल के बारे में', 'about.span': 'तारीख़ वाली यादें {first}–{last} तक फैली हैं।', 'about.sources': 'मुख्य स्रोत', 'about.interview': 'साक्षात्कार के जवाब',
    'about.texts': 'पाठ:', 'about.careful': 'यह कितना सावधान है',
    'about.threshold': 'यह तभी जवाब देता है जब कोई याद सवाल से कम से कम {pct}% मेल खाए; वरना कहता है “मुझे नहीं पता”।',
    'about.consent': 'सहमति दर्ज {date}: “{statement}”', 'about.aiOn': 'AI आवाज़ चालू है (अंश एक क्लाउड AI सेवा को भेजे जाते हैं)।',
    'about.aiOff': 'AI आवाज़ बंद है (सिर्फ़ शब्दशः उद्धरण; इस कंप्यूटर से कुछ बाहर नहीं जाता)।', 'about.memorial': 'स्मृति मोड चालू है।',
    'voiceIn.denied': 'माइक्रोफ़ोन की अनुमति नहीं मिली।', 'voiceIn.error': 'आवाज़ पहचान: {error}', 'voiceIn.unavailable': 'इस ब्राउज़र में आवाज़ से लिखना उपलब्ध नहीं है',
  },
  gu: {
    'mode.natural': 'AI અવાજ', 'mode.mix_method': 'શબ્દશઃ અવતરણ', 'mode.mix_method_fallback': 'શબ્દશઃ અવતરણ, AI જવાબ વપરાયો નથી',
    'mode.basic_info': 'પ્રોફાઇલ હકીકત', 'mode.fallback': 'પૂરતા પુરાવા નથી', 'mode.support': 'સહાય માહિતી',
    'conf.high': 'ઊંચો', 'conf.medium': 'મધ્યમ', 'conf.low': 'ઓછો', 'conf.label': 'ભરોસો: {level}',
    'reason.not_their_words': 'તેમના શબ્દો નથી', 'reason.wrong_attribution': 'ખોટો સ્રોત', 'reason.incorrect': 'હકીકતમાં ખોટું',
    'reason.unhelpful': 'જવાબ ન આપ્યો', 'reason.other': 'બીજું કંઈક',
    'voices.first_person': 'પોતાના શબ્દો', 'voices.third_party': 'બીજાએ લખેલું', 'voices.synthesized': 'સંશ્લેષિત',
    'elonVoices.first_person': 'તેમના શબ્દો', 'elonVoices.third_party': 'તેમના વિશે', 'elonVoices.synthesized': 'સંશ્લેષિત',
    'aboutVoices.first_person': 'તેમના પોતાના શબ્દોમાં', 'aboutVoices.third_party': 'બીજાએ લખેલું', 'aboutVoices.synthesized': 'સંશ્લેષિત સારાંશ',
    'chat.speakerInferred': 'આ ટ્રાન્સક્રિપ્ટમાં બોલનારાઓને AIએ અલગ ઓળખ્યા છે, એટલે ક્યારેક કોઈ લીટી ઇન્ટરવ્યૂ લેનારની હોઈ શકે.',
    'chat.you': 'તમે','chat.match': 'મેળ {pct}%', 'chat.listenStandIn': '▶ સાંભળો (સ્ટેન્ડ-ઇન અવાજ, તેમનો નહીં)', 'chat.listenTheirs': '▶ તેમના અવાજમાં સાંભળો',
    'chat.standInTip': 'આ મોડેલ માટે પસંદ કરેલો કૃત્રિમ અવાજ. આ સાચી વ્યક્તિના અવાજનું રેકોર્ડિંગ કે નકલ નથી.', 'chat.generating': 'અવાજ બની રહ્યો છે…',
    'chat.readAloud': '🔊 મોટેથી વાંચો', 'chat.originalEnglish': 'મૂળ (અંગ્રેજી)', 'chat.whyConfidence': 'આ ભરોસો કેમ?',
    'chat.whyEmpty': 'આ મોડેલમાં હજી શોધવા માટે કોઈ યાદ નથી.',
    'chat.whyRefused': 'સૌથી નજીકની યાદ {best}% મળતી હતી, અને આ મોડેલ ફક્ત {threshold}% થી ઉપર જવાબ આપે છે. એટલે અનુમાન કરવાને બદલે તે કહે છે કે તેને ખબર નથી.',
    'chat.whyAnswered': 'સૌથી સારો સ્રોત પ્રશ્ન સાથે {best}% મળે છે (આ મોડેલ {threshold}% થી ઉપર જવાબ આપે છે). વપરાયેલા સ્રોત: {sources}, જેમાંથી {own} તેમના પોતાના શબ્દોમાં. વધુ મેળ અને પોતાના શબ્દો એટલે વધુ ભરોસો.',
    'chat.copied': '✓ કૉપી થયું', 'chat.copy': 'કૉપી કરો', 'chat.greetingMeta': 'મોડેલની શરૂઆત', 'chat.error': 'ભૂલ: {message}',
    'chat.clearConfirm': 'આ વાતચીત આ બ્રાઉઝરમાંથી દૂર કરવી છે?',
    'chat.voiceBrowser': 'તમારા બ્રાઉઝરની અવાજ ઓળખ વપરાય છે, જે ઑડિયો તેના પ્રદાતાને મોકલી શકે છે', 'chat.voiceLocal': 'આ જ કમ્પ્યુટર પર લખાયું',
    'chat.offline': 'ઑફલાઇન', 'chat.live': 'લાઇવ', 'chat.connecting': 'જોડાઈ રહ્યું છે', 'chat.options': 'ચેટ વિકલ્પો', 'chat.timeTravel': 'ટાઇમ ટ્રાવેલ',
    'chat.langTip': 'જવાબની ભાષા (AI દ્વારા અનુવાદ)', 'chat.langNeedsAi': 'આ મોડેલ માટે બીજી ભાષાઓમાં AI અવાજ જોઈએ',
    'chat.answerLanguage': 'જવાબની ભાષા', 'chat.sameAsQuestion': 'પ્રશ્નની ભાષા',
    'chat.lengthTip': 'જવાબ કેટલા લાંબા હોય', 'chat.answerLength': 'જવાબની લંબાઈ', 'chat.short': 'ટૂંકો', 'chat.normal': 'સામાન્ય લંબાઈ', 'chat.detailed': 'વિગતવાર',
    'chat.conversationTip': 'હાથ લગાડ્યા વગર વાત કરો: તે સાંભળે છે, મોટેથી જવાબ આપે છે, પછી ફરી સાંભળે છે. {note}.',
    'chat.endConversation': '■ વાતચીત પૂરી કરો', 'chat.voiceConversation': '🎧 અવાજથી વાતચીત',
    'chat.save': '⋯ સાચવો', 'chat.markdown': 'Markdown તરીકે ડાઉનલોડ કરો', 'chat.print': 'પ્રિન્ટ / PDF તરીકે સાચવો', 'chat.clear': 'વાતચીત દૂર કરો',
    'chat.keptHere': 'વાતચીત ફક્ત આ જ બ્રાઉઝરમાં રહે છે.', 'chat.notSaved': 'આ ડેમો વાતચીત સાચવવામાં આવતી નથી.',
    'chat.conversationWith': '{name} સાથે વાતચીત',
    'chat.nudge': 'તમે ઘણા સમયથી {name}ની યાદો સાથે વાત કરી રહ્યા છો. આ એક સંગ્રહ છે, એ વ્યક્તિ નહીં. થોડો આરામ કરવો, અથવા કોઈ નજીકની વ્યક્તિ સાથે વાત કરવી બરાબર છે.',
    'chat.nudgeMemorial': 'તમે ઘણા સમયથી {name}ના યાદ કરેલા શબ્દો સાથે વાત કરી રહ્યા છો. આ એક સંગ્રહ છે, એ વ્યક્તિ નહીં. થોડો આરામ કરવો, અથવા કોઈ નજીકની વ્યક્તિ સાથે વાત કરવી બરાબર છે.',
    'chat.takeBreak': 'આરામ કરો', 'chat.keepGoing': 'ચાલુ રાખો',
    'chat.aiTip': 'AI તેમના પોતાના શબ્દોમાંથી, તેમના અવાજમાં જવાબ આપે છે', 'chat.aiOffTip': 'આ મોડેલ માટે બંધ: તે અંશો ક્લાઉડ AI સેવાને મોકલે',
    'chat.quotesTip': 'ફક્ત સ્રોતોમાંથી શબ્દશઃ અવતરણ, કોઈ AI લખાણ નહીં',
    'chat.listening': 'સાંભળી રહ્યું છે…', 'chat.transcribing': 'લખાઈ રહ્યું છે…', 'chat.stopDictating': 'બોલીને લખવાનું બંધ કરો', 'chat.dictate': 'પ્રશ્ન બોલીને લખો', 'chat.send': 'મોકલો',
    'chat.greet.elon': 'નમસ્તે, હું ઇલોન મસ્કનું CHRONUS મોડેલ છું, જે તેમના જાહેર ઇન્ટરવ્યૂ, ટ્વીટ્સ અને જીવનચરિત્રોમાંથી બનેલું છે. દરેક જવાબ એ જ સ્રોતો પર આધારિત છે, અને તમે દરેક જવાબ નીચે તેમને ચકાસી શકો છો.\n\nકંઈ પણ પૂછો.',
    'chat.greet.pretrained': 'હું {name}નું CHRONUS મોડેલ છું. {description} હું ફક્ત આ લખાણોમાંથી જવાબ આપું છું, અને તમે દરેક જવાબનો સ્રોત ચકાસી શકો છો.',
    'chat.greet.memorial': 'આ {name}ના શબ્દો છે, જેને તેમને પ્રેમ કરનારા લોકોએ સાચવ્યા છે. હું ફક્ત એ જ કહી શકું જે તેમણે લખ્યું કે કહ્યું, અથવા પરિવારને જે યાદ છે, અને હું બતાવીશ કે દરેક જવાબ ક્યાંથી આવે છે.',
    'chat.greet.custom': 'નમસ્તે, હું {name}નું CHRONUS મોડેલ છું. હું ફક્ત આ મોડેલમાં ઉમેરાયેલા દસ્તાવેજો અને ઇન્ટરવ્યૂના જવાબોમાંથી જવાબ આપું છું, અને તમે દરેક જવાબનો સ્રોત ચકાસી શકો છો.',
    'chat.disc.elon': 'ઇલોન મસ્કના જાહેર ઇન્ટરવ્યૂ, ટ્વીટ્સ અને જીવનચરિત્રોમાંથી બનેલું AI સિમ્યુલેશન. આ સાચી વ્યક્તિ નથી અને તેમની સાથે સંકળાયેલું નથી.',
    'chat.disc.pretrained': '{name}ના જાહેર ડોમેન લખાણો ({titles}; Project Gutenberg) માંથી બનેલું AI સિમ્યુલેશન. આ સાચી વ્યક્તિ નથી.',
    'chat.disc.memorial': 'સંમતિથી બનેલો {name}ના શબ્દોનો સ્મૃતિ-સંગ્રહ. આ {name} નથી, અને તે શોકમાં સહારો કે તમારી આસપાસના લોકોની જગ્યા લઈ શકતો નથી.',
    'chat.disc.custom': 'સંમતિથી વહેંચાયેલી યાદોમાંથી બનેલું AI સિમ્યુલેશન. આ સાચી વ્યક્તિ નથી, અને તે શોકમાં સહારો કે વ્યાવસાયિક મદદની જગ્યા લઈ શકતું નથી.',
    'chat.allModels': '← બધા મોડેલ', 'chat.yourModel': 'તમારું મોડેલ', 'chat.pretrainedModel': 'પહેલેથી બનેલું મોડેલ', 'chat.notFound': 'મોડેલ મળ્યું નથી',
    'chat.notBuilt': '{name} હજી બન્યું નથી.', 'chat.finish': 'તેને પૂરું બનાવો',
    'fb.good': 'સારો જવાબ', 'fb.report': 'સમસ્યા જણાવો', 'fb.thanks': 'આભાર, સમીક્ષા માટે મોકલ્યું', 'fb.whatsWrong': 'શું ખોટું છે', 'fb.note': 'સમીક્ષક માટે વૈકલ્પિક નોંધ',
    'viewer.source': 'સ્રોત {n}', 'viewer.inContext': 'સંદર્ભમાં', 'viewer.neighbouring': 'આસપાસનાં પાનાં', 'viewer.p': 'પા. {page}',
    'viewer.browse': 'આ મોડેલની બધી યાદો જુઓ →',
    'tt.loading': 'ટાઇમલાઇન લોડ થઈ રહી છે…', 'tt.undated': 'આ મોડેલની કોઈ યાદ પર તારીખ નથી, એટલે ટાઇમ ટ્રાવેલ ઉપલબ્ધ નથી.',
    'tt.chart': 'દર વર્ષની તારીખવાળી યાદો ({dated} તારીખવાળી, {undated} તારીખ વગરની)', 'tt.tip': '{year}ની યાદો', 'tt.from': 'શરૂઆત', 'tt.to': 'અંત', 'tt.any': 'કોઈ પણ સમય',
    'tt.note': 'શ્રેણી નક્કી હોય ત્યારે તારીખ વગરની યાદો (મોટા ભાગના ઇન્ટરવ્યૂ અને પુસ્તકો) બાકાત રહે છે.',
    'about.title': 'આ મોડેલ વિશે', 'about.span': 'તારીખવાળી યાદો {first}–{last} સુધી ફેલાયેલી છે.', 'about.sources': 'મુખ્ય સ્રોતો', 'about.interview': 'ઇન્ટરવ્યૂના જવાબો',
    'about.texts': 'લખાણો:', 'about.careful': 'તે કેટલું સાવચેત છે',
    'about.threshold': 'કોઈ યાદ પ્રશ્ન સાથે ઓછામાં ઓછી {pct}% મળે ત્યારે જ તે જવાબ આપે છે; નહીંતર કહે છે “મને ખબર નથી”.',
    'about.consent': 'સંમતિ નોંધાઈ {date}: “{statement}”', 'about.aiOn': 'AI અવાજ ચાલુ છે (અંશો ક્લાઉડ AI સેવાને મોકલાય છે).',
    'about.aiOff': 'AI અવાજ બંધ છે (ફક્ત શબ્દશઃ અવતરણ; આ કમ્પ્યુટરમાંથી કંઈ બહાર જતું નથી).', 'about.memorial': 'સ્મૃતિ મોડ ચાલુ છે.',
    'voiceIn.denied': 'માઇક્રોફોનની પરવાનગી મળી નથી.', 'voiceIn.error': 'અવાજ ઓળખ: {error}', 'voiceIn.unavailable': 'આ બ્રાઉઝરમાં અવાજથી લખવાનું ઉપલબ્ધ નથી',
  },
}
