// [English, हिन्दी, ગુજરાતી]: preserving someone (create/*) and the models page
export const CREATE = [
  ['25 questions across six parts of who they are. Best answered with them, in their own words. Skip anything; come back any time.', 'वे कौन हैं, इसके छह हिस्सों में 25 सवाल। सबसे अच्छा है कि उन्हीं के साथ, उन्हीं के शब्दों में जवाब दें। कुछ भी छोड़ें; कभी भी लौटें।', 'તેઓ કોણ છે, તેના છ ભાગમાં 25 પ્રશ્નો. સૌથી સારું એ કે તેમની સાથે જ, તેમના જ શબ્દોમાં જવાબ આપો. કંઈ પણ છોડો; ગમે ત્યારે પાછા આવો.'],
  ['A language model may rephrase their words conversationally, always citing them. Off: answers are their exact words only.', 'एक भाषा मॉडल उनके शब्दों को बातचीत के लहजे में कह सकता है, हमेशा हवाले के साथ। बंद: जवाब सिर्फ़ उनके हूबहू शब्द।', 'એક ભાષા મોડેલ તેમના શબ્દોને વાતચીતના લહેકામાં કહી શકે છે, હંમેશાં હવાલા સાથે. બંધ: જવાબ ફક્ત તેમના એકસરખા શબ્દો.'],
  ['A line about them (optional)', 'उनके बारे में एक पंक्ति (वैकल्पिक)', 'તેમના વિશે એક લીટી (વૈકલ્પિક)'],
  ['About 45 seconds at a relaxed pace. Pauses are fine.', 'आराम से पढ़ने में लगभग 45 सेकंड। बीच में रुकना ठीक है।', 'આરામથી વાંચતાં લગભગ 45 સેકન્ડ. વચ્ચે અટકવું ઠીક છે.'],
  ['A password-protected .chronus file exported from any CHRONUS install.', 'किसी भी CHRONUS इंस्टॉल से निकाली गई पासवर्ड वाली .chronus फ़ाइल।', 'કોઈ પણ CHRONUS ઇન્સ્ટોલમાંથી કાઢેલી પાસવર્ડવાળી .chronus ફાઇલ.'],
  ['Active · review by {date}', 'सक्रिय · {date} तक समीक्षा', 'સક્રિય · {date} સુધીમાં સમીક્ષા'],
  ['Add a few more of their words or interview answers before building: a model needs at least {n} memories to answer well.', 'बनाने से पहले उनके कुछ और शब्द या इंटरव्यू जवाब जोड़ें: अच्छे जवाबों के लिए मॉडल को कम से कम {n} यादें चाहिए।', 'બનાવતા પહેલા તેમના થોડા વધુ શબ્દો કે ઇન્ટરવ્યૂ જવાબ ઉમેરો: સારા જવાબ માટે મોડેલને ઓછામાં ઓછી {n} યાદો જોઈએ.'],
  ['Add memories', 'यादें जोड़ें', 'યાદો ઉમેરો'],
  ['Add more memories', 'और यादें जोड़ें', 'વધુ યાદો ઉમેરો'],
  ['Allow the AI voice', 'AI आवाज़ की अनुमति दें', 'AI અવાજની પરવાનગી આપો'],
  ['Allowed', 'अनुमति है', 'પરવાનગી છે'],
  ['Answered', 'जवाब दिया', 'જવાબ આપ્યો'],
  ['Back', 'पीछे', 'પાછા'],
  ['Backup password', 'बैकअप पासवर्ड', 'બેકઅપ પાસવર્ડ'],
  ['Breadcrumb', 'पेज का रास्ता', 'પેજનો માર્ગ'],
  ['Browse and correct memories', 'यादें देखें और सुधारें', 'યાદો જુઓ અને સુધારો'],
  ['Build', 'बनाएँ', 'બનાવો'],
  ['Build a private model of someone in your life from their letters, journals, voice notes and a guided interview. Then talk with them, in their words and, with consent, their voice.', 'अपने जीवन के किसी व्यक्ति का निजी मॉडल उनकी चिट्ठियों, डायरियों, वॉइस नोट्स और निर्देशित इंटरव्यू से बनाएँ। फिर उनसे बात करें, उनके शब्दों में और, सहमति हो तो, उनकी आवाज़ में।', 'તમારા જીવનની કોઈ વ્યક્તિનું ખાનગી મોડેલ તેમના પત્રો, ડાયરીઓ, વૉઇસ નોટ્સ અને માર્ગદર્શિત ઇન્ટરવ્યૂમાંથી બનાવો. પછી તેમની સાથે વાત કરો, તેમના શબ્દોમાં અને, સંમતિ હોય તો, તેમના અવાજમાં.'],
  ['Calibrating the “I don’t know” threshold', '“मुझे नहीं पता” की सीमा तय हो रही है', '“મને ખબર નથી” ની મર્યાદા નક્કી થઈ રહી છે'],
  ['Cancel', 'रद्द करें', 'રદ કરો'],
  ['Can’t load the consent statement. Is the CHRONUS server running on port 8001?', 'सहमति का वक्तव्य लोड नहीं हो सका। क्या CHRONUS सर्वर पोर्ट 8001 पर चल रहा है?', 'સંમતિનું નિવેદન લોડ ન થઈ શક્યું. શું CHRONUS સર્વર પોર્ટ 8001 પર ચાલી રહ્યું છે?'],
  ['Checking the consent record', 'सहमति के रिकॉर्ड की जाँच', 'સંમતિના રેકોર્ડની તપાસ'],
  ['Choose a .chronus file', '.chronus फ़ाइल चुनें', '.chronus ફાઇલ પસંદ કરો'],
  ['Clone|their voice.', 'उनकी आवाज़|क्लोन करें।', 'તેમનો અવાજ|ક્લોન કરો.'],
  ['Cloned voice', 'क्लोन आवाज़', 'ક્લોન અવાજ'],
  ['Cloud processing.', 'क्लाउड प्रोसेसिंग।', 'ક્લાઉડ પ્રોસેસિંગ.'],
  ['Consent and privacy', 'सहमति और निजता', 'સંમતિ અને ગોપનીયતા'],
  ['Consent can change. So can this model.', 'सहमति बदल सकती है। यह मॉडल भी।', 'સંમતિ બદલાઈ શકે છે. આ મોડેલ પણ.'],
  ['Consent is due for renewal', 'सहमति का नवीनीकरण बाक़ी है', 'સંમતિનું નવીનીકરણ બાકી છે'],
  ['Consent record preview', 'सहमति रिकॉर्ड की झलक', 'સંમતિ રેકોર્ડની ઝલક'],
  ['Consent renewed for a year', 'सहमति एक साल के लिए नवीनीकृत', 'સંમતિ એક વર્ષ માટે નવીનીકૃત'],
  ['Consent revoked. {name} was deleted.', 'सहमति वापस ली गई। {name} को मिटा दिया गया।', 'સંમતિ પાછી ખેંચાઈ. {name} ને ભૂંસી નાખ્યું.'],
  ['Consent.', 'सहमति।', 'સંમતિ.'],
  ['Continue building', 'बनाना जारी रखें', 'બનાવવાનું ચાલુ રાખો'],
  ['Continue to consent', 'सहमति की ओर बढ़ें', 'સંમતિ તરફ આગળ વધો'],
  ['Create {name}’s model', '{name} का मॉडल बनाएँ', '{name}નું મોડેલ બનાવો'],
  ['Date', 'तारीख़', 'તારીખ'],
  ['Decrypting…', 'डिक्रिप्ट हो रहा है…', 'ડિક્રિપ્ટ થઈ રહ્યું છે…'],
  ['Delete', 'मिटाएँ', 'ભૂંસો'],
  ['Delete forever', 'हमेशा के लिए मिटाएँ', 'કાયમ માટે ભૂંસો'],
  ['Delete {name}', '{name} को मिटाएँ', '{name} ને ભૂંસો'],
  ['Delete {name}?', '{name} को मिटाएँ?', '{name} ને ભૂંસવું છે?'],
  ['Download backup', 'बैकअप डाउनलोड करें', 'બેકઅપ ડાઉનલોડ કરો'],
  ['Download {name} as a password-protected .chronus file you can import on any install.', '{name} को पासवर्ड वाली .chronus फ़ाइल के रूप में डाउनलोड करें, जिसे किसी भी इंस्टॉल पर इम्पोर्ट कर सकते हैं।', '{name} ને પાસવર્ડવાળી .chronus ફાઇલ તરીકે ડાઉનલોડ કરો, જે કોઈ પણ ઇન્સ્ટોલ પર ઇમ્પોર્ટ કરી શકાય.'],
  ['Draft', 'ड्राफ़्ट', 'ડ્રાફ્ટ'],
  ['Drop', 'छोड़ें', 'મૂકો'],
  ['Drop files here, or choose them', 'फ़ाइलें यहाँ छोड़ें, या चुनें', 'ફાઇલો અહીં મૂકો, અથવા પસંદ કરો'],
  ['Embedding with Sentence-BERT', 'Sentence-BERT से एम्बेडिंग', 'Sentence-BERT થી એમ્બેડિંગ'],
  ['Encrypted backup downloaded', 'एन्क्रिप्टेड बैकअप डाउनलोड हुआ', 'એન્ક્રિપ્ટેડ બેકઅપ ડાઉનલોડ થયો'],
  ['Encrypted backup · optional', 'एन्क्रिप्टेड बैकअप · वैकल्पिक', 'એન્ક્રિપ્ટેડ બેકઅપ · વૈકલ્પિક'],
  ['Encrypting…', 'एन्क्रिप्ट हो रहा है…', 'એન્ક્રિપ્ટ થઈ રહ્યું છે…'],
  ['Every answer will come from something {name} really said or wrote, with the source attached. Keep adding their words whenever you find more.', 'हर जवाब {name} की सच में कही या लिखी किसी बात से आएगा, स्रोत के साथ। जब भी और मिलें, उनके शब्द जोड़ते रहें।', 'દરેક જવાબ {name} એ ખરેખર કહેલી કે લખેલી કોઈ વાતમાંથી આવશે, સ્રોત સાથે. જ્યારે પણ વધુ મળે, તેમના શબ્દો ઉમેરતા રહો.'],
  ['Everything is in place', 'सब कुछ तैयार है', 'બધું તૈયાર છે'],
  ['Exit', 'बाहर निकलें', 'બહાર નીકળો'],
  ['Files', 'फ़ाइलें', 'ફાઇલો'],
  ['Files (theirs / others’)', 'फ़ाइलें (उनकी / दूसरों की)', 'ફાઇલો (તેમની / બીજાની)'],
  ['Follow-ups worth asking next', 'आगे पूछने लायक़ सवाल', 'આગળ પૂછવા જેવા પ્રશ્નો'],
  ['For someone who has died. Built with the family’s agreement, with gentler framing.', 'उनके लिए जो अब नहीं रहे। परिवार की सहमति से, नरम लहजे के साथ बना।', 'તેમના માટે જે હવે નથી રહ્યા. પરિવારની સંમતિથી, નરમ લહેકા સાથે બનેલું.'],
  ['Gather|their words.', 'उनके शब्द|इकट्ठा करें।', 'તેમના શબ્દો|ભેગા કરો.'],
  ['Preserve|someone', 'किसी को|सहेजें', 'કોઈને|સાચવો'],
  ['Gathering their memories', 'उनकी यादें इकट्ठा हो रही हैं', 'તેમની યાદો ભેગી થઈ રહી છે'],
  ['Go to {id}', '{id} पर जाएँ', '{id} પર જાઓ'],
  ['Hear a line in their voice', 'उनकी आवाज़ में एक पंक्ति सुनें', 'તેમના અવાજમાં એક લીટી સાંભળો'],
  ['Home', 'होम', 'હોમ'],
  ['I am answering as myself', 'मैं ख़ुद के रूप में जवाब दे रहा/रही हूँ', 'હું પોતે તરીકે જવાબ આપું છું'],
  ['I understand it answers only from what they really said, and says “I don’t know” otherwise.', 'मैं समझता/समझती हूँ कि यह सिर्फ़ उनकी सच में कही बातों से जवाब देता है, वरना कहता है “मुझे नहीं पता”।', 'હું સમજું છું કે તે ફક્ત તેમણે ખરેખર કહેલી વાતોમાંથી જવાબ આપે છે, નહીંતર કહે છે “મને ખબર નથી”.'],
  ['If they are with you, ask them to read', 'अगर वे आपके साथ हैं, तो उनसे यह पढ़ने को कहें', 'જો તેઓ તમારી સાથે હોય, તો તેમને આ વાંચવા કહો'],
  ['Import', 'इम्पोर्ट करें', 'ઇમ્પોર્ટ કરો'],
  ['Import a backup', 'बैकअप इम्पोर्ट करें', 'બેકઅપ ઇમ્પોર્ટ કરો'],
  ['In their own words…', 'उन्हीं के शब्दों में…', 'તેમના જ શબ્દોમાં…'],
  ['Insights and knowledge gaps', 'इनसाइट्स और जानकारी की कमियाँ', 'ઇનસાઇટ્સ અને જાણકારીની ખામીઓ'],
  ['Insights for {name}', '{name} के लिए इनसाइट्स', '{name} માટે ઇનસાઇટ્સ'],
  ['Interview dimensions', 'इंटरव्यू के पहलू', 'ઇન્ટરવ્યૂનાં પાસાં'],
  ['Labelling every memory by voice', 'हर याद पर लेबल कि शब्द किसके हैं', 'દરેક યાદ પર લેબલ કે શબ્દો કોના છે'],
  ['Letters, journals, notes and photos of handwritten pages. Label each batch by whose words it is: only their own words are ever quoted as theirs.', 'चिट्ठियाँ, डायरियाँ, नोट्स और हाथ से लिखे पन्नों की फ़ोटो। हर खेप पर लेबल लगाएँ कि शब्द किसके हैं: सिर्फ़ उनके अपने शब्द ही कभी उनके नाम से उद्धृत होते हैं।', 'પત્રો, ડાયરીઓ, નોંધો અને હાથે લખેલાં પાનાંના ફોટા. દરેક જથ્થા પર લેબલ લગાવો કે શબ્દો કોના છે: ફક્ત તેમના પોતાના શબ્દો જ ક્યારેય તેમના નામે ટાંકવામાં આવે છે.'],
  ['Letters, journals, notes, photos of handwritten pages and voice notes. Label each batch by whose words it is: only their own words are ever quoted as theirs.', 'चिट्ठियाँ, डायरियाँ, नोट्स, हाथ से लिखे पन्नों की फ़ोटो और वॉइस नोट्स। हर खेप पर लेबल लगाएँ कि शब्द किसके हैं: सिर्फ़ उनके अपने शब्द ही कभी उनके नाम से उद्धृत होते हैं।', 'પત્રો, ડાયરીઓ, નોંધો, હાથે લખેલાં પાનાંના ફોટા અને વૉઇસ નોટ્સ. દરેક જથ્થા પર લેબલ લગાવો કે શબ્દો કોના છે: ફક્ત તેમના પોતાના શબ્દો જ ક્યારેય તેમના નામે ટાંકવામાં આવે છે.'],
  ['Live preview', 'लाइव झलक', 'લાઇવ ઝલક'],
  ['Living, with consent', 'जीवित, सहमति के साथ', 'જીવિત, સંમતિ સાથે'],
  ['Loading the consent statement…', 'सहमति का वक्तव्य लोड हो रहा है…', 'સંમતિનું નિવેદન લોડ થઈ રહ્યું છે…'],
  ['Loading the questions…', 'सवाल लोड हो रहे हैं…', 'પ્રશ્નો લોડ થઈ રહ્યા છે…'],
  ['Making their voice…', 'उनकी आवाज़ बन रही है…', 'તેમનો અવાજ બની રહ્યો છે…'],
  ['Manage', 'प्रबंधन', 'વ્યવસ્થાપન'],
  ['Memorial', 'स्मृति', 'સ્મૃતિ'],
  ['Microphone access was blocked. Allow it in your browser settings.', 'माइक्रोफ़ोन की अनुमति रोकी गई है। इसे अपनी ब्राउज़र सेटिंग्स में चालू करें।', 'માઇક્રોફોનની પરવાનગી રોકાઈ છે. તેને તમારા બ્રાઉઝર સેટિંગ્સમાં ચાલુ કરો.'],
  ['Mode', 'मोड', 'મોડ'],
  ['New', 'नया', 'નવું'],
  ['Next question', 'अगला सवाल', 'આગળનો પ્રશ્ન'],
  ['Next: add some of their own words', 'अगला: उनके कुछ अपने शब्द जोड़ें', 'આગળ: તેમના થોડા પોતાના શબ્દો ઉમેરો'],
  ['Next: answer more interview questions ({n} of 25)', 'अगला: इंटरव्यू के और सवालों के जवाब दें (25 में से {n})', 'આગળ: ઇન્ટરવ્યૂના વધુ પ્રશ્નોના જવાબ આપો (25 માંથી {n})'],
  ['Next: build the model', 'अगला: मॉडल बनाएँ', 'આગળ: મોડેલ બનાવો'],
  ['Next: {n} more memories before it can be built', 'अगला: बनाने से पहले {n} और यादें', 'આગળ: બનાવતા પહેલા {n} વધુ યાદો'],
  ['No one preserved yet.', 'अभी तक कोई सहेजा नहीं गया।', 'હજી સુધી કોઈ સચવાયું નથી.'],
  ['Nobody can chat with {name} until consent is renewed.', 'सहमति के नवीनीकरण तक कोई {name} से बात नहीं कर सकता।', 'સંમતિના નવીનીકરણ સુધી કોઈ {name} સાથે વાત કરી શકે નહીં.'],
  ['Nobody can chat with {name} until it is resumed.', 'फिर से शुरू होने तक कोई {name} से बात नहीं कर सकता।', 'ફરી શરૂ થાય ત્યાં સુધી કોઈ {name} સાથે વાત કરી શકે નહીં.'],
  ['None yet', 'अभी कोई नहीं', 'હજી કોઈ નહીં'],
  ['Not yet', 'अभी नहीं', 'હજી નહીં'],
  ['Off-limits topics saved', 'वर्जित विषय सहेजे गए', 'વર્જિત વિષયો સાચવ્યા'],
  ['Off-limits topics, comma-separated. Questions about them are refused, and memories that mention them are never quoted.', 'वर्जित विषय, कॉमा से अलग करें। इनके बारे में सवालों से इनकार किया जाता है, और जिन यादों में इनका ज़िक्र हो, वे कभी उद्धृत नहीं होतीं।', 'વર્જિત વિષયો, અલ્પવિરામથી અલગ કરો. તેમના વિશેના પ્રશ્નોનો ઇનકાર થાય છે, અને જે યાદોમાં તેમનો ઉલ્લેખ હોય, તે ક્યારેય ટાંકવામાં આવતી નથી.'],
  ['Optional: add their cloned voice', 'वैकल्पिक: उनकी क्लोन आवाज़ जोड़ें', 'વૈકલ્પિક: તેમનો ક્લોન અવાજ ઉમેરો'],
  ['Password (8+ characters)', 'पासवर्ड (8+ अक्षर)', 'પાસવર્ડ (8+ અક્ષર)'],
  ['Pause', 'रोकें', 'રોકો'],
  ['Paused', 'रुका हुआ', 'રોકાયેલું'],
  ['Paused: resume it on its page to talk again', 'रुका हुआ: फिर बात करने के लिए इसके पेज पर दोबारा शुरू करें', 'રોકાયેલું: ફરી વાત કરવા તેના પેજ પર ફરી શરૂ કરો'],
  ['Play', 'चलाएँ', 'વગાડો'],
  ['Preserve someone new', 'किसी नए को सहेजें', 'કોઈ નવાને સાચવો'],
  ['Preserve the people', 'उन लोगों को सहेजें', 'એ લોકોને સાચવો'],
  ['Preserve {name}', '{name} को सहेजें', '{name} ને સાચવો'],
  ['Preserving', 'सहेज रहे हैं:', 'સાચવી રહ્યા છીએ:'],
  ['Preserving…', 'सहेजा जा रहा है…', 'સચવાઈ રહ્યું છે…'],
  ['Previous', 'पिछला', 'પાછલું'],
  ['Private', 'निजी', 'ખાનગી'],
  ['Private · consent first', 'निजी · पहले सहमति', 'ખાનગી · પહેલા સંમતિ'],
  ['Q&A log', 'सवाल-जवाब लॉग', 'પ્રશ્ન-જવાબ લૉગ'],
  ['Question {n} of 25', 'सवाल {n} / 25', 'પ્રશ્ન {n} / 25'],
  ['Reading {file}…', '{file} पढ़ा जा रहा है…', '{file} વંચાઈ રહી છે…'],
  ['Ready to preserve', 'सहेजने के लिए तैयार', 'સાચવવા માટે તૈયાર'],
  ['Ready to record', 'रिकॉर्ड करने के लिए तैयार', 'રેકોર્ડ કરવા માટે તૈયાર'],
  ['Ready to talk', 'बात करने के लिए तैयार', 'વાત કરવા માટે તૈયાર'],
  ['Rebuild with new memories', 'नई यादों के साथ फिर से बनाएँ', 'નવી યાદો સાથે ફરી બનાવો'],
  ['Rebuilding…', 'फिर से बन रहा है…', 'ફરી બની રહ્યું છે…'],
  ['Record', 'रिकॉर्ड करें', 'રેકોર્ડ કરો'],
  ['Recorded', 'रिकॉर्ड हो गया', 'રેકોર્ડ થયું'],
  ['Recording consent…', 'सहमति दर्ज हो रही है…', 'સંમતિ નોંધાઈ રહી છે…'],
  ['Recording · {s} s of {max}', 'रिकॉर्डिंग · {s} / {max} सेकंड', 'રેકોર્ડિંગ · {s} / {max} સેકન્ડ'],
  ['Remove their voice', 'उनकी आवाज़ हटाएँ', 'તેમનો અવાજ દૂર કરો'],
  ['Remove {file}', '{file} हटाएँ', '{file} દૂર કરો'],
  ['Removing…', 'हटाया जा रहा है…', 'દૂર થઈ રહ્યું છે…'],
  ['Renew for a year', 'एक साल के लिए नवीनीकरण करें', 'એક વર્ષ માટે નવીનીકરણ કરો'],
  ['Repeat it', 'दोबारा लिखें', 'ફરી લખો'],
  ['Repeat the password', 'पासवर्ड दोबारा लिखें', 'પાસવર્ડ ફરી લખો'],
  ['Resume', 'फिर से शुरू करें', 'ફરી શરૂ કરો'],
  ['Review and build', 'जाँचें और बनाएँ', 'તપાસો અને બનાવો'],
  ['Review was due {date}', 'समीक्षा {date} को होनी थी', 'સમીક્ષા {date} એ થવાની હતી'],
  ['Revoke consent', 'सहमति वापस लें', 'સંમતિ પાછી ખેંચો'],
  ['Revoke consent for {name}? This deletes the model and everything in it: memories, documents, interview answers and voice. It cannot be undone.', '{name} के लिए सहमति वापस लें? इससे मॉडल और उसमें मौजूद सब कुछ मिट जाएगा: यादें, दस्तावेज़, इंटरव्यू जवाब और आवाज़। इसे पलटा नहीं जा सकता।', '{name} માટે સંમતિ પાછી ખેંચવી છે? આનાથી મોડેલ અને તેમાંનું બધું ભૂંસાઈ જશે: યાદો, દસ્તાવેજો, ઇન્ટરવ્યૂ જવાબ અને અવાજ. આ પાછું વાળી શકાતું નથી.'],
  ['Sample personality map · it fills in as you answer the interview', 'नमूना व्यक्तित्व नक़्शा · इंटरव्यू के जवाबों के साथ भरता है', 'નમૂના વ્યક્તિત્વ નકશો · ઇન્ટરવ્યૂના જવાબો સાથે ભરાય છે'],
  ['Save', 'सहेजें', 'સાચવો'],
  ['Save answer', 'जवाब सहेजें', 'જવાબ સાચવો'],
  ['Save topics', 'विषय सहेजें', 'વિષયો સાચવો'],
  ['Saved', 'सहेजा गया', 'સાચવ્યું'],
  ['Saved as their own words', 'उनके अपने शब्दों के रूप में सहेजा गया', 'તેમના પોતાના શબ્દો તરીકે સાચવ્યું'],
  ['Saved as written by others', 'दूसरों के लिखे के रूप में सहेजा गया', 'બીજાએ લખેલા તરીકે સાચવ્યું'],
  ['Saving…', 'सहेजा जा रहा है…', 'સચવાઈ રહ્યું છે…'],
  ['Self', 'स्वयं', 'સ્વયં'],
  ['Skip to the interview', 'सीधे इंटरव्यू पर जाएँ', 'સીધા ઇન્ટરવ્યૂ પર જાઓ'],
  ['Speak the answer', 'जवाब बोलें', 'જવાબ બોલો'],
  ['Speaking…', 'बोल रहा है…', 'બોલી રહ્યું છે…'],
  ['Start recording', 'रिकॉर्डिंग शुरू करें', 'રેકોર્ડિંગ શરૂ કરો'],
  ['Start the interview', 'इंटरव्यू शुरू करें', 'ઇન્ટરવ્યૂ શરૂ કરો'],
  ['Start with a parent, a grandparent, a mentor, or yourself. It takes a few steps, and you can keep adding their words at any time.', 'माता-पिता, दादा-दादी, किसी गुरु या ख़ुद से शुरू करें। इसमें कुछ क़दम लगते हैं, और आप कभी भी उनके शब्द जोड़ते रह सकते हैं।', 'માતા-પિતા, દાદા-દાદી, કોઈ ગુરુ કે પોતાનાથી શરૂ કરો. તેમાં થોડાં પગલાં લાગે છે, અને તમે ગમે ત્યારે તેમના શબ્દો ઉમેરતા રહી શકો છો.'],
  ['Start with consent', 'सहमति से शुरू करें', 'સંમતિથી શરૂ કરો'],
  ['Starts with consent', 'सहमति से शुरू होता है', 'સંમતિથી શરૂ થાય છે'],
  ['Step {n} of 6', 'क़दम {n} / 6', 'પગલું {n} / 6'],
  ['Steps', 'क़दम', 'પગલાં'],
  ['Stop', 'रोकें', 'રોકો'],
  ['Stop recording', 'रिकॉर्डिंग रोकें', 'રેકોર્ડિંગ રોકો'],
  ['That recording is only {s} seconds. Record at least 10 seconds of them speaking.', 'यह रिकॉर्डिंग सिर्फ़ {s} सेकंड की है। उनके बोलने के कम से कम 10 सेकंड रिकॉर्ड करें।', 'આ રેકોર્ડિંગ ફક્ત {s} સેકન્ડનું છે. તેમના બોલવાની ઓછામાં ઓછી 10 સેકન્ડ રેકોર્ડ કરો.'],
  ['The', 'निर्देशित', 'માર્ગદર્શિત'],
  ['The passwords don’t match.', 'पासवर्ड मेल नहीं खाते।', 'પાસવર્ડ મેળ ખાતા નથી.'],
  ['The people you’ve preserved.', 'वे लोग जिन्हें आपने सहेजा है।', 'એ લોકો જેમને તમે સાચવ્યા છે.'],
  ['The person who gave consent, or their family, can pause {name}, renew consent each year, keep topics private, or revoke it, which deletes everything.', 'सहमति देने वाला व्यक्ति, या उनका परिवार, {name} को रोक सकता है, हर साल सहमति नवीनीकृत कर सकता है, विषय निजी रख सकता है, या सहमति वापस ले सकता है, जिससे सब कुछ मिट जाता है।', 'સંમતિ આપનાર વ્યક્તિ, અથવા તેમનો પરિવાર, {name} ને રોકી શકે, દર વર્ષે સંમતિ નવીનીકૃત કરી શકે, વિષયો ખાનગી રાખી શકે, અથવા સંમતિ પાછી ખેંચી શકે, જેનાથી બધું ભૂંસાઈ જાય છે.'],
  ['The recording is sent to Fish Audio to make the voice.', 'आवाज़ बनाने के लिए रिकॉर्डिंग Fish Audio को भेजी जाती है।', 'અવાજ બનાવવા રેકોર્ડિંગ Fish Audio ને મોકલાય છે.'],
  ['The shape fills in as you answer. Each point is one part of who they are.', 'जवाबों के साथ यह आकार भरता है। हर बिंदु उनकी शख़्सियत का एक हिस्सा है।', 'જવાબો સાથે આ આકાર ભરાય છે. દરેક બિંદુ તેમના વ્યક્તિત્વનો એક ભાગ છે.'],
  ['Their answer', 'उनका जवाब', 'તેમનો જવાબ'],
  ['Their name', 'उनका नाम', 'તેમનું નામ'],
  ['Their name, or what you call them', 'उनका नाम, या आप उन्हें क्या बुलाते हैं', 'તેમનું નામ, અથવા તમે તેમને શું કહો છો'],
  ['Their voice is ready', 'उनकी आवाज़ तैयार है', 'તેમનો અવાજ તૈયાર છે'],
  ['Their voice was deleted here and at Fish Audio', 'उनकी आवाज़ यहाँ और Fish Audio पर मिटा दी गई', 'તેમનો અવાજ અહીં અને Fish Audio પર ભૂંસી નાખ્યો'],
  ['This person, or their estate, agreed to their voice being used for this model.', 'इस व्यक्ति, या उनके वारिसों ने, इस मॉडल के लिए उनकी आवाज़ के इस्तेमाल की सहमति दी है।', 'આ વ્યક્તિએ, અથવા તેમના વારસદારોએ, આ મોડેલ માટે તેમના અવાજના ઉપયોગની સંમતિ આપી છે.'],
  ['This removes everything the model was made of, here and at Fish Audio. It can’t be undone.', 'इससे वह सब हट जाएगा जिससे मॉडल बना था, यहाँ और Fish Audio पर। इसे पलटा नहीं जा सकता।', 'આનાથી મોડેલ જેમાંથી બન્યું હતું તે બધું દૂર થશે, અહીં અને Fish Audio પર. આ પાછું વાળી શકાતું નથી.'],
  ['To keep one memory but never quote it, use “Never quote” in', 'किसी याद को रखना पर कभी उद्धृत न करना हो, तो “कभी उद्धृत न करें” इस्तेमाल करें, यहाँ:', 'કોઈ યાદ રાખવી પણ ક્યારેય ટાંકવી ન હોય, તો “ક્યારેય ન ટાંકો” વાપરો, અહીં:'],
  ['Transcribed on this computer', 'इसी कंप्यूटर पर लिखित में बदला', 'આ જ કમ્પ્યુટર પર લેખિતમાં ફેરવ્યું'],
  ['Transcribing…', 'लिखित में बदला जा रहा है…', 'લેખિતમાં ફેરવાઈ રહ્યું છે…'],
  ['Try a pretrained model first', 'पहले कोई तैयार मॉडल आज़माएँ', 'પહેલા કોઈ તૈયાર મોડેલ અજમાવો'],
  ['Try again', 'फिर कोशिश करें', 'ફરી પ્રયાસ કરો'],
  ['Type a new answer to replace the saved one', 'सहेजे गए जवाब की जगह नया जवाब लिखें', 'સાચવેલા જવાબની જગ્યાએ નવો જવાબ લખો'],
  ['Type {name} to confirm', 'पुष्टि के लिए {name} लिखें', 'ખાતરી માટે {name} લખો'],
  ['Uploading', 'अपलोड हो रहा है', 'અપલોડ થઈ રહ્યું છે'],
  ['Uses your browser’s speech recognition', 'आपके ब्राउज़र की वाक् पहचान इस्तेमाल करता है', 'તમારા બ્રાઉઝરની વાણી ઓળખ વાપરે છે'],
  ['Voice added', 'आवाज़ जोड़ी गई', 'અવાજ ઉમેર્યો'],
  ['Voice cloning isn’t set up on this server. Add', 'इस सर्वर पर वॉइस क्लोनिंग सेट नहीं है।', 'આ સર્વર પર વૉઇસ ક્લોનિંગ સેટ નથી.'],
  ['Voice consent.', 'आवाज़ की सहमति।', 'અવાજની સંમતિ.'],
  ['What would they say? Use their words where you remember them.', 'वे क्या कहते? जहाँ याद हो, उनके शब्द इस्तेमाल करें।', 'તેઓ શું કહેત? જ્યાં યાદ હોય, ત્યાં તેમના શબ્દો વાપરો.'],
  ['Who', 'कौन', 'કોણ'],
  ['Who are you', 'आप किसे', 'તમે કોને'],
  ['Who is answering', 'कौन जवाब दे रहा है', 'કોણ જવાબ આપે છે'],
  ['Who they are to you', 'वे आपके क्या लगते हैं', 'તેઓ તમારા શું થાય'],
  ['Who will you preserve first?', 'सबसे पहले आप किसे सहेजेंगे?', 'સૌથી પહેલા તમે કોને સાચવશો?'],
  ['Whose words are these files', 'ये फ़ाइलें किसके शब्द हैं', 'આ ફાઇલો કોના શબ્દો છે'],
  ['With consent, 10 to 60 seconds of {name} speaking becomes a private cloned voice, so answers can be heard the way they talk. Voice is biometric data: removing it deletes it everywhere.', 'सहमति के साथ, {name} के बोलने के 10 से 60 सेकंड एक निजी क्लोन आवाज़ बनते हैं, ताकि जवाब वैसे सुनाई दें जैसे वे बोलते हैं। आवाज़ बायोमेट्रिक डेटा है: हटाने पर यह हर जगह से मिट जाती है।', 'સંમતિ સાથે, {name} ના બોલવાની 10 થી 60 સેકન્ડ ખાનગી ક્લોન અવાજ બને છે, જેથી જવાબ એ રીતે સંભળાય જે રીતે તેઓ બોલે છે. અવાજ બાયોમેટ્રિક ડેટા છે: દૂર કરતાં તે બધે જ ભૂંસાઈ જાય છે.'],
  ['Working…', 'काम चल रहा है…', 'કામ ચાલુ છે…'],
  ['Written by someone else', 'किसी और का लिखा', 'બીજા કોઈએ લખેલું'],
  ['You are preserving yourself. You choose what goes in, and you can delete it at any time.', 'आप ख़ुद को सहेज रहे हैं। इसमें क्या जाएगा, आप चुनते हैं, और इसे कभी भी मिटा सकते हैं।', 'તમે પોતાને સાચવી રહ્યા છો. તેમાં શું જશે તે તમે પસંદ કરો છો, અને તેને ગમે ત્યારે ભૂંસી શકો છો.'],
  ['You can play it once the model is built.', 'मॉडल बनने के बाद आप इसे चला सकते हैं।', 'મોડેલ બન્યા પછી તમે તેને વગાડી શકો છો.'],
  ['You can skip this', 'आप इसे छोड़ सकते हैं', 'તમે આ છોડી શકો છો'],
  ['a year after consent', 'सहमति के एक साल बाद', 'સંમતિના એક વર્ષ પછી'],
  ['and restart it.', 'में जोड़ें और सर्वर फिर से चालू करें।', 'માં ઉમેરો અને સર્વર ફરી ચાલુ કરો.'],
  ['comes first.', 'सबसे पहले।', 'સૌથી પહેલા.'],
  ['e.g. My grandmother, a teacher for thirty years', 'जैसे, मेरी दादी, तीस साल शिक्षिका रहीं', 'જેમ કે, મારાં દાદી, ત્રીસ વર્ષ શિક્ષિકા રહ્યાં'],
  ['e.g. divorce, the hospital', 'जैसे, तलाक़, अस्पताल', 'જેમ કે, છૂટાછેડા, હોસ્પિટલ'],
  ['interview.', 'इंटरव्यू।', 'ઇન્ટરવ્યૂ.'],
  ['of {n} memories needed', 'ज़रूरी {n} यादों में से', 'જરૂરી {n} યાદોમાંથી'],
  ['optional', 'वैकल्पिक', 'વૈકલ્પિક'],
  ['or upload a recording', 'या रिकॉर्डिंग अपलोड करें', 'અથવા રેકોર્ડિંગ અપલોડ કરો'],
  ['preserving?', 'सहेज रहे हैं?', 'સાચવી રહ્યા છો?'],
  ['since {date}', '{date} से', '{date} થી'],
  ['them', 'इस व्यक्ति', 'આ વ્યક્તિ'],
  ['to', 'को', 'ને'],
  ['transcribed', 'लिखित में बदला', 'લેખિતમાં ફેરવ્યું'],
  ['up to {mb} MB each', 'हर एक {mb} MB तक', 'દરેક {mb} MB સુધી'],
  ['who made you.', 'जिन्होंने आपको बनाया।', 'જેમણે તમને ઘડ્યા.'],
  ['{file} and its memories were removed', '{file} और उसकी यादें हटा दी गईं', '{file} અને તેની યાદો દૂર કરી'],
  ['{file}: CHRONUS can’t read {ext} files', '{file}: CHRONUS {ext} फ़ाइलें नहीं पढ़ सकता', '{file}: CHRONUS {ext} ફાઇલો વાંચી શકતું નથી'],
  ['{file}: larger than {mb} MB', '{file}: {mb} MB से बड़ी', '{file}: {mb} MB થી મોટી'],
  ['{file}: voice notes need local transcription (faster-whisper) on the server', '{file}: वॉइस नोट्स के लिए सर्वर पर लोकल ट्रांसक्रिप्शन (faster-whisper) चाहिए', '{file}: વૉઇસ નોટ્સ માટે સર્વર પર લોકલ ટ્રાન્સક્રિપ્શન (faster-whisper) જોઈએ'],
  ['{file}: {n} memories added', '{file}: {n} यादें जोड़ी गईं', '{file}: {n} યાદો ઉમેરાઈ'],
  ['{name} has died. Build this only as their next of kin or with the family’s agreement.', '{name} का निधन हो चुका है। इसे सिर्फ़ उनके निकट संबंधी के रूप में या परिवार की सहमति से बनाएँ।', '{name} નું અવસાન થયું છે. આ ફક્ત તેમના નજીકના સગા તરીકે અથવા પરિવારની સંમતિથી બનાવો.'],
  ['{name} is|preserved.', '{name} का व्यक्तित्व|सहेज लिया गया।', '{name} નું વ્યક્તિત્વ|સચવાઈ ગયું.'],
  ['{name} is a pretrained model; it can’t be edited here.', '{name} पहले से तैयार मॉडल है; इसे यहाँ बदला नहीं जा सकता।', '{name} પહેલેથી તૈયાર મોડેલ છે; તેને અહીં બદલી શકાતું નથી.'],
  ['{name} is active again', '{name} फिर से सक्रिय है', '{name} ફરી સક્રિય છે'],
  ['{name} is answering', '{name} जवाब दे रहे हैं', '{name} જવાબ આપે છે'],
  ['{name} is paused', '{name} रुका हुआ है', '{name} રોકાયેલું છે'],
  ['{name} should know what CHRONUS does, what it will be built from, and that they can ask for it to be deleted at any time.', '{name} को पता होना चाहिए कि CHRONUS क्या करता है, यह किन चीज़ों से बनेगा, और वे कभी भी इसे मिटाने के लिए कह सकते हैं।', '{name} ને ખબર હોવી જોઈએ કે CHRONUS શું કરે છે, તે શેમાંથી બનશે, અને તેઓ ગમે ત્યારે તેને ભૂંસવા કહી શકે છે.'],
  ['{name} was deleted: memories, files, voice, log entries and feedback.', '{name} को मिटा दिया गया: यादें, फ़ाइलें, आवाज़, लॉग प्रविष्टियाँ और फ़ीडबैक।', '{name} ને ભૂંસી નાખ્યું: યાદો, ફાઇલો, અવાજ, લૉગ નોંધો અને પ્રતિસાદ.'],
  ['{name} was imported.', '{name} इम्पोर्ट हो गया।', '{name} ઇમ્પોર્ટ થયું.'],
  ['{name}’s own words', '{name} के अपने शब्द', '{name} ના પોતાના શબ્દો'],
  ['{name}’s personality map · {n} of 25 answered', '{name} का व्यक्तित्व नक़्शा · 25 में से {n} के जवाब', '{name} નો વ્યક્તિત્વ નકશો · 25 માંથી {n} ના જવાબ'],
  ['{name}’s voice is ready', '{name} की आवाज़ तैयार है', '{name} નો અવાજ તૈયાર છે'],
  ['{n} already known', '{n} पहले से पता', '{n} પહેલેથી જાણીતા'],
  ['{n} follow-ups', '{n} अगले सवाल', '{n} આગળના પ્રશ્નો'],
  ['{n} memories', '{n} यादें', '{n} યાદો'],
  ['{n} memories so far', 'अब तक {n} यादें', 'અત્યાર સુધી {n} યાદો'],
  ['{n} of 25', '25 में से {n}', '25 માંથી {n}'],
  ['{n} of 25 answered', '25 में से {n} के जवाब', '25 માંથી {n} ના જવાબ'],
  ['{s} s sample', '{s} सेकंड का नमूना', '{s} સેકન્ડનો નમૂનો'],
]
