// [English, हिन्दी, ગુજરાતી]: the home page
export const HOME = [
  ['01 — Preserve someone', '01 — किसी को सहेजें', '01 — કોઈને સાચવો'],
  ['02 — From memories to a conversation', '02 — यादों से बातचीत तक', '02 — યાદોથી વાતચીત સુધી'],
  ['03 — Two ways to hear them', '03 — उन्हें सुनने के दो तरीक़े', '03 — તેમને સાંભળવાની બે રીત'],
  ['04 — How an answer is made', '04 — जवाब कैसे बनता है', '04 — જવાબ કેવી રીતે બને છે'],
  ['05 — Memory field', '05 — यादों का मैदान', '05 — યાદોનું ક્ષેત્ર'],
  ['06 — Around the conversation', '06 — बातचीत के आसपास', '06 — વાતચીતની આસપાસ'],
  ['07 — Consent first', '07 — पहले सहमति', '07 — પહેલા સંમતિ'],
  ['08 — Also included', '08 — यह भी शामिल है', '08 — આ પણ સામેલ છે'],
  ['09 — Questions', '09 — सवाल', '09 — પ્રશ્નો'],
  ['1 memory inside θ', 'θ के अंदर 1 याद', 'θ ની અંદર 1 યાદ'],
  ['1 source', '1 स्रोत', '1 સ્રોત'],
  ['12 pages', '12 पेज', '12 પાનાં'],
  ['25 guided questions with adaptive follow-ups fill in what the documents miss.', 'जो दस्तावेज़ों में छूट जाता है, उसे 25 निर्देशित सवाल और उनके हिसाब से बदलते अगले सवाल भर देते हैं।', 'દસ્તાવેજોમાં જે રહી જાય છે, તે 25 માર્ગદર્શિત પ્રશ્નો અને તે મુજબ બદલાતા આગળના પ્રશ્નો પૂરું કરે છે.'],
  ['25 questions across six dimensions, with follow-ups that dig into what the documents miss.', 'छह पहलुओं में 25 सवाल, और अगले सवाल जो वहाँ तक जाते हैं जहाँ दस्तावेज़ नहीं पहुँचते।', 'છ પાસાંમાં 25 પ્રશ્નો, અને આગળના પ્રશ્નો જે ત્યાં સુધી જાય છે જ્યાં દસ્તાવેજો નથી પહોંચતા.'],
  ['6 dimensions · 25 questions · 1 person', '6 पहलू · 25 सवाल · 1 व्यक्ति', '6 પાસાં · 25 પ્રશ્નો · 1 વ્યક્તિ'],
  ['A biography, or a family member’s interview answer. Used, labelled, never quoted as theirs.', 'कोई जीवनी, या परिवार के किसी सदस्य का इंटरव्यू जवाब। इस्तेमाल होता है, लेबल होता है, पर कभी उनके शब्दों के रूप में नहीं दिखाया जाता।', 'કોઈ જીવનચરિત્ર, અથવા પરિવારના કોઈ સભ્યનો ઇન્ટરવ્યૂ જવાબ. વપરાય છે, લેબલ થાય છે, પણ ક્યારેય તેમના શબ્દો તરીકે બતાવાતું નથી.'],
  ['A consented recording becomes their cloned voice. Removing it deletes it everywhere.', 'सहमति से की गई रिकॉर्डिंग उनकी क्लोन की गई आवाज़ बनती है। हटाने पर यह हर जगह से मिट जाती है।', 'સંમતિથી કરેલું રેકોર્ડિંગ તેમનો ક્લોન કરેલો અવાજ બને છે. દૂર કરતાં તે બધે જ ભૂંસાઈ જાય છે.'],
  ['A guided interview across six dimensions, with adaptive follow-ups, maps how they think, what they value and how they talk.', 'छह पहलुओं वाला निर्देशित इंटरव्यू, बदलते अगले सवालों के साथ, यह समझता है कि वे कैसे सोचते हैं, किसे अहमियत देते हैं और कैसे बोलते हैं।', 'છ પાસાંવાળો માર્ગદર્શિત ઇન્ટરવ્યૂ, બદલાતા આગળના પ્રશ્નો સાથે, સમજે છે કે તેઓ કેવી રીતે વિચારે છે, શેને મહત્ત્વ આપે છે અને કેવી રીતે બોલે છે.'],
  ['A map of one person’s memories. The pointer is a question; the nearest memories inside the threshold light up.', 'एक व्यक्ति की यादों का नक़्शा। पॉइंटर एक सवाल है; सीमा के अंदर की सबसे पास की यादें चमक उठती हैं।', 'એક વ્યક્તિની યાદોનો નકશો. પોઇન્ટર એક પ્રશ્ન છે; મર્યાદાની અંદરની સૌથી નજીકની યાદો ઝળકી ઊઠે છે.'],
  ['A person is not a dataset.', 'इंसान कोई डेटासेट नहीं है।', 'માણસ કોઈ ડેટાસેટ નથી.'],
  ['AI voice', 'AI आवाज़', 'AI અવાજ'],
  ['Active', 'सक्रिय', 'સક્રિય'],
  ['All of this is part of CHRONUS today. The controls here work.', 'यह सब आज CHRONUS का हिस्सा है। यहाँ के कंट्रोल सच में काम करते हैं।', 'આ બધું આજે CHRONUS નો ભાગ છે. અહીંનાં કંટ્રોલ ખરેખર કામ કરે છે.'],
  ['An answer you reviewed and approved. Marked as such wherever it appears.', 'ऐसा जवाब जिसे आपने जाँचकर मंज़ूर किया। जहाँ भी दिखे, उस पर यही निशान रहता है।', 'એવો જવાબ જે તમે તપાસીને મંજૂર કર્યો. જ્યાં પણ દેખાય, તેના પર આ નિશાન રહે છે.'],
  ['An optional cloned voice, then the build: it runs on your machine.', 'चाहें तो क्लोन की गई आवाज़, फिर मॉडल बनाना: यह आपके कंप्यूटर पर चलता है।', 'ઇચ્છો તો ક્લોન કરેલો અવાજ, પછી મોડેલ બનાવવું: તે તમારા કમ્પ્યુટર પર ચાલે છે.'],
  ['Answer', 'जवाब', 'જવાબ'],
  ['Ask', 'पूछें', 'પૂછો'],
  ['Ask aloud. Hear them answer.', 'बोलकर पूछें। उन्हें जवाब देते सुनें।', 'બોલીને પૂછો. તેમને જવાબ આપતા સાંભળો.'],
  ['Ask anything. Every answer cites the memory it came from, and an empty archive says “I don’t know”.', 'कुछ भी पूछें। हर जवाब उस याद का हवाला देता है जिससे वह आया, और ख़ाली संग्रह कहता है “मुझे नहीं पता”।', 'કંઈ પણ પૂછો. દરેક જવાબ જે યાદમાંથી આવ્યો તેનો હવાલો આપે છે, અને ખાલી સંગ્રહ કહે છે “મને ખબર નથી”.'],
  ['Ask in Hindi, Gujarati and more.', 'हिन्दी, गुजराती और दूसरी भाषाओं में पूछें।', 'હિન્દી, ગુજરાતી અને બીજી ભાષાઓમાં પૂછો.'],
  ['Asked in Hindi, Gujarati or another language? It is translated to English, answered, and translated back, with the English original shown.', 'हिन्दी, गुजराती या किसी और भाषा में पूछा? सवाल का अंग्रेज़ी में अनुवाद होता है, जवाब बनता है, फिर वापस अनुवाद होता है, और अंग्रेज़ी मूल भी दिखता है।', 'હિન્દી, ગુજરાતી કે બીજી કોઈ ભાષામાં પૂછ્યું? પ્રશ્નનો અંગ્રેજીમાં અનુવાદ થાય છે, જવાબ બને છે, પછી પાછો અનુવાદ થાય છે, અને અંગ્રેજી મૂળ પણ દેખાય છે.'],
  ['Begin', 'शुरू करें', 'શરૂ કરો'],
  ['Breaks character on purpose', 'जान-बूझकर किरदार से बाहर आता है', 'જાણી જોઈને પાત્રમાંથી બહાર આવે છે'],
  ['Browse pretrained models', 'पहले से तैयार मॉडल देखें', 'પહેલેથી તૈયાર મોડેલ જુઓ'],
  ['Built with the family’s agreement, with gentler framing and break reminders for long conversations.', 'परिवार की सहमति से बना, नरम लहजे और लंबी बातचीत में आराम की याद दिलाने के साथ।', 'પરિવારની સંમતિથી બનેલું, નરમ લહેકા અને લાંબી વાતચીતમાં આરામની યાદ અપાવવા સાથે.'],
  ['By others', 'दूसरों का', 'બીજાનું'],
  ['CHRONUS in numbers', 'आँकड़ों में CHRONUS', 'આંકડામાં CHRONUS'],
  ['CHRONUS learns how someone thinks, speaks and remembers from their letters, journals, voice notes and a guided interview, with their consent. Then it answers as them and cites every memory it uses.', 'CHRONUS किसी की चिट्ठियों, डायरियों, वॉइस नोट्स और एक निर्देशित इंटरव्यू से, उनकी सहमति के साथ, सीखता है कि वे कैसे सोचते, बोलते और याद रखते हैं। फिर वह उन्हीं की तरह जवाब देता है और हर इस्तेमाल की गई याद का हवाला देता है।', 'CHRONUS કોઈના પત્રો, ડાયરીઓ, વૉઇસ નોટ્સ અને માર્ગદર્શિત ઇન્ટરવ્યૂમાંથી, તેમની સંમતિ સાથે, શીખે છે કે તેઓ કેવી રીતે વિચારે, બોલે અને યાદ રાખે છે. પછી તે તેમની જેમ જ જવાબ આપે છે અને વાપરેલી દરેક યાદનો હવાલો આપે છે.'],
  ['CHRONUS runs on your own machine and listens only on 127.0.0.1. Turn on accounts and each person sees only the models they created. Delete a model and its memories, files, cloned voice, logs and feedback all go with it.', 'CHRONUS आपके अपने कंप्यूटर पर चलता है और सिर्फ़ 127.0.0.1 पर सुनता है। अकाउंट चालू करें तो हर व्यक्ति सिर्फ़ अपने बनाए मॉडल देखता है। मॉडल मिटाएँ, तो उसकी यादें, फ़ाइलें, क्लोन आवाज़, लॉग और फ़ीडबैक सब साथ मिट जाते हैं।', 'CHRONUS તમારા પોતાના કમ્પ્યુટર પર ચાલે છે અને ફક્ત 127.0.0.1 પર સાંભળે છે. એકાઉન્ટ ચાલુ કરો તો દરેક વ્યક્તિ ફક્ત પોતે બનાવેલા મોડેલ જુએ છે. મોડેલ ભૂંસો, તો તેની યાદો, ફાઇલો, ક્લોન અવાજ, લૉગ અને પ્રતિસાદ બધું સાથે જ ભૂંસાઈ જાય છે.'],
  ['Can I preserve someone who has died?', 'क्या मैं किसी ऐसे व्यक्ति को सहेज सकता हूँ जो अब नहीं रहे?', 'શું હું એવી વ્યક્તિને સાચવી શકું જે હવે નથી રહ્યા?'],
  ['Can be quoted word for word when it answers the question.', 'सवाल का जवाब देता हो, तो शब्दशः उद्धृत किया जा सकता है।', 'પ્રશ્નનો જવાબ આપતું હોય, તો શબ્દશઃ ટાંકી શકાય છે.'],
  ['Childhood stories', 'बचपन की कहानियाँ', 'બાળપણની વાર્તાઓ'],
  ['Click any point to see what kind of memory it is.', 'कोई भी बिंदु क्लिक करें और देखें कि वह किस तरह की याद है।', 'કોઈ પણ બિંદુ ક્લિક કરો અને જુઓ કે તે કેવા પ્રકારની યાદ છે.'],
  ['Cloned voice at Fish Audio', 'Fish Audio पर क्लोन आवाज़', 'Fish Audio પર ક્લોન અવાજ'],
  ['Cloned with consent · delete any time', 'सहमति से क्लोन · कभी भी मिटाएँ', 'સંમતિથી ક્લોન · ગમે ત્યારે ભૂંસો'],
  ['Compare Quotes only (left) with AI voice (right)', 'सिर्फ़ उद्धरण (बाएँ) की तुलना AI आवाज़ (दाएँ) से करें', 'ફક્ત અવતરણ (ડાબે) ની સરખામણી AI અવાજ (જમણે) સાથે કરો'],
  ['Confidence · high', 'भरोसा · ऊँचा', 'ભરોસો · ઊંચો'],
  ['Connecting', 'जुड़ रहा है', 'જોડાઈ રહ્યું છે'],
  ['Consent', 'सहमति', 'સંમતિ'],
  ['Consent comes first.', 'सहमति सबसे पहले।', 'સંમતિ સૌથી પહેલા.'],
  ['Consent record', 'सहमति का रिकॉर्ड', 'સંમતિનો રેકોર્ડ'],
  ['Continue {name}', '{name} को आगे बढ़ाएँ', '{name} ને આગળ વધારો'],
  ['Crisis check', 'संकट जाँच', 'કટોકટી તપાસ'],
  ['Crisis language brings up helplines. Long sessions with a personal model get a gentle break reminder.', 'संकट वाली भाषा पर हेल्पलाइन दिखती हैं। निजी मॉडल के साथ लंबी बातचीत में आराम की हल्की याद दिलाई जाती है।', 'કટોકટીવાળી ભાષા પર હેલ્પલાઇન દેખાય છે. અંગત મોડેલ સાથે લાંબી વાતચીતમાં આરામની હળવી યાદ અપાય છે.'],
  ['Delete means delete', 'मिटाना यानी मिटाना', 'ભૂંસવું એટલે ભૂંસવું'],
  ['Deleting…', 'मिटाया जा रहा है…', 'ભૂંસાઈ રહ્યું છે…'],
  ['Drag', 'खींचें', 'ખેંચો'],
  ['Drag to compare.', 'तुलना के लिए खींचें।', 'સરખામણી માટે ખેંચો.'],
  ['Each step keeps it honest: grounded in their archive, labelled by whose words it is, and quiet when it should be.', 'हर क़दम इसे ईमानदार रखता है: उनके संग्रह पर आधारित, शब्द किसके हैं इसका लेबल, और जहाँ चुप रहना चाहिए वहाँ चुप।', 'દરેક પગલું તેને પ્રામાણિક રાખે છે: તેમના સંગ્રહ પર આધારિત, શબ્દો કોના છે તેનું લેબલ, અને જ્યાં ચૂપ રહેવું જોઈએ ત્યાં ચૂપ.'],
  ['Eight ready-made models, each built only from its own public-domain writing or public record, show what CHRONUS does with a person’s words.', 'आठ तैयार मॉडल, हर एक सिर्फ़ अपने सार्वजनिक लेखन या सार्वजनिक रिकॉर्ड से बना, दिखाते हैं कि CHRONUS किसी के शब्दों से क्या करता है।', 'આઠ તૈયાર મોડેલ, દરેક ફક્ત પોતાના જાહેર લેખન કે જાહેર રેકોર્ડમાંથી બનેલું, બતાવે છે કે CHRONUS કોઈના શબ્દો સાથે શું કરે છે.'],
  ['Encrypted backup', 'एन्क्रिप्टेड बैकअप', 'એન્ક્રિપ્ટેડ બેકઅપ'],
  ['Every answer arrives with its sources, a confidence level and the reason for it, and a grounding score.', 'हर जवाब अपने स्रोतों, भरोसे के स्तर और उसकी वजह, और आधार स्कोर के साथ आता है।', 'દરેક જવાબ તેના સ્રોતો, ભરોસાનું સ્તર અને તેનું કારણ, અને આધાર સ્કોર સાથે આવે છે.'],
  ['Every answer comes from something they really said.', 'हर जवाब उनकी सच में कही किसी बात से आता है।', 'દરેક જવાબ તેમણે ખરેખર કહેલી કોઈ વાતમાંથી આવે છે.'],
  ['Every claim cited', 'हर दावे का हवाला', 'દરેક દાવાનો હવાલો'],
  ['Every question is checked for crisis language first. If it is there, the model steps out of character and shows helplines.', 'हर सवाल में पहले संकट वाली भाषा की जाँच होती है। अगर हो, तो मॉडल किरदार से बाहर आकर हेल्पलाइन दिखाता है।', 'દરેક પ્રશ્નમાં પહેલા કટોકટીવાળી ભાષાની તપાસ થાય છે. જો હોય, તો મોડેલ પાત્રમાંથી બહાર આવીને હેલ્પલાઇન બતાવે છે.'],
  ['Everything it takes to', 'वह सब कुछ, जिससे', 'એ બધું, જેનાથી'],
  ['Exact sentences', 'हूबहू वाक्य', 'એકસરખાં વાક્યો'],
  ['Export a model as a password-protected .chronus file and import it on any install.', 'मॉडल को पासवर्ड वाली .chronus फ़ाइल के रूप में निकालें और किसी भी इंस्टॉल पर इम्पोर्ट करें।', 'મોડેલને પાસવર્ડવાળી .chronus ફાઇલ તરીકે કાઢો અને કોઈ પણ ઇન્સ્ટોલ પર ઇમ્પોર્ટ કરો.'],
  ['Fair', 'वाजिब', 'વાજબી'],
  ['Family’s memories', 'परिवार की यादें', 'પરિવારની યાદો'],
  ['Feedback', 'फ़ीडबैक', 'પ્રતિસાદ'],
  ['Fillers removed', 'फ़ालतू शब्द हटाए गए', 'વધારાના શબ્દો દૂર કર્યા'],
  ['Five places', 'पाँच जगहें', 'પાંચ જગ્યા'],
  ['Five steps.', 'पाँच क़दम।', 'પાંચ પગલાં.'],
  ['For someone who has died.', 'उनके लिए जो अब नहीं रहे।', 'તેમના માટે જે હવે નથી રહ્યા.'],
  ['For thirty years I taught fractions at our village school, and mostly I used mangoes to do it.', 'तीस साल मैंने अपने गाँव के स्कूल में भिन्न पढ़ाए, और ज़्यादातर आमों से पढ़ाए।', 'ત્રીસ વર્ષ મેં અમારા ગામની શાળામાં અપૂર્ણાંક ભણાવ્યા, અને મોટે ભાગે કેરીઓથી ભણાવ્યા.'],
  ['From', 'से', 'થી'],
  ['From the guided interview · tap a dimension', 'निर्देशित इंटरव्यू से · कोई पहलू चुनें', 'માર્ગદર્શિત ઇન્ટરવ્યૂમાંથી · કોઈ પાસું પસંદ કરો'],
  ['Generated or reviewed answers, marked as such wherever they appear.', 'बनाए गए या जाँचे गए जवाब, जहाँ भी दिखें, उन पर यही निशान रहता है।', 'બનાવેલા કે તપાસેલા જવાબ, જ્યાં પણ દેખાય, તેના પર આ નિશાન રહે છે.'],
  ['Hand-checked corrections', 'हाथ से जाँचे गए सुधार', 'હાથે તપાસેલા સુધારા'],
  ['Hands-free conversation', 'बिना हाथ लगाए बातचीत', 'હાથ લગાવ્યા વિના વાતચીત'],
  ['Her own words · notes.txt', 'उनके अपने शब्द · notes.txt', 'તેમના પોતાના શબ્દો · notes.txt'],
  ['Her voice', 'उनकी आवाज़', 'તેમનો અવાજ'],
  ['Honesty with children. They always know', 'बच्चों से ईमानदारी। उन्हें हमेशा पता चल जाता है', 'બાળકો સાથે પ્રામાણિકતા. તેમને હંમેશાં ખબર પડી જાય છે'],
  ['How did you teach fractions?', 'आप भिन्न कैसे पढ़ाती थीं?', 'તમે અપૂર્ણાંક કેવી રીતે ભણાવતાં?'],
  ['How is their voice cloned?', 'उनकी आवाज़ कैसे क्लोन होती है?', 'તેમનો અવાજ કેવી રીતે ક્લોન થાય છે?'],
  ['How they said goodnight', 'वे शुभ रात्रि कैसे कहते थे', 'તેઓ શુભ રાત્રિ કેવી રીતે કહેતા'],
  ['I don’t know.', 'मुझे नहीं पता।', 'મને ખબર નથી.'],
  ['I don’t know. I never talked about that.', 'मुझे नहीं पता। मैंने उसके बारे में कभी बात नहीं की।', 'મને ખબર નથી. મેં તેના વિશે ક્યારેય વાત નથી કરી.'],
  ['I have their consent', 'मेरे पास उनकी सहमति है', 'મારી પાસે તેમની સંમતિ છે'],
  ['In range', 'दायरे में', 'મર્યાદામાં'],
  ['Interview', 'इंटरव्यू', 'ઇન્ટરવ્યૂ'],
  ['Interview: memories', 'इंटरव्यू: यादें', 'ઇન્ટરવ્યૂ: યાદો'],
  ['Interview: personality', 'इंटरव्यू: व्यक्तित्व', 'ઇન્ટરવ્યૂ: વ્યક્તિત્વ'],
  ['Is it really them?', 'क्या यह सच में वही हैं?', 'શું આ ખરેખર તેઓ જ છે?'],
  ['It says “I don’t know.” If no memory is close enough to your question, measured against a threshold calibrated for that model, no language model is called at all.', 'यह कहता है “मुझे नहीं पता।” अगर कोई याद आपके सवाल के काफ़ी पास नहीं है, जिसे उस मॉडल के लिए तय सीमा से मापा जाता है, तो किसी भाषा मॉडल को बुलाया ही नहीं जाता।', 'તે કહે છે “મને ખબર નથી.” જો કોઈ યાદ તમારા પ્રશ્નની પૂરતી નજીક ન હોય, જે તે મોડેલ માટે નક્કી કરેલી મર્યાદાથી મપાય છે, તો કોઈ ભાષા મોડેલને બોલાવાતું જ નથી.'],
  ['Journal', 'डायरी', 'ડાયરી'],
  ['Journals', 'डायरियाँ', 'ડાયરીઓ'],
  ['Kamla Patel · sample', 'कमला पटेल · नमूना', 'કમલા પટેલ · નમૂનો'],
  ['Keep talking.', 'बात करते रहें।', 'વાત કરતા રહો.'],
  ['Keep their words.', 'उनके शब्द सहेजें।', 'તેમના શબ્દો સાચવો.'],
  ['Knowledge gaps', 'जानकारी की कमियाँ', 'જાણકારીની ખામીઓ'],
  ['Languages', 'भाषाएँ', 'ભાષાઓ'],
  ['Left out', 'बाहर', 'બહાર'],
  ['Letter', 'चिट्ठी', 'પત્ર'],
  ['Letters', 'चिट्ठियाँ', 'પત્રો'],
  ['Letters and journals (.txt .md .pdf .docx .csv .json), photos of pages, or voice notes.', 'चिट्ठियाँ और डायरियाँ (.txt .md .pdf .docx .csv .json), पन्नों की फ़ोटो, या वॉइस नोट्स।', 'પત્રો અને ડાયરીઓ (.txt .md .pdf .docx .csv .json), પાનાંના ફોટા, અથવા વૉઇસ નોટ્સ.'],
  ['Letters to Ravi', 'रवि को चिट्ठियाँ', 'રવિને પત્રો'],
  ['Letters, journals, photos of handwritten pages and voice notes become memories, each labelled by whose words it is.', 'चिट्ठियाँ, डायरियाँ, हाथ से लिखे पन्नों की फ़ोटो और वॉइस नोट्स यादें बनते हैं, हर एक पर लेबल कि शब्द किसके हैं।', 'પત્રો, ડાયરીઓ, હાથે લખેલાં પાનાંના ફોટા અને વૉઇસ નોટ્સ યાદો બને છે, દરેક પર લેબલ કે શબ્દો કોના છે.'],
  ['Limit answers to memories dated within the years you choose.', 'जवाब सिर्फ़ उन यादों से, जो आपके चुने सालों के बीच की हों।', 'જવાબ ફક્ત એ યાદોમાંથી, જે તમે પસંદ કરેલાં વર્ષોની વચ્ચેની હોય.'],
  ['Listening', 'सुन रहा है', 'સાંભળી રહ્યું છે'],
  ['Locked until consent', 'सहमति तक बंद', 'સંમતિ સુધી બંધ'],
  ['Logged for Insights', 'इनसाइट्स के लिए दर्ज', 'ઇનસાઇટ્સ માટે નોંધ્યું'],
  ['Memorial mode', 'स्मृति मोड', 'સ્મૃતિ મોડ'],
  ['Memory browser', 'यादों का ब्राउज़र', 'યાદોનું બ્રાઉઝર'],
  ['Memory vectors', 'याद वेक्टर', 'યાદ વેક્ટર'],
  ['Model', 'मॉडल', 'મોડેલ'],
  ['Move over the field', 'मैदान पर पॉइंटर घुमाएँ', 'ક્ષેત્ર પર પોઇન્ટર ફેરવો'],
  ['Natural phrasing', 'सहज भाषा', 'સહજ ભાષા'],
  ['Near-duplicates dropped', 'लगभग दोहराव हटाए गए', 'લગભગ પુનરાવર્તન દૂર કર્યાં'],
  ['Needed', 'ज़रूरी', 'જરૂરી'],
  ['Needs the AI voice', 'AI आवाज़ ज़रूरी', 'AI અવાજ જરૂરી'],
  ['No retrieval needed', 'खोज की ज़रूरत नहीं', 'શોધની જરૂર નથી'],
  ['No, and it never pretends to be. It is a model built only from what they actually said, wrote and answered. Quotes only shows their exact sentences; AI voice rewrites them, cites each source, and falls back to quotes when it can’t stay grounded.', 'नहीं, और यह कभी होने का दिखावा भी नहीं करता। यह सिर्फ़ उनकी सच में कही, लिखी और जवाब में दी बातों से बना मॉडल है। सिर्फ़ उद्धरण उनके हूबहू वाक्य दिखाता है; AI आवाज़ उन्हें दोबारा लिखती है, हर स्रोत का हवाला देती है, और आधार न रहे तो उद्धरणों पर लौट आती है।', 'ના, અને તે ક્યારેય હોવાનો ડોળ પણ નથી કરતું. તે ફક્ત તેમણે ખરેખર કહેલી, લખેલી અને જવાબમાં આપેલી વાતોમાંથી બનેલું મોડેલ છે. ફક્ત અવતરણ તેમનાં એકસરખાં વાક્યો બતાવે છે; AI અવાજ તેમને ફરી લખે છે, દરેક સ્રોતનો હવાલો આપે છે, અને આધાર ન રહે તો અવતરણો પર પાછો આવે છે.'],
  ['Not a chatbot wearing a name. A private model of one real person, built only from what they wrote, said and answered, so it sounds like them because it is them.', 'किसी का नाम ओढ़े चैटबॉट नहीं। एक असली इंसान का निजी मॉडल, सिर्फ़ उनके लिखे, कहे और दिए जवाबों से बना, इसलिए वह उन जैसा लगता है क्योंकि वह उन्हीं के शब्द हैं।', 'કોઈનું નામ ઓઢેલું ચેટબૉટ નહીં. એક સાચી વ્યક્તિનું ખાનગી મોડેલ, ફક્ત તેમણે લખેલા, કહેલા અને આપેલા જવાબોમાંથી બનેલું, એટલે તે તેમના જેવું લાગે છે કારણ કે તે તેમના જ શબ્દો છે.'],
  ['Not ready yet?', 'अभी तैयार नहीं?', 'હજી તૈયાર નથી?'],
  ['Nothing in her archive came close · no AI was asked', 'उनके संग्रह में कुछ भी पास नहीं आया · AI से पूछा ही नहीं गया', 'તેમના સંગ્રહમાં કંઈ નજીક ન આવ્યું · AI ને પૂછાયું જ નહીં'],
  ['Nothing inside θ', 'θ के अंदर कुछ नहीं', 'θ ની અંદર કંઈ નહીં'],
  ['Nothing left', 'कुछ नहीं बचा', 'કંઈ બાકી નથી'],
  ['Off', 'बंद', 'બંધ'],
  ['One person’s archive', 'एक व्यक्ति का संग्रह', 'એક વ્યક્તિનો સંગ્રહ'],
  ['Open', 'खोलें', 'ખોલો'],
  ['Open the voice studio', 'वॉइस स्टूडियो खोलें', 'વૉઇસ સ્ટુડિયો ખોલો'],
  ['Optional hybrid BM25 + rerank', 'वैकल्पिक हाइब्रिड BM25 + रीरैंक', 'વૈકલ્પિક હાઇબ્રિડ BM25 + રીરૅન્ક'],
  ['Optional year range', 'वैकल्पिक सालों की सीमा', 'વૈકલ્પિક વર્ષોની મર્યાદા'],
  ['Own words', 'अपने शब्द', 'પોતાના શબ્દો'],
  ['Personality preservation · consent first', 'व्यक्तित्व सहेजना · पहले सहमति', 'વ્યક્તિત્વ સાચવવું · પહેલા સંમતિ'],
  ['Pipeline steps', 'पाइपलाइन के क़दम', 'પાઇપલાઇનનાં પગલાં'],
  ['Preserve a person.', 'किसी को सहेजें।', 'કોઈને સાચવો.'],
  ['Preserve your first person', 'अपने पहले व्यक्ति को सहेजें', 'તમારી પહેલી વ્યક્તિને સાચવો'],
  ['Profile facts', 'प्रोफ़ाइल तथ्य', 'પ્રોફાઇલ હકીકતો'],
  ['Q&A log entries', 'सवाल-जवाब लॉग की प्रविष्टियाँ', 'પ્રશ્ન-જવાબ લૉગની નોંધો'],
  ['Question language', 'सवाल की भाषा', 'પ્રશ્નની ભાષા'],
  ['Quotes if ungrounded', 'आधार न हो तो उद्धरण', 'આધાર ન હોય તો અવતરણ'],
  ['Quotes only', 'सिर्फ़ उद्धरण', 'ફક્ત અવતરણ'],
  ['Quotes only gives you their exact sentences. AI voice rephrases them conversationally, cites every claim, and falls back to quotes when it can’t stay grounded.', 'सिर्फ़ उद्धरण आपको उनके हूबहू वाक्य देता है। AI आवाज़ उन्हें बातचीत के लहजे में कहती है, हर दावे का हवाला देती है, और आधार न रहे तो उद्धरणों पर लौट आती है।', 'ફક્ત અવતરણ તમને તેમનાં એકસરખાં વાક્યો આપે છે. AI અવાજ તેમને વાતચીતના લહેકામાં કહે છે, દરેક દાવાનો હવાલો આપે છે, અને આધાર ન રહે તો અવતરણો પર પાછો આવે છે.'],
  ['Quotes only returns the one to three sentences of each memory that answer you. AI voice rewrites their words with [n] citations, and falls back to quotes if it is not grounded.', 'सिर्फ़ उद्धरण हर याद के वे एक से तीन वाक्य लौटाता है जो आपको जवाब देते हैं। AI आवाज़ उनके शब्द [n] हवालों के साथ दोबारा लिखती है, और आधार न हो तो उद्धरणों पर लौट आती है।', 'ફક્ત અવતરણ દરેક યાદનાં એ એકથી ત્રણ વાક્યો આપે છે જે તમને જવાબ આપે છે. AI અવાજ તેમના શબ્દો [n] હવાલા સાથે ફરી લખે છે, અને આધાર ન હોય તો અવતરણો પર પાછો આવે છે.'],
  ['Read aloud in her cloned voice, made from a consented recording.', 'उनकी क्लोन आवाज़ में पढ़ा गया, जो सहमति से की गई रिकॉर्डिंग से बनी है।', 'તેમના ક્લોન અવાજમાં વાંચ્યું, જે સંમતિથી કરેલા રેકોર્ડિંગમાંથી બન્યો છે.'],
  ['Read from photo', 'फ़ोटो से पढ़ा गया', 'ફોટામાંથી વાંચ્યું'],
  ['Ready', 'तैयार', 'તૈયાર'],
  ['Recorded in English', 'अंग्रेज़ी में दर्ज', 'અંગ્રેજીમાં નોંધાયું'],
  ['Relationship', 'रिश्ता', 'સંબંધ'],
  ['Remove a model, remove all of it.', 'मॉडल हटाएँ, तो पूरा हटाएँ।', 'મોડેલ દૂર કરો, તો આખું દૂર કરો.'],
  ['Removing', 'हटाया जा रहा है', 'દૂર થઈ રહ્યું છે'],
  ['Restore the demo', 'डेमो फिर से शुरू करें', 'ડેમો ફરી શરૂ કરો'],
  ['Retrieve', 'खोजें', 'શોધો'],
  ['Reviewed answers', 'जाँचे गए जवाब', 'તપાસેલા જવાબ'],
  ['Runs on every message', 'हर संदेश पर चलता है', 'દરેક સંદેશ પર ચાલે છે'],
  ['Same question.', 'वही सवाल।', 'એ જ પ્રશ્ન.'],
  ['Sample archive', 'नमूना संग्रह', 'નમૂના સંગ્રહ'],
  ['Sample archive · real embeddings have 384 dimensions', 'नमूना संग्रह · असली एम्बेडिंग में 384 आयाम होते हैं', 'નમૂના સંગ્રહ · સાચા એમ્બેડિંગમાં 384 પરિમાણ હોય છે'],
  ['Sample model · retired teacher', 'नमूना मॉडल · सेवानिवृत्त शिक्षिका', 'નમૂના મોડેલ · નિવૃત્ત શિક્ષિકા'],
  ['Sample · cites interview answer Q14', 'नमूना · इंटरव्यू जवाब Q14 का हवाला', 'નમૂનો · ઇન્ટરવ્યૂ જવાબ Q14 નો હવાલો'],
  ['School diaries', 'स्कूल की डायरियाँ', 'શાળાની ડાયરીઓ'],
  ['Scroll', 'स्क्रॉल करें', 'સ્ક્રોલ કરો'],
  ['Search what a model knows. Edit, hide from quotes or delete any memory.', 'खोजें कि मॉडल क्या जानता है। कोई भी याद बदलें, उद्धरणों से छिपाएँ या मिटाएँ।', 'શોધો કે મોડેલ શું જાણે છે. કોઈ પણ યાદ બદલો, અવતરણોમાંથી છુપાવો કે ભૂંસો.'],
  ['Searching', 'खोज रहा है', 'શોધી રહ્યું છે'],
  ['See how it works', 'देखें यह कैसे काम करता है', 'જુઓ તે કેવી રીતે કામ કરે છે'],
  ['See what people asked that the archive couldn’t answer, with the interview question that would fill it.', 'देखें लोगों ने क्या पूछा जिसका जवाब संग्रह नहीं दे सका, और कौन-सा इंटरव्यू सवाल वह कमी भरेगा।', 'જુઓ લોકોએ શું પૂછ્યું જેનો જવાબ સંગ્રહ ન આપી શક્યો, અને કયો ઇન્ટરવ્યૂ પ્રશ્ન તે ખામી પૂરી કરશે.'],
  ['Selected memory', 'चुनी हुई याद', 'પસંદ કરેલી યાદ'],
  ['Sentence-BERT embeddings search this person’s own ChromaDB collection. Nothing close enough means “I don’t know”, and no language model is called.', 'Sentence-BERT एम्बेडिंग इसी व्यक्ति के अपने ChromaDB संग्रह में खोजते हैं। कुछ भी काफ़ी पास न हो तो जवाब “मुझे नहीं पता”, और कोई भाषा मॉडल नहीं बुलाया जाता।', 'Sentence-BERT એમ્બેડિંગ આ જ વ્યક્તિના પોતાના ChromaDB સંગ્રહમાં શોધે છે. કંઈ પૂરતું નજીક ન હોય તો જવાબ “મને ખબર નથી”, અને કોઈ ભાષા મોડેલ બોલાવાતું નથી.'],
  ['Server offline', 'सर्वर बंद है', 'સર્વર બંધ છે'],
  ['Short, normal or detailed', 'छोटा, सामान्य या विस्तार से', 'ટૂંકું, સામાન્ય કે વિગતવાર'],
  ['Show its work', 'अपना काम दिखाता है', 'પોતાનું કામ બતાવે છે'],
  ['Simple facts like “When were you born?” are answered from a checked profile, without searching the archive.', '“आपका जन्म कब हुआ?” जैसे सीधे तथ्य संग्रह खोजे बिना, जाँची हुई प्रोफ़ाइल से बताए जाते हैं।', '“તમારો જન્મ ક્યારે થયો?” જેવી સીધી હકીકતો સંગ્રહ શોધ્યા વિના, તપાસેલી પ્રોફાઇલમાંથી કહેવાય છે.'],
  ['Six checks between your question and', 'आपके सवाल और', 'તમારા પ્રશ્ન અને'],
  ['So nothing starts without their yes.', 'इसलिए उनकी हाँ के बिना कुछ शुरू नहीं होता।', 'એટલે તેમની હા વિના કંઈ શરૂ થતું નથી.'],
  ['Source', 'स्रोत', 'સ્રોત'],
  ['Start it with', 'इसे', 'તેને'],
  ['Start the CHRONUS server to load the pretrained models.', 'पहले से तैयार मॉडल लोड करने के लिए CHRONUS सर्वर चालू करें।', 'પહેલેથી તૈયાર મોડેલ લોડ કરવા CHRONUS સર્વર ચાલુ કરો.'],
  ['Statement', 'वक्तव्य', 'નિવેદન'],
  ['Status', 'स्थिति', 'સ્થિતિ'],
  ['Step {n} of 5', 'क़दम {n} / 5', 'પગલું {n} / 5'],
  ['Streamed as it is written', 'जैसे-जैसे लिखा जाता है, वैसे-वैसे दिखता है', 'જેમ લખાય છે તેમ દેખાય છે'],
  ['Synthesized', 'संश्लेषित', 'સંશ્લેષિત'],
  ['Talk', 'बात करें', 'વાત કરો'],
  ['Talk to them at 30, or at 70.', '30 की उम्र में उनसे बात करें, या 70 में।', '30 વર્ષની ઉંમરે તેમની સાથે વાત કરો, કે 70 એ.'],
  ['Talk with them', 'उनसे बात करें', 'તેમની સાથે વાત કરો'],
  ['The answer is built from these memories and cites each one.', 'जवाब इन्हीं यादों से बनता है और हर एक का हवाला देता है।', 'જવાબ આ જ યાદોમાંથી બને છે અને દરેકનો હવાલો આપે છે.'],
  ['The closest memory is {near} away and θ is {theta}, so nothing is cited and no language model is called.', 'सबसे पास की याद {near} दूर है और θ {theta} है, इसलिए किसी का हवाला नहीं दिया जाता और कोई भाषा मॉडल नहीं बुलाया जाता।', 'સૌથી નજીકની યાદ {near} દૂર છે અને θ {theta} છે, એટલે કોઈનો હવાલો અપાતો નથી અને કોઈ ભાષા મોડેલ બોલાવાતું નથી.'],
  ['The interview', 'इंटरव्यू', 'ઇન્ટરવ્યૂ'],
  ['The moment a child’s face changes, when the sum finally makes sense.', 'वह पल जब बच्चे का चेहरा बदल जाता है, जब सवाल आख़िरकार समझ आ जाता है।', 'એ ક્ષણ જ્યારે બાળકનો ચહેરો બદલાઈ જાય છે, જ્યારે દાખલો આખરે સમજાઈ જાય છે.'],
  ['The short version: it only says what their words support, and it tells you where each answer came from.', 'छोटे में: यह वही कहता है जो उनके शब्दों से साबित हो, और बताता है कि हर जवाब कहाँ से आया।', 'ટૂંકમાં: તે એ જ કહે છે જે તેમના શબ્દોથી સાબિત થાય, અને કહે છે કે દરેક જવાબ ક્યાંથી આવ્યો.'],
  ['The stories only they knew', 'वे कहानियाँ जो सिर्फ़ वे जानते थे', 'એ વાર્તાઓ જે ફક્ત તેઓ જાણતા હતા'],
  ['The way they tell a story', 'उनका कहानी सुनाने का अंदाज़', 'તેમની વાર્તા કહેવાની રીત'],
  ['Their advice', 'उनकी सलाह', 'તેમની સલાહ'],
  ['Their cloned voice', 'उनकी क्लोन आवाज़', 'તેમનો ક્લોન અવાજ'],
  ['Their consent, and some of their words: letters, journals, notes, photos of handwritten pages or voice notes. The 25-question interview fills in the rest, and you can keep adding memories later.', 'उनकी सहमति, और उनके कुछ शब्द: चिट्ठियाँ, डायरियाँ, नोट्स, हाथ से लिखे पन्नों की फ़ोटो या वॉइस नोट्स। बाक़ी 25 सवालों वाला इंटरव्यू भर देता है, और आप बाद में भी यादें जोड़ते रह सकते हैं।', 'તેમની સંમતિ, અને તેમના થોડા શબ્દો: પત્રો, ડાયરીઓ, નોંધો, હાથે લખેલાં પાનાંના ફોટા કે વૉઇસ નોટ્સ. બાકીનું 25 પ્રશ્નોવાળો ઇન્ટરવ્યૂ પૂરું કરે છે, અને તમે પછી પણ યાદો ઉમેરતા રહી શકો છો.'],
  ['Their permission, recorded with the model and shown in About this model.', 'उनकी अनुमति, मॉडल के साथ दर्ज और “इस मॉडल के बारे में” में दिखाई गई।', 'તેમની પરવાનગી, મોડેલ સાથે નોંધાયેલી અને “આ મોડેલ વિશે” માં બતાવેલી.'],
  ['Their personality', 'उनका व्यक्तित्व', 'તેમનું વ્યક્તિત્વ'],
  ['Their personality,', 'उनका व्यक्तित्व,', 'તેમનું વ્યક્તિત્વ,'],
  ['Their sense of humour', 'उनका मज़ाकिया अंदाज़', 'તેમની રમૂજવૃત્તિ'],
  ['Their voice', 'उनकी आवाज़', 'તેમનો અવાજ'],
  ['Their words', 'उनके शब्द', 'તેમના શબ્દો'],
  ['They agree to be preserved, or for memorial mode, their family does. The record stays with the model.', 'वे ख़ुद सहेजे जाने के लिए राज़ी होते हैं, या स्मृति मोड में उनका परिवार। यह रिकॉर्ड मॉडल के साथ रहता है।', 'તેઓ પોતે સચવાવા માટે રાજી થાય છે, અથવા સ્મૃતિ મોડમાં તેમનો પરિવાર. આ રેકોર્ડ મોડેલ સાથે રહે છે.'],
  ['Threshold calibrated per model', 'हर मॉडल के लिए तय सीमा', 'દરેક મોડેલ માટે નક્કી કરેલી મર્યાદા'],
  ['Threshold θ', 'सीमा θ', 'મર્યાદા θ'],
  ['Time travel', 'समय यात्रा', 'સમય યાત્રા'],
  ['To', 'तक', 'સુધી'],
  ['Top-k', 'Top-k', 'Top-k'],
  ['Transcribed', 'लिखित रूप में बदला', 'લેખિત સ્વરૂપમાં ફેરવ્યું'],
  ['Translate', 'अनुवाद', 'અનુવાદ'],
  ['Translated in and out, with the original shown. Needs the AI voice.', 'आते-जाते अनुवाद, मूल भी दिखता है। AI आवाज़ ज़रूरी है।', 'આવતાં-જતાં અનુવાદ, મૂળ પણ દેખાય છે. AI અવાજ જરૂરી છે.'],
  ['Try it on a sample', 'नमूने पर आज़माएँ', 'નમૂના પર અજમાવો'],
  ['Try it on history first.', 'पहले इतिहास पर आज़माएँ।', 'પહેલા ઇતિહાસ પર અજમાવો.'],
  ['Typed from her notebooks and uploaded by her family, with her consent.', 'उनकी कॉपियों से टाइप किया गया और उनकी सहमति से उनके परिवार ने अपलोड किया।', 'તેમની નોટબુકમાંથી ટાઇપ કરેલું અને તેમની સંમતિથી તેમના પરિવારે અપલોડ કરેલું.'],
  ['Under the hood', 'अंदर क्या है', 'અંદર શું છે'],
  ['Untranslated sources stay visible', 'बिना अनुवाद वाले स्रोत भी दिखते रहते हैं', 'અનુવાદ વિનાના સ્રોત પણ દેખાતા રહે છે'],
  ['Upload letters, journals and voice notes, answer the interview, and CHRONUS builds a private model that only you can open. Memorial mode is there for someone who has died.', 'चिट्ठियाँ, डायरियाँ और वॉइस नोट्स अपलोड करें, इंटरव्यू के जवाब दें, और CHRONUS एक निजी मॉडल बनाता है जिसे सिर्फ़ आप खोल सकते हैं। जो अब नहीं रहे, उनके लिए स्मृति मोड है।', 'પત્રો, ડાયરીઓ અને વૉઇસ નોટ્સ અપલોડ કરો, ઇન્ટરવ્યૂના જવાબ આપો, અને CHRONUS એક ખાનગી મોડેલ બનાવે છે જે ફક્ત તમે ખોલી શકો. જે હવે નથી રહ્યા, તેમના માટે સ્મૃતિ મોડ છે.'],
  ['Upload what they wrote and recorded. Anything someone else wrote is labelled, never quoted as theirs.', 'उनका लिखा और रिकॉर्ड किया हुआ अपलोड करें। किसी और का लिखा लेबल किया जाता है, कभी उनके शब्दों के रूप में नहीं दिखाया जाता।', 'તેમણે લખેલું અને રેકોર્ડ કરેલું અપલોડ કરો. બીજાએ લખેલું લેબલ થાય છે, ક્યારેય તેમના શબ્દો તરીકે બતાવાતું નથી.'],
  ['Uploaded files', 'अपलोड की गई फ़ाइलें', 'અપલોડ કરેલી ફાઇલો'],
  ['Used for context and labelled, but never shown as their quote.', 'संदर्भ के लिए इस्तेमाल और लेबल किया जाता है, पर कभी उनके उद्धरण के रूप में नहीं दिखाया जाता।', 'સંદર્ભ માટે વપરાય છે અને લેબલ થાય છે, પણ ક્યારેય તેમના અવતરણ તરીકે બતાવાતું નથી.'],
  ['View in context for every source', 'हर स्रोत को संदर्भ में देखें', 'દરેક સ્રોતને સંદર્ભમાં જુઓ'],
  ['Voice and build', 'आवाज़ और निर्माण', 'અવાજ અને નિર્માણ'],
  ['Voice note', 'वॉइस नोट', 'વૉઇસ નોટ'],
  ['Voice notes', 'वॉइस नोट्स', 'વૉઇસ નોટ્સ'],
  ['Watch a question', 'देखें, एक सवाल कैसे', 'જુઓ, એક પ્રશ્ન કેવી રીતે'],
  ['Wellbeing', 'भलाई', 'સુખાકારી'],
  ['What do I need to preserve someone?', 'किसी को सहेजने के लिए मुझे क्या चाहिए?', 'કોઈને સાચવવા માટે મારે શું જોઈએ?'],
  ['What do you think of cryptocurrency?', 'क्रिप्टोकरेंसी के बारे में आप क्या सोचती हैं?', 'ક્રિપ્ટોકરન્સી વિશે તમે શું વિચારો છો?'],
  ['What happens when it doesn’t know?', 'जब इसे पता न हो, तब क्या होता है?', 'જ્યારે તેને ખબર ન હોય, ત્યારે શું થાય છે?'],
  ['What principle would you never compromise on, no matter the cost?', 'ऐसा कौन-सा सिद्धांत है जिस पर आप किसी भी क़ीमत पर समझौता नहीं करेंगी?', 'એવો કયો સિદ્ધાંત છે જેના પર તમે કોઈ પણ કિંમતે સમાધાન નહીં કરો?'],
  ['What they believed', 'वे किस बात में विश्वास करते थे', 'તેઓ શેમાં માનતા હતા'],
  ['What they said or wrote. The only text CHRONUS will ever present as their quote.', 'जो उन्होंने कहा या लिखा। सिर्फ़ यही वह पाठ है जिसे CHRONUS कभी उनके उद्धरण के रूप में दिखाएगा।', 'જે તેમણે કહ્યું કે લખ્યું. ફક્ત આ જ લખાણ CHRONUS ક્યારેય તેમના અવતરણ તરીકે બતાવશે.'],
  ['What was your favourite part of teaching?', 'पढ़ाने में आपको सबसे अच्छा क्या लगता था?', 'ભણાવવામાં તમને સૌથી વધુ શું ગમતું?'],
  ['When they never said it, CHRONUS won’t make it up.', 'जो उन्होंने कभी नहीं कहा, CHRONUS वह गढ़ेगा नहीं।', 'જે તેમણે ક્યારેય નથી કહ્યું, તે CHRONUS ઘડી કાઢશે નહીં.'],
  ['Who can see the models I build?', 'मेरे बनाए मॉडल कौन देख सकता है?', 'મેં બનાવેલાં મોડેલ કોણ જોઈ શકે?'],
  ['With consent, a recording of them speaking is sent to Fish Audio to make a private voice. Removing the voice deletes it here and at Fish Audio. Pretrained figures use a clearly labelled stand-in voice, never a clone.', 'सहमति के साथ, उनके बोलने की रिकॉर्डिंग निजी आवाज़ बनाने के लिए Fish Audio को भेजी जाती है। आवाज़ हटाने पर वह यहाँ और Fish Audio पर, दोनों जगह से मिट जाती है। पहले से तैयार हस्तियाँ साफ़ लेबल वाली प्रतिनिधि आवाज़ इस्तेमाल करती हैं, कभी क्लोन नहीं।', 'સંમતિ સાથે, તેમના બોલવાનું રેકોર્ડિંગ ખાનગી અવાજ બનાવવા Fish Audio ને મોકલાય છે. અવાજ દૂર કરતાં તે અહીં અને Fish Audio પર, બંને જગ્યાએથી ભૂંસાઈ જાય છે. પહેલેથી તૈયાર હસ્તીઓ સ્પષ્ટ લેબલવાળો પ્રતિનિધિ અવાજ વાપરે છે, ક્યારેય ક્લોન નહીં.'],
  ['With consent, a short recording becomes their cloned voice, so every answer can be heard the way they said things.', 'सहमति के साथ, एक छोटी रिकॉर्डिंग उनकी क्लोन आवाज़ बनती है, ताकि हर जवाब वैसे सुनाई दे जैसे वे बात कहते थे।', 'સંમતિ સાથે, એક નાનું રેકોર્ડિંગ તેમનો ક્લોન અવાજ બને છે, જેથી દરેક જવાબ એ રીતે સંભળાય જે રીતે તેઓ વાત કહેતા.'],
  ['With consent, a short recording becomes their cloned voice. Turn on hands-free and simply talk: CHRONUS listens, answers from their words and reads it in their voice.', 'सहमति के साथ, एक छोटी रिकॉर्डिंग उनकी क्लोन आवाज़ बनती है। हैंड्स-फ़्री चालू करें और बस बोलें: CHRONUS सुनता है, उनके शब्दों से जवाब देता है और उनकी आवाज़ में पढ़ता है।', 'સંમતિ સાથે, એક નાનું રેકોર્ડિંગ તેમનો ક્લોન અવાજ બને છે. હૅન્ડ્સ-ફ્રી ચાલુ કરો અને બસ બોલો: CHRONUS સાંભળે છે, તેમના શબ્દોમાંથી જવાબ આપે છે અને તેમના અવાજમાં વાંચે છે.'],
  ['Works with no API key', 'बिना API key के भी चलता है', 'API key વિના પણ ચાલે છે'],
  ['Written by others', 'दूसरों का लिखा', 'બીજાએ લખેલું'],
  ['Yes, in memorial mode, built with the family’s agreement. Answers use gentler framing, and long sessions get a break reminder.', 'हाँ, स्मृति मोड में, परिवार की सहमति से। जवाबों का लहजा नरम रहता है, और लंबी बातचीत में आराम की याद दिलाई जाती है।', 'હા, સ્મૃતિ મોડમાં, પરિવારની સંમતિથી. જવાબોનો લહેકો નરમ રહે છે, અને લાંબી વાતચીતમાં આરામની યાદ અપાય છે.'],
  ['Your CHRONUS is live', 'आपका CHRONUS चालू है', 'તમારું CHRONUS ચાલુ છે'],
  ['Your CHRONUS right now', 'आपका CHRONUS अभी', 'તમારું CHRONUS અત્યારે'],
  ['Your cursor is the question. CHRONUS searches only this person’s memories, keeps the closest few inside its threshold, and answers from those. Outside the circle, it says “I don’t know.”', 'आपका कर्सर ही सवाल है। CHRONUS सिर्फ़ इसी व्यक्ति की यादें खोजता है, अपनी सीमा के अंदर की सबसे पास की कुछ यादें रखता है, और उन्हीं से जवाब देता है। घेरे के बाहर, वह कहता है “मुझे नहीं पता।”', 'તમારું કર્સર જ પ્રશ્ન છે. CHRONUS ફક્ત આ જ વ્યક્તિની યાદો શોધે છે, પોતાની મર્યાદાની અંદરની સૌથી નજીકની થોડી યાદો રાખે છે, અને તેમાંથી જ જવાબ આપે છે. વર્તુળની બહાર, તે કહે છે “મને ખબર નથી.”'],
  ['[1] notes.txt · her own words · sample model', '[1] notes.txt · उनके अपने शब्द · नमूना मॉडल', '[1] notes.txt · તેમના પોતાના શબ્દો · નમૂના મોડેલ'],
  ['dimensions of personality the interview maps', 'व्यक्तित्व के पहलू जिन्हें इंटरव्यू समझता है', 'વ્યક્તિત્વનાં પાસાં જે ઇન્ટરવ્યૂ સમજે છે'],
  ['file types it reads: documents, photos of pages and voice notes', 'फ़ाइल प्रकार जो यह पढ़ता है: दस्तावेज़, पन्नों की फ़ोटो और वॉइस नोट्स', 'ફાઇલ પ્રકાર જે તે વાંચે છે: દસ્તાવેજો, પાનાંના ફોટા અને વૉઇસ નોટ્સ'],
  ['find their words.', 'उनके शब्द ढूँढता है।', 'તેમના શબ્દો શોધે છે.'],
  ['guided questions, with adaptive follow-ups', 'निर्देशित सवाल, बदलते अगले सवालों के साथ', 'માર્ગદર્શિત પ્રશ્નો, બદલાતા આગળના પ્રશ્નો સાથે'],
  ['in their own words.', 'उन्हीं के शब्दों में।', 'તેમના જ શબ્દોમાં.'],
  ['keep them close.', 'वे क़रीब रहें।', 'તેઓ નજીક રહે.'],
  ['memories', 'यादें', 'યાદો'],
  ['person who can open your model: you', 'व्यक्ति जो आपका मॉडल खोल सकता है: आप', 'વ્યક્તિ જે તમારું મોડેલ ખોલી શકે: તમે'],
  ['preserved', 'सहेजे गए', 'સાચવેલા'],
  ['pretrained', 'पहले से तैयार', 'પહેલેથી તૈયાર'],
  ['questions.', 'सवाल।', 'પ્રશ્નો.'],
  ['their answer.', 'उनके जवाब के बीच छह जाँचें।', 'તેમના જવાબ વચ્ચે છ તપાસ.'],
  ['to preserve someone.', 'से शुरू करें, ताकि किसी को सहेज सकें।', 'થી શરૂ કરો, જેથી કોઈને સાચવી શકો.'],
  ['{n} memories inside θ', 'θ के अंदर {n} यादें', 'θ ની અંદર {n} યાદો'],
  ['{n} of 25 questions', '25 में से {n} सवाल', '25 માંથી {n} પ્રશ્નો'],
]
