// The home page in English, Hindi and Gujarati (merged into i18n.jsx).
// The Hindi and Gujarati were drafted for CHRONUS; have a native speaker check them.

export const HOME = {
  en: {
    'hero.eyebrow': 'Memory, not mimicry',
    'hero.line1': 'Their words.', 'hero.line2': 'Their voice.', 'hero.line3': 'Never invented.',
    'hero.sub': "CHRONUS answers in a person's own words, drawn from their interviews, letters and books. Every reply shows its source, and when the archive is silent, it says so.",
    'hero.create': 'Create a model with consent', 'hero.tryDemo': 'Try the live demo',
    'hero.modelsReady': 'models ready to talk to', 'hero.memories': 'source-tagged memories',
    'hero.cites': 'Every factual answer cites its source, or says “I don\'t know”',
    'hero.builtOn': 'Built on', 'hero.since': 'Research since 2024', 'hero.university': 'Parul University — B.Tech Project', 'hero.scroll': 'Scroll to explore',
    'preview.example': 'Example', 'preview.examples': 'Examples', 'preview.ownWords': 'own words', 'preview.verbatim': 'verbatim',
    'preview.noSource': 'No source found, so it says so', 'preview.ask': 'Ask {name} yourself →',
    'mq.consent': 'Consent-first', 'mq.reviewed': 'Human-reviewed', 'mq.nothingInvented': 'Nothing invented', 'mq.cited': 'Source-cited',
    'mq.privacy': 'Privacy-preserving', 'mq.notResurrection': 'Not a resurrection', 'mq.remembering': 'A remembering',
    'demo.title': 'Talk to a CHRONUS model',
    'demo.desc': 'See how a preserved intelligence responds to questions with depth, nuance, and voice. Every answer is traced back to something real.',
    'demo.disclaimer': "Live connection to the CHRONUS backend. This is an AI simulation built from Elon Musk's public interviews, tweets and biographies. It is not the real person and is not affiliated with him.",
    'common.createOwn': 'Create your own model', 'common.allModels': 'All models', 'common.createModel': 'Create a model', 'common.memories': '{count} memories',
    'common.loading': 'Loading…', 'common.deleting': 'Deleting…', 'common.cancel': 'Cancel', 'common.answerMode': 'Answer mode',
    'gallery.eyebrow': 'Pretrained models', 'gallery.title': 'Talk to history, in their own words',
    'gallery.intro': 'Each model answers only from texts its subject actually wrote or said: public-domain books, letters and speeches, or public interviews. Listen buttons use a labelled stand-in voice, never a clone.',
    'gallery.ask': 'Ask {name} →', 'gallery.more': 'All models, including yours',
    'why.line1': 'Personal archives', 'why.line2': 'disappear with', 'why.line3': 'the person.',
    'why.p1': "Texts, voice notes, letters, photos — usually static, unsearchable, and fading. Everything about a person's presence vanishes with them.",
    'why.p2': "CHRONUS turns that static archive into something you can actually revisit and ask things of — without pretending it's the person. Every answer is traced back to something real, or it says",
    'why.idk': '"I don\'t know."',
    'band.remember': 'Remember', 'band.protect': 'Protect', 'band.honor': 'Honor',
    'train.title': "Preserve someone's words", 'train.sub': 'Four steps, all in your browser, to a model that answers only from what they actually said.',
    's1.tag': 'CONSENT FIRST', 's1.title': 'Start with permission',
    's1.desc': "Name the person and your relationship to them, and confirm you have their consent (or their estate's). The consent is recorded with the model. Nothing leaves your computer unless you turn the cloud AI voice on.",
    's1.f1': 'Consent statement saved with a timestamp', 's1.f2': 'Private by default: models live on your machine', 's1.f3': 'Delete everything, vectors and files, in one click',
    's2.tag': 'THEIR OWN WORDS', 's2.title': 'Add letters, journals and transcripts',
    's2.desc': 'Upload what they wrote or said. Each file is split into short memories and embedded for search. Mark whether a file is in their own words or written about them, so a biography is never quoted as something they said.',
    's2.f1': '.txt, .md, .pdf, .docx, .csv and .json, up to 10 MB each', 's2.f2': 'Re-uploading a file replaces its old memories', 's2.f3': 'Every memory keeps its source file and page',
    's3.tag': 'GUIDED INTERVIEW', 's3.title': 'Fill the gaps with 25 questions',
    's3.desc': 'A structured interview across six dimensions, from personality to how they talk, captures what documents miss. Answers can come from the person or from family and friends, and the model always says who answered.',
    's3.f1': '6 dimensions: personality, memories, relationships, passions, values, voice', 's3.f2': 'Answering again replaces the earlier answer', 's3.f3': 'Built once there are at least 10 memories',
    's4.tag': 'TALK & VERIFY', 's4.title': 'Ask, check the source, listen',
    's4.desc': "Answers are built from the closest memories, quoted or carefully tidied, with every source and its match strength one click away. If nothing in the archive fits, it says “I don't know” instead of guessing.",
    's4.f1': 'Verbatim quotes mode, or an AI voice grounded in the quotes', 's4.f2': 'Listen in their consented voice (optional)', 's4.f3': 'Low-confidence answers are labelled as such',
    'train.readyTitle': 'Ready when you are.', 'train.readySub': 'Start a model now, or try the voice sandbox to hear how a consented voice clone sounds first.',
    'train.sandbox': 'Open the voice sandbox',
    'trust.eyebrow': 'Trust & Ethics', 'trust.title': 'Designed for dignity', 'trust.sub': 'Every answer comes with a visible source — so you always know where it came from.',
    'trust.c1.title': 'No invented opinions', 'trust.c1.desc': 'Answers are anchored to retrieved material, not generated from a persona prompt.',
    'trust.c2.title': 'Source citations on every answer', 'trust.c2.desc': 'Every response is tagged — "From a letter, 1998" — so you always know the origin.',
    'trust.c3.title': 'Session-aware design', 'trust.c3.desc': 'Intentionally built to avoid encouraging dependency — clear framing as a memory tool.',
    'trust.c4.title': 'Your data stays governed', 'trust.c4.desc': 'Access, deletion, and export controls live with the family, not the platform.',
    'hood.eyebrow': 'Under the Hood', 'hood.title': 'Built to be trustworthy',
    'hood.i1.title': 'Local-first by default', 'hood.i1.desc': "Your data doesn't have to leave your device.",
    'hood.i2.title': 'Encrypted backups', 'hood.i2.desc': 'Export a model as one password-encrypted file; without the password it is unreadable.',
    'hood.i3.title': 'Confidence thresholds', 'hood.i3.desc': 'Every answer checked against a confidence score before shown.',
    'roadmap.title': 'Where this is headed',
    'roadmap.p1.tag': 'Today', 'roadmap.p1.title': 'Local-first memory assistant', 'roadmap.p1.desc': 'A consent-based, source-cited, voice-authentic conversational agent running entirely on your device.',
    'roadmap.p2.tag': 'Coming Next', 'roadmap.p2.title': 'Secure family collaboration', 'roadmap.p2.desc': 'Multiple relatives contributing memories safely through federated, encrypted architecture.',
    'roadmap.p3.tag': 'Research Frontier', 'roadmap.p3.title': 'Neuromorphic & quantum-inspired memory', 'roadmap.p3.desc': 'Experimental work on brain-inspired dual-memory consolidation — clearly labeled as R&D, not product.',
    'faq.eyebrow': 'FAQ', 'faq.title': 'Common questions',
    'faq.q1': 'Is this meant to be the person?', 'faq.a1': 'No. CHRONUS is a memory retrieval tool, not a resurrection. It helps you revisit what someone actually said and believed.',
    'faq.q2': "What happens if it doesn't know something?", 'faq.a2': 'It says "I don\'t know." CHRONUS uses a strict confidence threshold and refuses to answer rather than guess.',
    'faq.q3': 'Who approves new answers?', 'faq.a3': 'A trusted human reviewer — typically a family member. The system never auto-generates content.',
    'faq.q4': 'Can I delete everything later?', 'faq.a4': 'Yes — immediately and unrecoverably. A single action deletes all local vectors, models, and voice samples.',
    'faq.q5': 'Who can access these memories?', 'faq.a5': 'Only people explicitly authorized. Access controls live with the family, not the platform.',
    'faq.q6': 'What if the person is still alive?', 'faq.a6': 'The strongest use case. They build their own archive — choosing what to include and how the system represents them.',
    'footer.line1': 'Start the way it', 'footer.line2': 'should start.',
    'footer.tagline': 'A consent-built memory archive. Every answer sourced. Every source named.',
    'footer.product': 'Product', 'footer.research': 'Research', 'footer.ethics': 'Ethics', 'footer.deleteData': 'Delete your data',
    'footer.code': 'Source code', 'footer.architecture': 'Architecture', 'footer.evaluation': 'Evaluation', 'footer.roadmapDoc': 'Roadmap doc',
    'footer.copyright': 'CHRONUS Research Project. Parul University.', 'footer.privacy': 'Privacy & ethics',
    'start.eyebrow': 'Start with consent', 'start.title': 'Where would you like to begin?',
    'start.o1.title': 'Build a model of someone', 'start.o1.body': 'Record consent, add their letters and answers, and talk to it. Everything stays on this computer by default.',
    'start.o2.title': 'Talk to a pretrained model', 'start.o2.body': 'Elon Musk and seven historical figures, built only from public interviews and public-domain texts.', 'start.o2.cta': 'Browse models',
    'start.o3.title': 'Hear a consented voice', 'start.o3.body': 'Clone your own voice (with consent) in the sandbox, and delete it whenever you like.', 'start.o3.cta': 'Open the sandbox',
    'start.questions': 'Questions about the research?', 'start.email': 'Email the team', 'start.issue': 'Open an issue on GitHub',
    'loader.tagline': 'Their words. Their voice. Their memory — never invented.', 'loader.init': 'Initializing',
    'app.skip': 'Skip to content',
  },
  hi: {
    'hero.eyebrow': 'यादें, नक़ल नहीं',
    'hero.line1': 'उनके शब्द।', 'hero.line2': 'उनकी आवाज़।', 'hero.line3': 'कुछ भी गढ़ा नहीं।',
    'hero.sub': 'CHRONUS किसी व्यक्ति के अपने शब्दों में जवाब देता है, जो उनके साक्षात्कारों, पत्रों और किताबों से लिए गए हैं। हर जवाब अपना स्रोत दिखाता है, और जब संग्रह में कुछ नहीं होता, तो वह साफ़ कह देता है।',
    'hero.create': 'सहमति से मॉडल बनाएँ', 'hero.tryDemo': 'लाइव डेमो आज़माएँ',
    'hero.modelsReady': 'मॉडल बात करने के लिए तैयार', 'hero.memories': 'स्रोत सहित यादें',
    'hero.cites': 'हर तथ्यात्मक जवाब अपना स्रोत बताता है, या कहता है “मुझे नहीं पता”',
    'hero.builtOn': 'इन पर बना', 'hero.since': '2024 से शोध', 'hero.university': 'पारुल विश्वविद्यालय — बी.टेक प्रोजेक्ट', 'hero.scroll': 'आगे देखने के लिए स्क्रॉल करें',
    'preview.example': 'उदाहरण', 'preview.examples': 'उदाहरण', 'preview.ownWords': 'अपने शब्द', 'preview.verbatim': 'शब्दशः',
    'preview.noSource': 'कोई स्रोत नहीं मिला, इसलिए यही बताया', 'preview.ask': 'खुद {name} से पूछें →',
    'mq.consent': 'सहमति पहले', 'mq.reviewed': 'इंसान द्वारा जाँचा गया', 'mq.nothingInvented': 'कुछ भी गढ़ा नहीं', 'mq.cited': 'स्रोत सहित',
    'mq.privacy': 'निजता की रक्षा', 'mq.notResurrection': 'पुनर्जीवन नहीं', 'mq.remembering': 'एक स्मरण',
    'demo.title': 'CHRONUS मॉडल से बात करें',
    'demo.desc': 'देखें कि सहेजी गई बुद्धि सवालों का जवाब गहराई, बारीकी और अपने अंदाज़ में कैसे देती है। हर जवाब किसी असली स्रोत से जुड़ा होता है।',
    'demo.disclaimer': 'CHRONUS बैकएंड से लाइव कनेक्शन। यह एलन मस्क के सार्वजनिक साक्षात्कारों, ट्वीट्स और जीवनियों से बना एक AI सिमुलेशन है। यह असली व्यक्ति नहीं है और उनसे संबद्ध नहीं है।',
    'common.createOwn': 'अपना मॉडल बनाएँ', 'common.allModels': 'सभी मॉडल', 'common.createModel': 'मॉडल बनाएँ', 'common.memories': '{count} यादें',
    'common.loading': 'लोड हो रहा है…', 'common.deleting': 'मिटाया जा रहा है…', 'common.cancel': 'रद्द करें', 'common.answerMode': 'जवाब का तरीका',
    'gallery.eyebrow': 'पहले से बने मॉडल', 'gallery.title': 'इतिहास से बात करें, उनके अपने शब्दों में',
    'gallery.intro': 'हर मॉडल सिर्फ़ उन्हीं पाठों से जवाब देता है जो उस व्यक्ति ने सच में लिखे या कहे: सार्वजनिक डोमेन की किताबें, पत्र और भाषण, या सार्वजनिक साक्षात्कार। सुनने के बटन एक लेबल वाली स्टैंड-इन आवाज़ इस्तेमाल करते हैं, कभी क्लोन नहीं।',
    'gallery.ask': '{name} से पूछें →', 'gallery.more': 'सभी मॉडल, आपके मॉडल सहित',
    'why.line1': 'निजी संग्रह', 'why.line2': 'इंसान के साथ ही', 'why.line3': 'खो जाते हैं।',
    'why.p1': 'संदेश, वॉइस नोट, पत्र, तस्वीरें — अक्सर बेजान, खोजे न जा सकने वाले, और धीरे-धीरे मिटते हुए। किसी व्यक्ति की मौजूदगी से जुड़ी हर चीज़ उनके साथ चली जाती है।',
    'why.p2': 'CHRONUS उस बेजान संग्रह को ऐसी चीज़ बनाता है जिसे आप सच में दोबारा देख सकें और जिससे सवाल पूछ सकें — बिना यह दिखावा किए कि वह वही व्यक्ति है। हर जवाब किसी असली चीज़ से जुड़ा होता है, वरना वह कहता है',
    'why.idk': '“मुझे नहीं पता।”',
    'band.remember': 'याद रखें', 'band.protect': 'सुरक्षित रखें', 'band.honor': 'सम्मान दें',
    'train.title': 'किसी के शब्द सहेजें', 'train.sub': 'चार चरण, सब आपके ब्राउज़र में, एक ऐसे मॉडल तक जो सिर्फ़ उन्हीं बातों से जवाब देता है जो उन्होंने सच में कहीं।',
    's1.tag': 'पहले सहमति', 's1.title': 'अनुमति से शुरुआत करें',
    's1.desc': 'व्यक्ति का नाम और उनसे अपना रिश्ता बताएँ, और पुष्टि करें कि आपके पास उनकी (या उनके उत्तराधिकारियों की) सहमति है। सहमति मॉडल के साथ दर्ज होती है। जब तक आप क्लाउड AI आवाज़ चालू नहीं करते, कुछ भी आपके कंप्यूटर से बाहर नहीं जाता।',
    's1.f1': 'सहमति का कथन समय के साथ सहेजा जाता है', 's1.f2': 'डिफ़ॉल्ट रूप से निजी: मॉडल आपकी मशीन पर रहते हैं', 's1.f3': 'सब कुछ, वेक्टर और फ़ाइलें, एक क्लिक में मिटाएँ',
    's2.tag': 'उनके अपने शब्द', 's2.title': 'पत्र, डायरी और ट्रांसक्रिप्ट जोड़ें',
    's2.desc': 'जो उन्होंने लिखा या कहा, वह अपलोड करें। हर फ़ाइल छोटी-छोटी यादों में बाँटी जाती है और खोज के लिए एम्बेड की जाती है। बताएँ कि फ़ाइल उनके अपने शब्दों में है या उनके बारे में लिखी गई है, ताकि किसी जीवनी को कभी उनकी कही बात की तरह उद्धृत न किया जाए।',
    's2.f1': '.txt, .md, .pdf, .docx, .csv और .json, हर एक 10 MB तक', 's2.f2': 'फ़ाइल दोबारा अपलोड करने पर उसकी पुरानी यादें बदल जाती हैं', 's2.f3': 'हर याद अपनी स्रोत फ़ाइल और पेज याद रखती है',
    's3.tag': 'निर्देशित साक्षात्कार', 's3.title': '25 सवालों से कमी पूरी करें',
    's3.desc': 'व्यक्तित्व से लेकर बोलने के अंदाज़ तक, छह पहलुओं वाला एक व्यवस्थित साक्षात्कार वह सब दर्ज करता है जो दस्तावेज़ों में छूट जाता है। जवाब खुद व्यक्ति या परिवार और दोस्त दे सकते हैं, और मॉडल हमेशा बताता है कि जवाब किसने दिया।',
    's3.f1': '6 पहलू: व्यक्तित्व, यादें, रिश्ते, शौक, मूल्य, आवाज़', 's3.f2': 'दोबारा जवाब देने पर पिछला जवाब बदल जाता है', 's3.f3': 'कम से कम 10 यादें होने पर मॉडल बनता है',
    's4.tag': 'बात करें और जाँचें', 's4.title': 'पूछें, स्रोत जाँचें, सुनें',
    's4.desc': 'जवाब सबसे करीबी यादों से बनते हैं, उद्धृत या ध्यान से संवारे हुए, और हर स्रोत व उसके मेल की ताकत बस एक क्लिक दूर होती है। अगर संग्रह में कुछ मेल नहीं खाता, तो वह अंदाज़ा लगाने के बजाय कहता है “मुझे नहीं पता”।',
    's4.f1': 'शब्दशः उद्धरण मोड, या उद्धरणों पर आधारित AI आवाज़', 's4.f2': 'उनकी सहमति वाली आवाज़ में सुनें (वैकल्पिक)', 's4.f3': 'कम भरोसे वाले जवाबों पर साफ़ लेबल लगता है',
    'train.readyTitle': 'जब आप तैयार हों।', 'train.readySub': 'अभी मॉडल शुरू करें, या पहले वॉइस सैंडबॉक्स में सुनें कि सहमति से क्लोन की गई आवाज़ कैसी लगती है।',
    'train.sandbox': 'वॉइस सैंडबॉक्स खोलें',
    'trust.eyebrow': 'भरोसा और नैतिकता', 'trust.title': 'गरिमा के लिए बनाया गया', 'trust.sub': 'हर जवाब के साथ उसका स्रोत दिखता है — ताकि आप हमेशा जानें कि वह कहाँ से आया।',
    'trust.c1.title': 'कोई गढ़ी हुई राय नहीं', 'trust.c1.desc': 'जवाब खोजी गई सामग्री पर टिके होते हैं, किसी पर्सोना प्रॉम्प्ट से बनाए नहीं जाते।',
    'trust.c2.title': 'हर जवाब पर स्रोत', 'trust.c2.desc': 'हर जवाब पर टैग होता है — जैसे "1998 का एक पत्र" — ताकि आप हमेशा उसका मूल जानें।',
    'trust.c3.title': 'सत्र का ध्यान रखने वाला डिज़ाइन', 'trust.c3.desc': 'जान-बूझकर ऐसा बनाया गया कि निर्भरता न बढ़े — साफ़ तौर पर यादों का एक औज़ार।',
    'trust.c4.title': 'आपका डेटा आपके नियंत्रण में', 'trust.c4.desc': 'पहुँच, मिटाने और निर्यात के नियंत्रण परिवार के पास रहते हैं, प्लेटफ़ॉर्म के पास नहीं।',
    'hood.eyebrow': 'अंदर की बात', 'hood.title': 'भरोसेमंद होने के लिए बनाया गया',
    'hood.i1.title': 'डिफ़ॉल्ट रूप से लोकल', 'hood.i1.desc': 'आपका डेटा आपके डिवाइस से बाहर जाना ज़रूरी नहीं।',
    'hood.i2.title': 'एन्क्रिप्टेड बैकअप', 'hood.i2.desc': 'किसी मॉडल को पासवर्ड से एन्क्रिप्ट की गई एक फ़ाइल के रूप में निर्यात करें; पासवर्ड के बिना उसे पढ़ा नहीं जा सकता।',
    'hood.i3.title': 'भरोसे की सीमाएँ', 'hood.i3.desc': 'हर जवाब दिखाने से पहले भरोसे के स्कोर पर जाँचा जाता है।',
    'roadmap.title': 'हम कहाँ जा रहे हैं',
    'roadmap.p1.tag': 'आज', 'roadmap.p1.title': 'लोकल-फ़र्स्ट यादों का सहायक', 'roadmap.p1.desc': 'सहमति पर आधारित, स्रोत बताने वाला, असली आवाज़ वाला बातचीत एजेंट, जो पूरी तरह आपके डिवाइस पर चलता है।',
    'roadmap.p2.tag': 'अगला कदम', 'roadmap.p2.title': 'परिवार के साथ सुरक्षित सहयोग', 'roadmap.p2.desc': 'कई रिश्तेदार फ़ेडरेटेड, एन्क्रिप्टेड ढाँचे के ज़रिए सुरक्षित रूप से यादें जोड़ सकें।',
    'roadmap.p3.tag': 'शोध की सीमा', 'roadmap.p3.title': 'न्यूरोमॉर्फ़िक और क्वांटम-प्रेरित स्मृति', 'roadmap.p3.desc': 'दिमाग़ से प्रेरित दोहरी-स्मृति समेकन पर प्रयोगात्मक काम — साफ़ तौर पर शोध और विकास के रूप में चिह्नित, उत्पाद के रूप में नहीं।',
    'faq.eyebrow': 'अक्सर पूछे जाने वाले सवाल', 'faq.title': 'आम सवाल',
    'faq.q1': 'क्या यह वही व्यक्ति होने के लिए है?', 'faq.a1': 'नहीं। CHRONUS यादें खोजने का एक औज़ार है, पुनर्जीवन नहीं। यह आपको वह दोबारा देखने में मदद करता है जो किसी ने सच में कहा और माना।',
    'faq.q2': 'अगर उसे कुछ पता न हो तो क्या होता है?', 'faq.a2': 'वह कहता है “मुझे नहीं पता।” CHRONUS भरोसे की सख़्त सीमा इस्तेमाल करता है और अंदाज़ा लगाने के बजाय जवाब देने से मना कर देता है।',
    'faq.q3': 'नए जवाबों को कौन मंज़ूरी देता है?', 'faq.a3': 'एक भरोसेमंद इंसान समीक्षक — आमतौर पर परिवार का कोई सदस्य। सिस्टम अपने आप कोई सामग्री नहीं बनाता।',
    'faq.q4': 'क्या बाद में सब कुछ मिटाया जा सकता है?', 'faq.a4': 'हाँ — तुरंत और हमेशा के लिए। एक ही कदम सारे लोकल वेक्टर, मॉडल और आवाज़ के नमूने मिटा देता है।',
    'faq.q5': 'इन यादों तक कौन पहुँच सकता है?', 'faq.a5': 'केवल वे लोग जिन्हें साफ़ तौर पर अनुमति दी गई है। पहुँच के नियंत्रण परिवार के पास रहते हैं, प्लेटफ़ॉर्म के पास नहीं।',
    'faq.q6': 'अगर व्यक्ति अभी जीवित है तो?', 'faq.a6': 'यही सबसे अच्छा उपयोग है। वे अपना संग्रह खुद बनाते हैं — यह चुनते हुए कि क्या शामिल हो और सिस्टम उन्हें कैसे दिखाए।',
    'footer.line1': 'शुरुआत वैसे करें', 'footer.line2': 'जैसे होनी चाहिए।',
    'footer.tagline': 'सहमति से बना यादों का संग्रह। हर जवाब का स्रोत। हर स्रोत का नाम।',
    'footer.product': 'प्रोडक्ट', 'footer.research': 'शोध', 'footer.ethics': 'नैतिकता', 'footer.deleteData': 'अपना डेटा मिटाएँ',
    'footer.code': 'सोर्स कोड', 'footer.architecture': 'आर्किटेक्चर', 'footer.evaluation': 'मूल्यांकन', 'footer.roadmapDoc': 'रोडमैप दस्तावेज़',
    'footer.copyright': 'CHRONUS शोध परियोजना। पारुल विश्वविद्यालय।', 'footer.privacy': 'निजता और नैतिकता',
    'start.eyebrow': 'सहमति से शुरू करें', 'start.title': 'आप कहाँ से शुरू करना चाहेंगे?',
    'start.o1.title': 'किसी का मॉडल बनाएँ', 'start.o1.body': 'सहमति दर्ज करें, उनके पत्र और जवाब जोड़ें, और उससे बात करें। डिफ़ॉल्ट रूप से सब कुछ इसी कंप्यूटर पर रहता है।',
    'start.o2.title': 'पहले से बने मॉडल से बात करें', 'start.o2.body': 'एलन मस्क और सात ऐतिहासिक हस्तियाँ, केवल सार्वजनिक साक्षात्कारों और सार्वजनिक डोमेन के पाठों से बने।', 'start.o2.cta': 'मॉडल देखें',
    'start.o3.title': 'सहमति वाली आवाज़ सुनें', 'start.o3.body': 'सैंडबॉक्स में अपनी आवाज़ (सहमति से) क्लोन करें, और जब चाहें मिटा दें।', 'start.o3.cta': 'सैंडबॉक्स खोलें',
    'start.questions': 'शोध के बारे में सवाल?', 'start.email': 'टीम को ईमेल करें', 'start.issue': 'GitHub पर इशू खोलें',
    'loader.tagline': 'उनके शब्द। उनकी आवाज़। उनकी यादें — कभी गढ़ी नहीं।', 'loader.init': 'शुरू हो रहा है',
    'app.skip': 'मुख्य सामग्री पर जाएँ',
  },
  gu: {
    'hero.eyebrow': 'યાદો, નકલ નહીં',
    'hero.line1': 'તેમના શબ્દો.', 'hero.line2': 'તેમનો અવાજ.', 'hero.line3': 'કંઈ ઘડી કાઢેલું નહીં.',
    'hero.sub': 'CHRONUS વ્યક્તિના પોતાના શબ્દોમાં જવાબ આપે છે, જે તેમના ઇન્ટરવ્યૂ, પત્રો અને પુસ્તકોમાંથી લેવાયા છે. દરેક જવાબ તેનો સ્રોત બતાવે છે, અને સંગ્રહમાં કંઈ ન હોય ત્યારે તે સ્પષ્ટ કહી દે છે.',
    'hero.create': 'સંમતિથી મોડેલ બનાવો', 'hero.tryDemo': 'લાઇવ ડેમો અજમાવો',
    'hero.modelsReady': 'મોડેલ વાત કરવા તૈયાર', 'hero.memories': 'સ્રોત સાથેની યાદો',
    'hero.cites': 'દરેક હકીકતી જવાબ તેનો સ્રોત બતાવે છે, અથવા કહે છે “મને ખબર નથી”',
    'hero.builtOn': 'આના પર બનેલું', 'hero.since': '2024 થી સંશોધન', 'hero.university': 'પારુલ યુનિવર્સિટી — બી.ટેક પ્રોજેક્ટ', 'hero.scroll': 'આગળ જોવા સ્ક્રોલ કરો',
    'preview.example': 'ઉદાહરણ', 'preview.examples': 'ઉદાહરણો', 'preview.ownWords': 'પોતાના શબ્દો', 'preview.verbatim': 'શબ્દશઃ',
    'preview.noSource': 'કોઈ સ્રોત ન મળ્યો, એટલે એ જ કહ્યું', 'preview.ask': 'જાતે {name}ને પૂછો →',
    'mq.consent': 'પહેલાં સંમતિ', 'mq.reviewed': 'માણસ દ્વારા ચકાસાયેલું', 'mq.nothingInvented': 'કંઈ ઘડી કાઢેલું નહીં', 'mq.cited': 'સ્રોત સાથે',
    'mq.privacy': 'ગોપનીયતાનું રક્ષણ', 'mq.notResurrection': 'પુનર્જીવન નહીં', 'mq.remembering': 'એક સ્મરણ',
    'demo.title': 'CHRONUS મોડેલ સાથે વાત કરો',
    'demo.desc': 'જુઓ કે સાચવેલી બુદ્ધિ પ્રશ્નોના જવાબ ઊંડાણ, બારીકાઈ અને પોતાના અંદાજમાં કેવી રીતે આપે છે. દરેક જવાબ કોઈ સાચા સ્રોત સાથે જોડાયેલો હોય છે.',
    'demo.disclaimer': 'CHRONUS બેકએન્ડ સાથે લાઇવ જોડાણ. આ ઇલોન મસ્કના જાહેર ઇન્ટરવ્યૂ, ટ્વીટ્સ અને જીવનચરિત્રોમાંથી બનેલું AI સિમ્યુલેશન છે. આ સાચી વ્યક્તિ નથી અને તેમની સાથે સંકળાયેલું નથી.',
    'common.createOwn': 'તમારું પોતાનું મોડેલ બનાવો', 'common.allModels': 'બધા મોડેલ', 'common.createModel': 'મોડેલ બનાવો', 'common.memories': '{count} યાદો',
    'common.loading': 'લોડ થઈ રહ્યું છે…', 'common.deleting': 'ભૂંસાઈ રહ્યું છે…', 'common.cancel': 'રદ કરો', 'common.answerMode': 'જવાબની રીત',
    'gallery.eyebrow': 'પહેલેથી બનેલા મોડેલ', 'gallery.title': 'ઇતિહાસ સાથે વાત કરો, તેમના પોતાના શબ્દોમાં',
    'gallery.intro': 'દરેક મોડેલ ફક્ત એવા લખાણોમાંથી જવાબ આપે છે જે તે વ્યક્તિએ ખરેખર લખ્યા કે કહ્યા હોય: જાહેર ડોમેનનાં પુસ્તકો, પત્રો અને ભાષણો, અથવા જાહેર ઇન્ટરવ્યૂ. સાંભળવાનાં બટન લેબલવાળો સ્ટેન્ડ-ઇન અવાજ વાપરે છે, ક્યારેય ક્લોન નહીં.',
    'gallery.ask': '{name}ને પૂછો →', 'gallery.more': 'બધા મોડેલ, તમારા સહિત',
    'why.line1': 'અંગત સંગ્રહો', 'why.line2': 'વ્યક્તિની સાથે જ', 'why.line3': 'ખોવાઈ જાય છે.',
    'why.p1': 'મેસેજ, વૉઇસ નોટ, પત્રો, ફોટા — મોટે ભાગે સ્થિર, શોધી ન શકાય એવા, અને ધીમે ધીમે ઝાંખા પડતા. વ્યક્તિની હાજરી સાથે જોડાયેલું બધું તેમની સાથે જતું રહે છે.',
    'why.p2': 'CHRONUS એ સ્થિર સંગ્રહને એવી વસ્તુમાં ફેરવે છે જેને તમે ખરેખર ફરી જોઈ શકો અને જેને પ્રશ્નો પૂછી શકો — એ વ્યક્તિ હોવાનો દેખાવ કર્યા વગર. દરેક જવાબ કોઈ સાચી વસ્તુ સાથે જોડાયેલો હોય છે, નહીંતર તે કહે છે',
    'why.idk': '“મને ખબર નથી.”',
    'band.remember': 'યાદ રાખો', 'band.protect': 'સાચવો', 'band.honor': 'સન્માન આપો',
    'train.title': 'કોઈના શબ્દો સાચવો', 'train.sub': 'ચાર પગલાં, બધું તમારા બ્રાઉઝરમાં, એવા મોડેલ સુધી જે ફક્ત તેમણે ખરેખર કહેલી વાતોમાંથી જવાબ આપે.',
    's1.tag': 'પહેલાં સંમતિ', 's1.title': 'પરવાનગીથી શરૂઆત કરો',
    's1.desc': 'વ્યક્તિનું નામ અને તેમની સાથેનો તમારો સંબંધ જણાવો, અને ખાતરી કરો કે તમારી પાસે તેમની (અથવા તેમના વારસદારોની) સંમતિ છે. સંમતિ મોડેલ સાથે નોંધાય છે. તમે ક્લાઉડ AI અવાજ ચાલુ ન કરો ત્યાં સુધી કંઈ પણ તમારા કમ્પ્યુટરની બહાર જતું નથી.',
    's1.f1': 'સંમતિનું નિવેદન સમય સાથે સચવાય છે', 's1.f2': 'મૂળભૂત રીતે ખાનગી: મોડેલ તમારા મશીન પર રહે છે', 's1.f3': 'બધું, વેક્ટર અને ફાઇલો, એક ક્લિકમાં ભૂંસો',
    's2.tag': 'તેમના પોતાના શબ્દો', 's2.title': 'પત્રો, ડાયરી અને ટ્રાન્સક્રિપ્ટ ઉમેરો',
    's2.desc': 'તેમણે જે લખ્યું કે કહ્યું તે અપલોડ કરો. દરેક ફાઇલ નાની નાની યાદોમાં વહેંચાય છે અને શોધ માટે એમ્બેડ થાય છે. ફાઇલ તેમના પોતાના શબ્દોમાં છે કે તેમના વિશે લખાયેલી છે તે જણાવો, જેથી કોઈ જીવનચરિત્ર ક્યારેય તેમની કહેલી વાત તરીકે ટાંકવામાં ન આવે.',
    's2.f1': '.txt, .md, .pdf, .docx, .csv અને .json, દરેક 10 MB સુધી', 's2.f2': 'ફાઇલ ફરી અપલોડ કરવાથી તેની જૂની યાદો બદલાઈ જાય છે', 's2.f3': 'દરેક યાદ તેની સ્રોત ફાઇલ અને પાનું સાચવે છે',
    's3.tag': 'માર્ગદર્શિત ઇન્ટરવ્યૂ', 's3.title': '25 પ્રશ્નોથી ખૂટતું પૂરું કરો',
    's3.desc': 'વ્યક્તિત્વથી લઈને બોલવાની રીત સુધી, છ પાસાંનો એક વ્યવસ્થિત ઇન્ટરવ્યૂ દસ્તાવેજોમાં છૂટી ગયેલું બધું નોંધે છે. જવાબ વ્યક્તિ પોતે અથવા પરિવાર અને મિત્રો આપી શકે છે, અને મોડેલ હંમેશા જણાવે છે કે જવાબ કોણે આપ્યો.',
    's3.f1': '6 પાસાં: વ્યક્તિત્વ, યાદો, સંબંધો, શોખ, મૂલ્યો, અવાજ', 's3.f2': 'ફરી જવાબ આપવાથી અગાઉનો જવાબ બદલાઈ જાય છે', 's3.f3': 'ઓછામાં ઓછી 10 યાદો હોય ત્યારે મોડેલ બને છે',
    's4.tag': 'વાત કરો અને ચકાસો', 's4.title': 'પૂછો, સ્રોત તપાસો, સાંભળો',
    's4.desc': 'જવાબ સૌથી નજીકની યાદોમાંથી બને છે, ટાંકેલા અથવા કાળજીથી સુધારેલા, અને દરેક સ્રોત અને તેના મેળની તાકાત એક ક્લિક દૂર હોય છે. જો સંગ્રહમાં કંઈ બંધબેસતું ન હોય, તો તે અનુમાન કરવાને બદલે કહે છે “મને ખબર નથી”.',
    's4.f1': 'શબ્દશઃ અવતરણ મોડ, અથવા અવતરણો પર આધારિત AI અવાજ', 's4.f2': 'તેમના સંમતિવાળા અવાજમાં સાંભળો (વૈકલ્પિક)', 's4.f3': 'ઓછા ભરોસાવાળા જવાબો પર સ્પષ્ટ લેબલ હોય છે',
    'train.readyTitle': 'જ્યારે તમે તૈયાર હો.', 'train.readySub': 'હમણાં મોડેલ શરૂ કરો, અથવા પહેલાં વૉઇસ સેન્ડબોક્સમાં સાંભળો કે સંમતિથી ક્લોન કરેલો અવાજ કેવો લાગે છે.',
    'train.sandbox': 'વૉઇસ સેન્ડબોક્સ ખોલો',
    'trust.eyebrow': 'ભરોસો અને નૈતિકતા', 'trust.title': 'ગરિમા માટે રચાયેલું', 'trust.sub': 'દરેક જવાબ સાથે તેનો સ્રોત દેખાય છે — જેથી તમે હંમેશા જાણો કે તે ક્યાંથી આવ્યો.',
    'trust.c1.title': 'કોઈ ઘડી કાઢેલા અભિપ્રાય નહીં', 'trust.c1.desc': 'જવાબ શોધાયેલી સામગ્રી પર આધારિત હોય છે, કોઈ પર્સોના પ્રોમ્પ્ટથી બનાવેલા નહીં.',
    'trust.c2.title': 'દરેક જવાબ પર સ્રોત', 'trust.c2.desc': 'દરેક જવાબ પર ટૅગ હોય છે — જેમ કે "1998નો એક પત્ર" — જેથી તમે હંમેશા તેનું મૂળ જાણો.',
    'trust.c3.title': 'સત્રનું ધ્યાન રાખતી રચના', 'trust.c3.desc': 'જાણી જોઈને એવી રીતે બનાવ્યું છે કે નિર્ભરતા ન વધે — સ્પષ્ટપણે યાદોનું એક સાધન.',
    'trust.c4.title': 'તમારો ડેટા તમારા નિયંત્રણમાં', 'trust.c4.desc': 'પ્રવેશ, ભૂંસવા અને નિકાસનાં નિયંત્રણો પરિવાર પાસે રહે છે, પ્લેટફોર્મ પાસે નહીં.',
    'hood.eyebrow': 'અંદરની વાત', 'hood.title': 'ભરોસાપાત્ર બનવા માટે બનાવેલું',
    'hood.i1.title': 'મૂળભૂત રીતે લોકલ', 'hood.i1.desc': 'તમારો ડેટા તમારા ડિવાઇસની બહાર જાય એ જરૂરી નથી.',
    'hood.i2.title': 'એન્ક્રિપ્ટેડ બેકઅપ', 'hood.i2.desc': 'મોડેલને પાસવર્ડથી એન્ક્રિપ્ટ કરેલી એક ફાઇલ તરીકે નિકાસ કરો; પાસવર્ડ વગર તે વાંચી શકાતી નથી.',
    'hood.i3.title': 'ભરોસાની મર્યાદાઓ', 'hood.i3.desc': 'દરેક જવાબ બતાવતાં પહેલાં ભરોસાના સ્કોર સામે ચકાસાય છે.',
    'roadmap.title': 'આપણે ક્યાં જઈ રહ્યા છીએ',
    'roadmap.p1.tag': 'આજે', 'roadmap.p1.title': 'લોકલ-ફર્સ્ટ યાદોનો સહાયક', 'roadmap.p1.desc': 'સંમતિ આધારિત, સ્રોત બતાવતો, સાચા અવાજવાળો વાતચીત એજન્ટ, જે સંપૂર્ણપણે તમારા ડિવાઇસ પર ચાલે છે.',
    'roadmap.p2.tag': 'હવે પછી', 'roadmap.p2.title': 'પરિવાર સાથે સુરક્ષિત સહયોગ', 'roadmap.p2.desc': 'ઘણા સંબંધીઓ ફેડરેટેડ, એન્ક્રિપ્ટેડ માળખા દ્વારા સુરક્ષિત રીતે યાદો ઉમેરી શકે.',
    'roadmap.p3.tag': 'સંશોધનની સરહદ', 'roadmap.p3.title': 'ન્યુરોમોર્ફિક અને ક્વોન્ટમ-પ્રેરિત સ્મૃતિ', 'roadmap.p3.desc': 'મગજથી પ્રેરિત બેવડી-સ્મૃતિ એકીકરણ પર પ્રાયોગિક કામ — સ્પષ્ટપણે સંશોધન અને વિકાસ તરીકે દર્શાવેલું, ઉત્પાદન તરીકે નહીં.',
    'faq.eyebrow': 'વારંવાર પૂછાતા પ્રશ્નો', 'faq.title': 'સામાન્ય પ્રશ્નો',
    'faq.q1': 'શું આ એ જ વ્યક્તિ બનવા માટે છે?', 'faq.a1': 'ના. CHRONUS યાદો શોધવાનું સાધન છે, પુનર્જીવન નહીં. તે તમને એ ફરી જોવામાં મદદ કરે છે જે કોઈએ ખરેખર કહ્યું અને માન્યું.',
    'faq.q2': 'જો તેને કંઈક ખબર ન હોય તો શું થાય?', 'faq.a2': 'તે કહે છે “મને ખબર નથી.” CHRONUS ભરોસાની કડક મર્યાદા વાપરે છે અને અનુમાન કરવાને બદલે જવાબ આપવાનો ઇનકાર કરે છે.',
    'faq.q3': 'નવા જવાબોને કોણ મંજૂરી આપે છે?', 'faq.a3': 'એક ભરોસાપાત્ર માનવ સમીક્ષક — સામાન્ય રીતે પરિવારનો કોઈ સભ્ય. સિસ્ટમ જાતે કોઈ સામગ્રી બનાવતી નથી.',
    'faq.q4': 'શું હું પછીથી બધું ભૂંસી શકું?', 'faq.a4': 'હા — તરત અને કાયમ માટે. એક જ પગલું બધા લોકલ વેક્ટર, મોડેલ અને અવાજના નમૂના ભૂંસી નાખે છે.',
    'faq.q5': 'આ યાદો સુધી કોણ પહોંચી શકે?', 'faq.a5': 'ફક્ત સ્પષ્ટપણે મંજૂરી અપાયેલા લોકો. પ્રવેશનાં નિયંત્રણો પરિવાર પાસે રહે છે, પ્લેટફોર્મ પાસે નહીં.',
    'faq.q6': 'જો વ્યક્તિ હજી જીવિત હોય તો?', 'faq.a6': 'એ જ સૌથી સારો ઉપયોગ છે. તેઓ પોતાનો સંગ્રહ જાતે બનાવે છે — શું સામેલ કરવું અને સિસ્ટમ તેમને કેવી રીતે રજૂ કરે તે પસંદ કરીને.',
    'footer.line1': 'શરૂઆત એ રીતે કરો', 'footer.line2': 'જે રીતે થવી જોઈએ.',
    'footer.tagline': 'સંમતિથી બનેલો યાદોનો સંગ્રહ. દરેક જવાબનો સ્રોત. દરેક સ્રોતનું નામ.',
    'footer.product': 'પ્રોડક્ટ', 'footer.research': 'સંશોધન', 'footer.ethics': 'નૈતિકતા', 'footer.deleteData': 'તમારો ડેટા ભૂંસો',
    'footer.code': 'સોર્સ કોડ', 'footer.architecture': 'આર્કિટેક્ચર', 'footer.evaluation': 'મૂલ્યાંકન', 'footer.roadmapDoc': 'રોડમેપ દસ્તાવેજ',
    'footer.copyright': 'CHRONUS સંશોધન પ્રોજેક્ટ. પારુલ યુનિવર્સિટી.', 'footer.privacy': 'ગોપનીયતા અને નૈતિકતા',
    'start.eyebrow': 'સંમતિથી શરૂ કરો', 'start.title': 'તમે ક્યાંથી શરૂ કરવા માંગો છો?',
    'start.o1.title': 'કોઈનું મોડેલ બનાવો', 'start.o1.body': 'સંમતિ નોંધો, તેમના પત્રો અને જવાબો ઉમેરો, અને તેની સાથે વાત કરો. મૂળભૂત રીતે બધું આ જ કમ્પ્યુટર પર રહે છે.',
    'start.o2.title': 'પહેલેથી બનેલા મોડેલ સાથે વાત કરો', 'start.o2.body': 'ઇલોન મસ્ક અને સાત ઐતિહાસિક વ્યક્તિઓ, ફક્ત જાહેર ઇન્ટરવ્યૂ અને જાહેર ડોમેનનાં લખાણોમાંથી બનેલા.', 'start.o2.cta': 'મોડેલ જુઓ',
    'start.o3.title': 'સંમતિવાળો અવાજ સાંભળો', 'start.o3.body': 'સેન્ડબોક્સમાં તમારો પોતાનો અવાજ (સંમતિથી) ક્લોન કરો, અને ઇચ્છો ત્યારે ભૂંસી નાખો.', 'start.o3.cta': 'સેન્ડબોક્સ ખોલો',
    'start.questions': 'સંશોધન વિશે પ્રશ્નો?', 'start.email': 'ટીમને ઇમેઇલ કરો', 'start.issue': 'GitHub પર ઇશ્યૂ ખોલો',
    'loader.tagline': 'તેમના શબ્દો. તેમનો અવાજ. તેમની યાદો — ક્યારેય ઘડી કાઢેલી નહીં.', 'loader.init': 'શરૂ થઈ રહ્યું છે',
    'app.skip': 'મુખ્ય સામગ્રી પર જાઓ',
  },
}
