// Models, Roundtable, Insights, the voice sandbox, sign-in and the rest of
// Create and Memories in English,
// Hindi and Gujarati (merged into i18n.jsx). The Hindi and Gujarati were
// drafted for CHRONUS; have a native speaker check them.

export const PAGES = {
  en: {
    'models.ready': 'Ready', 'models.draft': 'Draft', 'models.interview': '{count}/25 interview',
    'models.localOnly': 'Local only', 'models.localOnlyTip': 'Answers use verbatim quotes only; nothing is sent to a cloud AI',
    'models.inMemory': 'In memory', 'models.inMemoryTip': 'Memorial mode: answers are framed as remembered words',
    'models.chat': 'Chat', 'models.memories': 'Memories', 'models.addMemories': 'Add memories', 'models.continue': 'Continue building',
    'models.importTitle': 'Import a backup', 'models.importText': 'Restore a model from an encrypted .chronus file made with “Back up” on its Create page.',
    'models.chooseFile': 'Choose .chronus file', 'models.password': 'Backup password', 'models.decrypting': 'Decrypting…', 'models.import': 'Import',
    'models.deleteConfirm': "Delete {name} permanently?\n\nThis removes every uploaded document, interview answer and memory of this model. It can't be undone.",
    'models.title': 'Talk to a preserved mind',
    'models.sub': 'Pretrained models built from public archives, and private models you build yourself from letters, journals and interviews. Every answer cites the memory it came from.',
    'models.loading': 'Loading models…', 'models.planned': 'Planned', 'models.plannedNote': 'From the CHRONUS research roadmap, not built yet.',
    'models.yours': 'Your models', 'models.yoursNote': 'Private models stay on this computer. Deleting one removes all of its data.',
    'models.noneTitle': 'No custom models yet', 'models.noneText': "Build one from someone's letters, journals and interview answers, with their consent.",
    'planned.einstein': 'Letters, essays and lectures', 'planned.gandhi': 'Speeches, letters and his autobiography', 'planned.tesla': 'Articles, patents and interviews',
    'planned.aurelius': 'Meditations', 'planned.jobs': 'Keynotes and interviews. Waiting on rights: his words are still under copyright',
    'planned.curie': 'Letters and scientific writing', 'planned.lincoln': 'Speeches and letters', 'planned.shakespeare': 'Plays and sonnets',

    'rt.replyingTo': 'replying to {name}', 'rt.title': 'One question, several minds',
    'rt.sub': 'Seat two to four models and ask them the same thing. Each answers only from its own archive; in the second round each one responds to another, still in its own recorded words, or says it has nothing on that.',
    'rt.choose': 'Choose models', 'rt.pickTwo': 'Pick at least two models first', 'rt.askTable': 'Ask the table…', 'rt.asking': 'Asking…', 'rt.ask': 'Ask',
    'rt.respond': 'Let them respond to each other', 'rt.aiOff': 'A seated model has AI voice turned off',
    'rt.round1': 'Round one', 'rt.round2': 'Round two: replies', 'rt.noReplies': 'No replies: nobody had a first answer to respond to.', 'rt.browseAll': 'Browse all models →',

    'range.7': 'Last 7 days', 'range.30': 'Last 30 days', 'range.90': 'Last 90 days',
    'ins.noneAll': 'No questions asked yet. Numbers appear here as people chat.', 'ins.noneModel': 'No questions asked yet to this model. Numbers appear here as people chat.',
    'ins.answered': 'Questions answered', 'ins.allTime': 'all time', 'ins.idk': 'Said “I don\'t know”', 'ins.questions': '{count} questions',
    'ins.grounding': 'Median grounding', 'ins.groundingSub': 'answer words found in sources', 'ins.time': 'Typical answer time', 'ins.p95': '95% under {time}',
    'ins.feedback': 'Feedback', 'ins.waiting': '{count} waiting for review',
    'ins.perDay': 'Questions per day, {range}', 'ins.groundedChart': 'How grounded answers are (share of words found in their sources)', 'ins.groundedTip': 'answers {from}–{to} grounded',
    'ins.howAnswered': 'How questions were answered', 'ins.confidence': 'Confidence', 'ins.mostAsked': 'Most asked',
    'ins.title': 'How the models are doing',
    'ins.sub': "What people ask, how well answers are grounded, what the archives can't answer yet, and feedback waiting for a person to review. Built from this server's Q&A log, which keeps questions for 90 days unless the server is set otherwise.",
    'ins.model': 'Model', 'ins.dateRange': 'Date range', 'ins.overview': 'Overview', 'ins.gaps': 'Knowledge gaps', 'ins.review': 'Review queue',
    'gaps.none': "Nothing unanswered yet. Questions the archive can't answer (or answers only with low confidence) collect here.",
    'gaps.summary': "{unanswered} of {total} questions couldn't be answered well. Similar questions are grouped.",
    'gaps.asked': 'asked {count}×', 'gaps.also': 'Also: {list}', 'gaps.couldFill': 'Could be filled by interview {id}: “{question}”',
    'gaps.answerIt': 'Answer it', 'gaps.addDoc': 'Add a document', 'gaps.choose': "Choose a model above to see what its archive can't answer.",
    'review.good': '👍 Good answer', 'review.problem': 'Problem', 'review.q': 'Q:', 'review.a': 'A:', 'review.edit': 'Answer (edit before approving if needed)',
    'review.note': 'Note: {note}', 'review.approve': 'Approve into memory',
    'review.approveTip': 'Store this answer as a memory labelled “reviewed past answer” (never quoted as their own words)',
    'review.dismiss': 'Dismiss', 'review.none': 'Nothing waiting. 👍 and 👎 on answers land here for a person to review.',
    'review.explain': "Approving a custom model's answer stores it as a memory labelled “reviewed past answer”, so it can help later answers but is never quoted as their own words. Pretrained models only learn from published sources, so their feedback can only be dismissed.",
    'hist.deleted': 'Questions deleted: {questions}. Feedback deleted: {feedback}.',
    'hist.confirm': "Delete every question you asked {name}, and your feedback? This can't be undone.", 'hist.anyModel': 'any model',
    'hist.link': 'Delete my question history', 'hist.linkWith': 'Delete my question history with {name}',

    'vs.title': 'Clone & test a voice',
    'vs.sub': "Try a cloned voice without building a whole model. Only clone a voice with the speaker's permission: the recording goes to Fish Audio, and deleting the voice here deletes it there too.",
    'vs.new': '1. New voice', 'vs.notSetUp': "Cloud voice isn't set up yet: add {key} to {file}, then restart the server.",
    'vs.consentText': 'This is my voice, or the speaker (or their estate) agreed to it being cloned.',
    'vs.cloudText': 'I agree that the recording, and any text I play, is sent to Fish Audio.',
    'vs.namePlaceholder': 'Name this voice (e.g. My voice)', 'vs.readThis': 'Read this aloud:',
    'vs.script': 'The quick brown fox jumps over the lazy dog. I am recording this short paragraph so a private test voice can be made from it. I can delete this voice whenever I want, and it is deleted from the cloud service too.',
    'vs.stop': '■ Stop · {seconds} s', 'vs.record': '🎙 Record', 'vs.upload': 'Upload audio',
    'vs.hint': '6-60 seconds of clear speech. Any audio format works; it is converted to .wav in your browser.',
    'vs.making': 'Making the voice…', 'vs.speaking': 'Speaking…', 'vs.tooShort': 'That was {seconds} s; please record 6-60 seconds of clear speech',
    'vs.deleteConfirm': 'Delete this voice here and at Fish Audio? This cannot be undone.',
    'vs.yours': '2. Your test voices', 'vs.none': 'No voices yet.', 'vs.sample': '{seconds} s sample · {date}',
    'vs.legacy': 'Saved only in this browser by an older version of this page. They still exist at Fish Audio:',
    'vs.unnamed': 'Unnamed voice', 'vs.deleteFish': 'Delete from Fish Audio', 'vs.test': 'Test “{name}”', 'vs.quickTest': 'Quick test',
    'vs.quickLine': 'Hello! This is a quick test of how this cloned voice sounds.', 'vs.typePlaceholder': 'Type anything to hear it in this voice…',
    'vs.synth': 'Synthesizing…', 'vs.speak': 'Speak', 'vs.home': '← Home',

    'login.eyebrow': 'Private server', 'login.signIn': 'Sign in', 'login.enterCode': 'Enter the access code',
    'login.accountsNote': 'Each person has their own name and code, and sees only the models they made.',
    'login.codeNote': 'This CHRONUS server is protected. Ask whoever runs it for the code.',
    'login.name': 'Your name', 'login.code': 'Access code', 'login.checking': 'Checking…',

    'ans.self': 'The person themselves', 'ans.family': 'Family', 'ans.friend': 'A friend', 'ans.colleague': 'A colleague',
    'up.title': '2. Upload documents',
    'up.note': 'Letters, journals, emails, speeches, transcripts, photos or scans of handwritten letters ({types}; up to {mb} MB each).',
    'up.audio': 'Voice notes and recordings work too: they are transcribed on this computer.', 'up.dupes': 'Text already in this model from another file is skipped.',
    'up.who': 'Who wrote these documents', 'up.bySelf': 'Written or spoken by {name}', 'up.byOther': 'Written about {name}',
    'up.uploading': 'Uploading…', 'up.choose': 'Choose files', 'up.tooBig': '{file}: larger than {mb} MB',
    'up.theirWords': 'their words', 'up.aboutThem': 'about them', 'up.known': '{count} already known',
    'iv.speak': '🎙 Speak the answer', 'iv.next': 'Next: {id}', 'iv.saved': '✓ saved', 'iv.answer': 'Answer', 'iv.theirAnswer': 'Their answer…',
    'iv.saving': 'Saving…', 'iv.save': 'Save', 'iv.replace': 'Answered. Write here to replace the saved answer.', 'iv.prompt': 'Answer in their words, as they would.',
    'iv.saveAnswer': 'Save answer', 'iv.askNext': 'Ask next', 'iv.title': '3. Interview', 'iv.followups': '{count} follow-ups',
    'iv.intro': '25 questions across six parts of a personality. Answer as many as you can; even a few fill gaps the documents leave. After each answer, CHRONUS suggests what to ask next, from the names, places and years it mentions. You can speak answers instead of typing them.',
    'iv.who': 'Who is answering?',
    'create.voiceNotSetUp': "Cloud voice isn't set up yet: add {key} to {file} (get a key at fish.audio/app/api-keys), then restart the server.",
    'bk.title': '6. Back up',
    'bk.intro': "Download {name} as one encrypted .chronus file: memories, documents, interview answers, consent record and voice recording. Only someone with the password can open it. Import it on the Models page of any CHRONUS install. Keep the password safe: it can't be recovered.",
    'bk.password': 'Password (8+ characters)', 'bk.passwordLabel': 'Password', 'bk.repeat': 'Repeat password', 'bk.encrypting': 'Encrypting…', 'bk.download': 'Download backup',
    'bk.mismatch': "The passwords don't match.", 'bk.done': '✓ Backup downloaded', 'create.notCustom': "{name} is a pretrained model and can't be edited.",
    'mem.deleteConfirm': 'Delete this memory? The model will no longer use it. This cannot be undone.', 'mem.edited': 'edited', 'mem.back': '← Back to chat',
    'mem.sub': 'Every answer is built from these memories and nothing else.', 'mem.subCustom': 'Correct a memory, or remove one or a whole document, and the model changes right away.',
    'mem.subPretrained': 'This model is built from published sources, so its memories are read-only.',
    'mem.search': 'Search by meaning, e.g. “childhood” or “first factory”', 'mem.source': 'Source', 'mem.allSources': 'All sources', 'mem.reviewed': 'Reviewed answers',
    'mem.searchBtn': 'Search', 'mem.clear': 'Clear', 'mem.closest': '{count} memories, closest to “{query}” first', 'mem.docs': 'Uploaded documents ({count})',
    'mem.remove': 'Remove', 'mem.removeConfirm': 'Remove {file} and every memory made from it?', 'mem.more': 'Show more',
    'mem.loadingHistory': 'Loading history…', 'mem.tampered': "This model's change log was altered after it was written (entry {entry}).",
    'replaced.edit': 'edited', 'replaced.delete': 'deleted', 'replaced.restore': 'replaced by a restore', 'replaced.never_quote': 'quoting changed',
    'chart.chart': 'Chart', 'chart.table': 'Table', 'chart.empty': 'Nothing yet.',
  },
  hi: {
    'models.ready': 'तैयार', 'models.draft': 'ड्राफ़्ट', 'models.interview': 'साक्षात्कार {count}/25',
    'models.localOnly': 'सिर्फ़ लोकल', 'models.localOnlyTip': 'जवाब सिर्फ़ शब्दशः उद्धरणों से; किसी क्लाउड AI को कुछ नहीं भेजा जाता',
    'models.inMemory': 'स्मृति में', 'models.inMemoryTip': 'स्मृति मोड: जवाब याद किए गए शब्दों की तरह दिए जाते हैं',
    'models.chat': 'बात करें', 'models.memories': 'यादें', 'models.addMemories': 'यादें जोड़ें', 'models.continue': 'बनाना जारी रखें',
    'models.importTitle': 'बैकअप आयात करें', 'models.importText': 'किसी मॉडल को उसके बनाएँ पेज पर “बैकअप” से बनी एन्क्रिप्टेड .chronus फ़ाइल से वापस लाएँ।',
    'models.chooseFile': '.chronus फ़ाइल चुनें', 'models.password': 'बैकअप पासवर्ड', 'models.decrypting': 'डिक्रिप्ट हो रहा है…', 'models.import': 'आयात करें',
    'models.deleteConfirm': '{name} को हमेशा के लिए मिटाएँ?\n\nइससे इस मॉडल का हर अपलोड किया गया दस्तावेज़, साक्षात्कार का जवाब और याद मिट जाएगी। यह वापस नहीं होगा।',
    'models.title': 'सहेजे गए मन से बात करें',
    'models.sub': 'सार्वजनिक संग्रहों से बने पहले से तैयार मॉडल, और पत्रों, डायरियों और साक्षात्कारों से आपके खुद बनाए निजी मॉडल। हर जवाब उस याद का हवाला देता है जिससे वह आया।',
    'models.loading': 'मॉडल लोड हो रहे हैं…', 'models.planned': 'योजना में', 'models.plannedNote': 'CHRONUS शोध रोडमैप से, अभी बने नहीं हैं।',
    'models.yours': 'आपके मॉडल', 'models.yoursNote': 'निजी मॉडल इसी कंप्यूटर पर रहते हैं। किसी को मिटाने से उसका सारा डेटा मिट जाता है।',
    'models.noneTitle': 'अभी कोई कस्टम मॉडल नहीं', 'models.noneText': 'किसी के पत्रों, डायरियों और साक्षात्कार के जवाबों से, उनकी सहमति के साथ, एक मॉडल बनाएँ।',
    'planned.einstein': 'पत्र, निबंध और व्याख्यान', 'planned.gandhi': 'भाषण, पत्र और उनकी आत्मकथा', 'planned.tesla': 'लेख, पेटेंट और साक्षात्कार',
    'planned.aurelius': 'मेडिटेशन्स', 'planned.jobs': 'कीनोट और साक्षात्कार। अधिकारों का इंतज़ार: उनके शब्द अभी कॉपीराइट में हैं',
    'planned.curie': 'पत्र और वैज्ञानिक लेखन', 'planned.lincoln': 'भाषण और पत्र', 'planned.shakespeare': 'नाटक और सॉनेट',

    'rt.replyingTo': '{name} को जवाब', 'rt.title': 'एक सवाल, कई मन',
    'rt.sub': 'दो से चार मॉडल बिठाएँ और सबसे एक ही बात पूछें। हर मॉडल सिर्फ़ अपने संग्रह से जवाब देता है; दूसरे दौर में हर एक किसी दूसरे को जवाब देता है, फिर भी अपने दर्ज शब्दों में, या कह देता है कि उसके पास इस पर कुछ नहीं है।',
    'rt.choose': 'मॉडल चुनें', 'rt.pickTwo': 'पहले कम से कम दो मॉडल चुनें', 'rt.askTable': 'सबसे पूछें…', 'rt.asking': 'पूछ रहे हैं…', 'rt.ask': 'पूछें',
    'rt.respond': 'उन्हें एक-दूसरे को जवाब देने दें', 'rt.aiOff': 'बैठे हुए किसी मॉडल की AI आवाज़ बंद है',
    'rt.round1': 'पहला दौर', 'rt.round2': 'दूसरा दौर: जवाब', 'rt.noReplies': 'कोई जवाब नहीं: किसी के पास जवाब देने लायक पहला जवाब नहीं था।', 'rt.browseAll': 'सभी मॉडल देखें →',

    'range.7': 'पिछले 7 दिन', 'range.30': 'पिछले 30 दिन', 'range.90': 'पिछले 90 दिन',
    'ins.noneAll': 'अभी तक कोई सवाल नहीं पूछा गया। लोग जैसे-जैसे बात करेंगे, आँकड़े यहाँ दिखेंगे।', 'ins.noneModel': 'इस मॉडल से अभी तक कोई सवाल नहीं पूछा गया। लोग जैसे-जैसे बात करेंगे, आँकड़े यहाँ दिखेंगे।',
    'ins.answered': 'जवाब दिए गए सवाल', 'ins.allTime': 'अब तक', 'ins.idk': '“मुझे नहीं पता” कहा', 'ins.questions': '{count} सवाल',
    'ins.grounding': 'मध्यिका आधार', 'ins.groundingSub': 'जवाब के शब्द जो स्रोतों में मिले', 'ins.time': 'आम जवाब का समय', 'ins.p95': '95% {time} से कम में',
    'ins.feedback': 'फ़ीडबैक', 'ins.waiting': '{count} समीक्षा के इंतज़ार में',
    'ins.perDay': 'हर दिन के सवाल, {range}', 'ins.groundedChart': 'जवाब कितने आधारित हैं (स्रोतों में मिले शब्दों का हिस्सा)', 'ins.groundedTip': '{from}–{to} आधारित जवाब',
    'ins.howAnswered': 'सवालों के जवाब कैसे दिए गए', 'ins.confidence': 'भरोसा', 'ins.mostAsked': 'सबसे ज़्यादा पूछे गए',
    'ins.title': 'मॉडल कैसा कर रहे हैं',
    'ins.sub': 'लोग क्या पूछते हैं, जवाब कितने आधारित हैं, संग्रह अभी किन सवालों का जवाब नहीं दे सकते, और कौन-सा फ़ीडबैक किसी इंसान की समीक्षा का इंतज़ार कर रहा है। यह इस सर्वर के सवाल-जवाब लॉग से बना है, जो सवालों को 90 दिन तक रखता है, जब तक सर्वर पर कुछ और तय न हो।',
    'ins.model': 'मॉडल', 'ins.dateRange': 'तारीख़ की सीमा', 'ins.overview': 'सारांश', 'ins.gaps': 'ज्ञान की कमियाँ', 'ins.review': 'समीक्षा कतार',
    'gaps.none': 'अभी कुछ अनुत्तरित नहीं। जिन सवालों का संग्रह जवाब नहीं दे सकता (या सिर्फ़ कम भरोसे से देता है), वे यहाँ जमा होते हैं।',
    'gaps.summary': '{total} में से {unanswered} सवालों का अच्छा जवाब नहीं दिया जा सका। मिलते-जुलते सवाल एक साथ रखे गए हैं।',
    'gaps.asked': '{count}× पूछा गया', 'gaps.also': 'और भी: {list}', 'gaps.couldFill': 'साक्षात्कार {id} से भरा जा सकता है: “{question}”',
    'gaps.answerIt': 'जवाब दें', 'gaps.addDoc': 'दस्तावेज़ जोड़ें', 'gaps.choose': 'ऊपर कोई मॉडल चुनें, ताकि दिखे कि उसका संग्रह किन सवालों का जवाब नहीं दे सकता।',
    'review.good': '👍 अच्छा जवाब', 'review.problem': 'समस्या', 'review.q': 'सवाल:', 'review.a': 'जवाब:', 'review.edit': 'जवाब (ज़रूरत हो तो मंज़ूरी से पहले बदलें)',
    'review.note': 'नोट: {note}', 'review.approve': 'याद में मंज़ूर करें',
    'review.approveTip': 'इस जवाब को “समीक्षित पुराना जवाब” लेबल वाली याद के रूप में रखें (कभी उनके अपने शब्दों की तरह उद्धृत नहीं)',
    'review.dismiss': 'खारिज करें', 'review.none': 'कुछ इंतज़ार में नहीं। जवाबों पर 👍 और 👎 किसी इंसान की समीक्षा के लिए यहाँ आते हैं।',
    'review.explain': 'किसी कस्टम मॉडल के जवाब को मंज़ूर करने पर वह “समीक्षित पुराना जवाब” लेबल वाली याद बन जाता है, ताकि वह आगे के जवाबों में मदद करे, पर कभी उनके अपने शब्दों की तरह उद्धृत न हो। पहले से बने मॉडल सिर्फ़ प्रकाशित स्रोतों से सीखते हैं, इसलिए उनका फ़ीडबैक सिर्फ़ खारिज किया जा सकता है।',
    'hist.deleted': 'मिटाए गए सवाल: {questions}। मिटाया गया फ़ीडबैक: {feedback}।',
    'hist.confirm': '{name} से पूछे गए आपके सारे सवाल, और आपका फ़ीडबैक मिटाएँ? यह वापस नहीं होगा।', 'hist.anyModel': 'किसी भी मॉडल',
    'hist.link': 'मेरे सवालों का इतिहास मिटाएँ', 'hist.linkWith': '{name} के साथ मेरे सवालों का इतिहास मिटाएँ',

    'vs.title': 'आवाज़ क्लोन करें और जाँचें',
    'vs.sub': 'पूरा मॉडल बनाए बिना क्लोन की गई आवाज़ आज़माएँ। सिर्फ़ बोलने वाले की अनुमति से ही आवाज़ क्लोन करें: रिकॉर्डिंग Fish Audio को जाती है, और यहाँ आवाज़ मिटाने पर वह वहाँ से भी मिट जाती है।',
    'vs.new': '1. नई आवाज़', 'vs.notSetUp': 'क्लाउड आवाज़ अभी सेट नहीं है: {file} में {key} जोड़ें, फिर सर्वर दोबारा शुरू करें।',
    'vs.consentText': 'यह मेरी आवाज़ है, या बोलने वाले (या उनके उत्तराधिकारियों) ने इसे क्लोन करने की सहमति दी है।',
    'vs.cloudText': 'मैं सहमत हूँ कि रिकॉर्डिंग, और जो भी टेक्स्ट मैं चलाऊँ, Fish Audio को भेजा जाएगा।',
    'vs.namePlaceholder': 'इस आवाज़ को नाम दें (जैसे मेरी आवाज़)', 'vs.readThis': 'इसे ज़ोर से पढ़ें:',
    'vs.script': 'यह छोटा-सा अनुच्छेद इसलिए पढ़ा जा रहा है ताकि इससे एक निजी परीक्षण आवाज़ बनाई जा सके। आज मौसम साफ़ है और बगीचे में रंग-बिरंगे फूल खिले हैं। यह आवाज़ कभी भी मिटाई जा सकती है, और तब यह क्लाउड सेवा से भी मिट जाती है।',
    'vs.stop': '■ रोकें · {seconds} सेकंड', 'vs.record': '🎙 रिकॉर्ड करें', 'vs.upload': 'ऑडियो अपलोड करें',
    'vs.hint': '6-60 सेकंड का साफ़ बोला गया हिस्सा। कोई भी ऑडियो फ़ॉर्मैट चलेगा; वह आपके ब्राउज़र में ही .wav में बदला जाता है।',
    'vs.making': 'आवाज़ बन रही है…', 'vs.speaking': 'बोल रहा है…', 'vs.tooShort': 'यह {seconds} सेकंड था; कृपया 6-60 सेकंड की साफ़ आवाज़ रिकॉर्ड करें',
    'vs.deleteConfirm': 'यह आवाज़ यहाँ और Fish Audio पर मिटाएँ? यह वापस नहीं होगा।',
    'vs.yours': '2. आपकी परीक्षण आवाज़ें', 'vs.none': 'अभी कोई आवाज़ नहीं।', 'vs.sample': '{seconds} सेकंड का नमूना · {date}',
    'vs.legacy': 'इस पेज के पुराने संस्करण ने इन्हें सिर्फ़ इसी ब्राउज़र में सहेजा था। ये अब भी Fish Audio पर मौजूद हैं:',
    'vs.unnamed': 'बिना नाम की आवाज़', 'vs.deleteFish': 'Fish Audio से मिटाएँ', 'vs.test': '“{name}” जाँचें', 'vs.quickTest': 'जल्दी जाँच',
    'vs.quickLine': 'नमस्ते! यह जाँचने के लिए एक छोटा-सा परीक्षण है कि यह क्लोन की गई आवाज़ कैसी सुनाई देती है।', 'vs.typePlaceholder': 'इस आवाज़ में सुनने के लिए कुछ भी लिखें…',
    'vs.synth': 'आवाज़ बन रही है…', 'vs.speak': 'बोलें', 'vs.home': '← होम',

    'login.eyebrow': 'निजी सर्वर', 'login.signIn': 'साइन इन करें', 'login.enterCode': 'एक्सेस कोड डालें',
    'login.accountsNote': 'हर व्यक्ति का अपना नाम और कोड है, और वे सिर्फ़ अपने बनाए मॉडल देखते हैं।',
    'login.codeNote': 'यह CHRONUS सर्वर सुरक्षित है। कोड के लिए इसे चलाने वाले से पूछें।',
    'login.name': 'आपका नाम', 'login.code': 'एक्सेस कोड', 'login.checking': 'जाँच हो रही है…',

    'ans.self': 'खुद वह व्यक्ति', 'ans.family': 'परिवार', 'ans.friend': 'एक मित्र', 'ans.colleague': 'एक सहकर्मी',
    'up.title': '2. दस्तावेज़ अपलोड करें',
    'up.note': 'पत्र, डायरी, ईमेल, भाषण, ट्रांसक्रिप्ट, तस्वीरें या हाथ से लिखे पत्रों के स्कैन ({types}; हर एक {mb} MB तक)।',
    'up.audio': 'वॉइस नोट और रिकॉर्डिंग भी चलती हैं: वे इसी कंप्यूटर पर लिखी जाती हैं।', 'up.dupes': 'जो टेक्स्ट किसी दूसरी फ़ाइल से इस मॉडल में पहले से है, उसे छोड़ दिया जाता है।',
    'up.who': 'ये दस्तावेज़ किसने लिखे', 'up.bySelf': '{name} द्वारा लिखा या कहा गया', 'up.byOther': '{name} के बारे में लिखा गया',
    'up.uploading': 'अपलोड हो रहा है…', 'up.choose': 'फ़ाइलें चुनें', 'up.tooBig': '{file}: {mb} MB से बड़ी',
    'up.theirWords': 'उनके शब्द', 'up.aboutThem': 'उनके बारे में', 'up.known': '{count} पहले से मौजूद',
    'iv.speak': '🎙 जवाब बोलें', 'iv.next': 'अगला: {id}', 'iv.saved': '✓ सहेजा गया', 'iv.answer': 'जवाब दें', 'iv.theirAnswer': 'उनका जवाब…',
    'iv.saving': 'सहेजा जा रहा है…', 'iv.save': 'सहेजें', 'iv.replace': 'जवाब दिया जा चुका है। सहेजा गया जवाब बदलने के लिए यहाँ लिखें।', 'iv.prompt': 'उनके शब्दों में जवाब दें, जैसे वे देते।',
    'iv.saveAnswer': 'जवाब सहेजें', 'iv.askNext': 'आगे पूछें', 'iv.title': '3. साक्षात्कार', 'iv.followups': '{count} आगे के सवाल',
    'iv.intro': 'व्यक्तित्व के छह हिस्सों में 25 सवाल। जितने हो सकें उतनों के जवाब दें; कुछ जवाब भी दस्तावेज़ों में छूटी कमियाँ भर देते हैं। हर जवाब के बाद CHRONUS उसमें आए नामों, जगहों और सालों से सुझाता है कि आगे क्या पूछें। आप टाइप करने के बजाय जवाब बोल भी सकते हैं।',
    'iv.who': 'कौन जवाब दे रहा है?',
    'create.voiceNotSetUp': 'क्लाउड आवाज़ अभी सेट नहीं है: {file} में {key} जोड़ें (कुंजी fish.audio/app/api-keys पर मिलेगी), फिर सर्वर दोबारा शुरू करें।',
    'bk.title': '6. बैकअप',
    'bk.intro': '{name} को एक एन्क्रिप्टेड .chronus फ़ाइल के रूप में डाउनलोड करें: यादें, दस्तावेज़, साक्षात्कार के जवाब, सहमति का रिकॉर्ड और आवाज़ की रिकॉर्डिंग। इसे सिर्फ़ पासवर्ड वाला ही खोल सकता है। इसे किसी भी CHRONUS के मॉडल पेज पर आयात करें। पासवर्ड संभालकर रखें: यह वापस नहीं मिल सकता।',
    'bk.password': 'पासवर्ड (8+ अक्षर)', 'bk.passwordLabel': 'पासवर्ड', 'bk.repeat': 'पासवर्ड दोबारा', 'bk.encrypting': 'एन्क्रिप्ट हो रहा है…', 'bk.download': 'बैकअप डाउनलोड करें',
    'bk.mismatch': 'पासवर्ड मेल नहीं खाते।', 'bk.done': '✓ बैकअप डाउनलोड हुआ', 'create.notCustom': '{name} पहले से बना मॉडल है और इसे बदला नहीं जा सकता।',
    'mem.deleteConfirm': 'यह याद मिटाएँ? मॉडल इसे फिर इस्तेमाल नहीं करेगा। यह वापस नहीं होगा।', 'mem.edited': 'बदला गया', 'mem.back': '← चैट पर वापस',
    'mem.sub': 'हर जवाब इन्हीं यादों से बनता है, और किसी चीज़ से नहीं।', 'mem.subCustom': 'कोई याद सुधारें, या कोई याद या पूरा दस्तावेज़ हटाएँ, और मॉडल तुरंत बदल जाता है।',
    'mem.subPretrained': 'यह मॉडल प्रकाशित स्रोतों से बना है, इसलिए इसकी यादें सिर्फ़ पढ़ी जा सकती हैं।',
    'mem.search': 'अर्थ से खोजें, जैसे “बचपन” या “पहली फ़ैक्टरी”', 'mem.source': 'स्रोत', 'mem.allSources': 'सभी स्रोत', 'mem.reviewed': 'समीक्षित जवाब',
    'mem.searchBtn': 'खोजें', 'mem.clear': 'साफ़ करें', 'mem.closest': '{count} यादें, “{query}” के सबसे करीब पहले', 'mem.docs': 'अपलोड किए गए दस्तावेज़ ({count})',
    'mem.remove': 'हटाएँ', 'mem.removeConfirm': '{file} और उससे बनी हर याद हटाएँ?', 'mem.more': 'और दिखाएँ',
    'mem.loadingHistory': 'इतिहास लोड हो रहा है…', 'mem.tampered': 'इस मॉडल का बदलाव-लॉग लिखे जाने के बाद बदला गया (प्रविष्टि {entry})।',
    'replaced.edit': 'बदला गया', 'replaced.delete': 'मिटाया गया', 'replaced.restore': 'वापस लाने से बदला गया', 'replaced.never_quote': 'उद्धरण की अनुमति बदली',
    'chart.chart': 'चार्ट', 'chart.table': 'तालिका', 'chart.empty': 'अभी कुछ नहीं।',
  },
  gu: {
    'models.ready': 'તૈયાર', 'models.draft': 'ડ્રાફ્ટ', 'models.interview': 'ઇન્ટરવ્યૂ {count}/25',
    'models.localOnly': 'ફક્ત લોકલ', 'models.localOnlyTip': 'જવાબ ફક્ત શબ્દશઃ અવતરણોથી; કોઈ ક્લાઉડ AIને કંઈ મોકલાતું નથી',
    'models.inMemory': 'સ્મૃતિમાં', 'models.inMemoryTip': 'સ્મૃતિ મોડ: જવાબ યાદ કરેલા શબ્દો તરીકે અપાય છે',
    'models.chat': 'વાત કરો', 'models.memories': 'યાદો', 'models.addMemories': 'યાદો ઉમેરો', 'models.continue': 'બનાવવાનું ચાલુ રાખો',
    'models.importTitle': 'બેકઅપ આયાત કરો', 'models.importText': 'મોડેલને તેના બનાવો પાના પરના “બેકઅપ”થી બનેલી એન્ક્રિપ્ટેડ .chronus ફાઇલમાંથી પાછું લાવો.',
    'models.chooseFile': '.chronus ફાઇલ પસંદ કરો', 'models.password': 'બેકઅપ પાસવર્ડ', 'models.decrypting': 'ડિક્રિપ્ટ થઈ રહ્યું છે…', 'models.import': 'આયાત કરો',
    'models.deleteConfirm': '{name}ને કાયમ માટે ભૂંસવું છે?\n\nઆથી આ મોડેલનો દરેક અપલોડ કરેલો દસ્તાવેજ, ઇન્ટરવ્યૂનો જવાબ અને યાદ ભૂંસાઈ જશે. આ પાછું થઈ શકશે નહીં.',
    'models.title': 'સાચવેલા મન સાથે વાત કરો',
    'models.sub': 'જાહેર સંગ્રહોમાંથી બનેલા પહેલેથી તૈયાર મોડેલ, અને પત્રો, ડાયરીઓ અને ઇન્ટરવ્યૂમાંથી તમે જાતે બનાવેલા ખાનગી મોડેલ. દરેક જવાબ જે યાદમાંથી આવ્યો તેનો હવાલો આપે છે.',
    'models.loading': 'મોડેલ લોડ થઈ રહ્યા છે…', 'models.planned': 'આયોજિત', 'models.plannedNote': 'CHRONUS સંશોધન રોડમેપમાંથી, હજી બન્યા નથી.',
    'models.yours': 'તમારા મોડેલ', 'models.yoursNote': 'ખાનગી મોડેલ આ જ કમ્પ્યુટર પર રહે છે. કોઈને ભૂંસવાથી તેનો બધો ડેટા ભૂંસાઈ જાય છે.',
    'models.noneTitle': 'હજી કોઈ કસ્ટમ મોડેલ નથી', 'models.noneText': 'કોઈના પત્રો, ડાયરીઓ અને ઇન્ટરવ્યૂના જવાબોમાંથી, તેમની સંમતિ સાથે, એક મોડેલ બનાવો.',
    'planned.einstein': 'પત્રો, નિબંધો અને વ્યાખ્યાનો', 'planned.gandhi': 'ભાષણો, પત્રો અને તેમની આત્મકથા', 'planned.tesla': 'લેખો, પેટન્ટ અને ઇન્ટરવ્યૂ',
    'planned.aurelius': 'મેડિટેશન્સ', 'planned.jobs': 'કીનોટ અને ઇન્ટરવ્યૂ. હક્કોની રાહ: તેમના શબ્દો હજી કૉપિરાઇટ હેઠળ છે',
    'planned.curie': 'પત્રો અને વૈજ્ઞાનિક લખાણ', 'planned.lincoln': 'ભાષણો અને પત્રો', 'planned.shakespeare': 'નાટકો અને સૉનેટ',

    'rt.replyingTo': '{name}ને જવાબ', 'rt.title': 'એક પ્રશ્ન, અનેક મન',
    'rt.sub': 'બેથી ચાર મોડેલ બેસાડો અને બધાને એક જ વાત પૂછો. દરેક ફક્ત પોતાના સંગ્રહમાંથી જવાબ આપે છે; બીજા રાઉન્ડમાં દરેક બીજાને જવાબ આપે છે, તોય પોતાના નોંધાયેલા શબ્દોમાં, અથવા કહે છે કે તેની પાસે એ વિશે કંઈ નથી.',
    'rt.choose': 'મોડેલ પસંદ કરો', 'rt.pickTwo': 'પહેલાં ઓછામાં ઓછા બે મોડેલ પસંદ કરો', 'rt.askTable': 'બધાને પૂછો…', 'rt.asking': 'પૂછી રહ્યા છીએ…', 'rt.ask': 'પૂછો',
    'rt.respond': 'તેમને એકબીજાને જવાબ આપવા દો', 'rt.aiOff': 'બેઠેલા કોઈ મોડેલનો AI અવાજ બંધ છે',
    'rt.round1': 'પહેલો રાઉન્ડ', 'rt.round2': 'બીજો રાઉન્ડ: જવાબો', 'rt.noReplies': 'કોઈ જવાબ નથી: કોઈની પાસે જવાબ આપવા જેવો પહેલો જવાબ નહોતો.', 'rt.browseAll': 'બધા મોડેલ જુઓ →',

    'range.7': 'છેલ્લા 7 દિવસ', 'range.30': 'છેલ્લા 30 દિવસ', 'range.90': 'છેલ્લા 90 દિવસ',
    'ins.noneAll': 'હજી સુધી કોઈ પ્રશ્ન પૂછાયો નથી. લોકો વાત કરશે તેમ આંકડા અહીં દેખાશે.', 'ins.noneModel': 'આ મોડેલને હજી સુધી કોઈ પ્રશ્ન પૂછાયો નથી. લોકો વાત કરશે તેમ આંકડા અહીં દેખાશે.',
    'ins.answered': 'જવાબ અપાયેલા પ્રશ્નો', 'ins.allTime': 'અત્યાર સુધી', 'ins.idk': '“મને ખબર નથી” કહ્યું', 'ins.questions': '{count} પ્રશ્નો',
    'ins.grounding': 'મધ્યક આધાર', 'ins.groundingSub': 'જવાબના શબ્દો જે સ્રોતોમાં મળ્યા', 'ins.time': 'સામાન્ય જવાબનો સમય', 'ins.p95': '95% {time} થી ઓછામાં',
    'ins.feedback': 'પ્રતિસાદ', 'ins.waiting': '{count} સમીક્ષાની રાહમાં',
    'ins.perDay': 'દરરોજના પ્રશ્નો, {range}', 'ins.groundedChart': 'જવાબો કેટલા આધારિત છે (સ્રોતોમાં મળેલા શબ્દોનો હિસ્સો)', 'ins.groundedTip': '{from}–{to} આધારિત જવાબો',
    'ins.howAnswered': 'પ્રશ્નોના જવાબ કેવી રીતે અપાયા', 'ins.confidence': 'ભરોસો', 'ins.mostAsked': 'સૌથી વધુ પૂછાયેલા',
    'ins.title': 'મોડેલ કેવું કરી રહ્યા છે',
    'ins.sub': 'લોકો શું પૂછે છે, જવાબો કેટલા આધારિત છે, સંગ્રહો હજી કયા પ્રશ્નોના જવાબ આપી શકતા નથી, અને કયો પ્રતિસાદ કોઈ વ્યક્તિની સમીક્ષાની રાહ જુએ છે. આ સર્વરના પ્રશ્ન-જવાબ લૉગમાંથી બનેલું છે, જે પ્રશ્નો 90 દિવસ સુધી રાખે છે, સિવાય કે સર્વર પર બીજું નક્કી હોય.',
    'ins.model': 'મોડેલ', 'ins.dateRange': 'તારીખની શ્રેણી', 'ins.overview': 'સારાંશ', 'ins.gaps': 'જ્ઞાનની ખામીઓ', 'ins.review': 'સમીક્ષા કતાર',
    'gaps.none': 'હજી કંઈ અનુત્તરિત નથી. જે પ્રશ્નોના જવાબ સંગ્રહ આપી શકતો નથી (અથવા ફક્ત ઓછા ભરોસા સાથે આપે છે) તે અહીં ભેગા થાય છે.',
    'gaps.summary': '{total}માંથી {unanswered} પ્રશ્નોના સારા જવાબ આપી શકાયા નથી. મળતા આવતા પ્રશ્નો સાથે રાખ્યા છે.',
    'gaps.asked': '{count}× પૂછાયો', 'gaps.also': 'આ પણ: {list}', 'gaps.couldFill': 'ઇન્ટરવ્યૂ {id}થી ભરી શકાય: “{question}”',
    'gaps.answerIt': 'જવાબ આપો', 'gaps.addDoc': 'દસ્તાવેજ ઉમેરો', 'gaps.choose': 'ઉપર કોઈ મોડેલ પસંદ કરો, જેથી દેખાય કે તેનો સંગ્રહ કયા પ્રશ્નોના જવાબ આપી શકતો નથી.',
    'review.good': '👍 સારો જવાબ', 'review.problem': 'સમસ્યા', 'review.q': 'પ્રશ્ન:', 'review.a': 'જવાબ:', 'review.edit': 'જવાબ (જરૂર હોય તો મંજૂરી પહેલાં સુધારો)',
    'review.note': 'નોંધ: {note}', 'review.approve': 'યાદમાં મંજૂર કરો',
    'review.approveTip': 'આ જવાબને “સમીક્ષિત જૂનો જવાબ” લેબલવાળી યાદ તરીકે રાખો (ક્યારેય તેમના પોતાના શબ્દો તરીકે ટાંકવામાં નહીં આવે)',
    'review.dismiss': 'અવગણો', 'review.none': 'કંઈ રાહમાં નથી. જવાબો પરના 👍 અને 👎 કોઈ વ્યક્તિની સમીક્ષા માટે અહીં આવે છે.',
    'review.explain': 'કસ્ટમ મોડેલના જવાબને મંજૂર કરવાથી તે “સમીક્ષિત જૂનો જવાબ” લેબલવાળી યાદ બને છે, જેથી તે પછીના જવાબોમાં મદદ કરે પણ ક્યારેય તેમના પોતાના શબ્દો તરીકે ટાંકવામાં ન આવે. પહેલેથી બનેલા મોડેલ ફક્ત પ્રકાશિત સ્રોતોમાંથી શીખે છે, એટલે તેમનો પ્રતિસાદ ફક્ત અવગણી શકાય છે.',
    'hist.deleted': 'ભૂંસાયેલા પ્રશ્નો: {questions}. ભૂંસાયેલો પ્રતિસાદ: {feedback}.',
    'hist.confirm': '{name}ને પૂછેલા તમારા બધા પ્રશ્નો, અને તમારો પ્રતિસાદ ભૂંસવો છે? આ પાછું થઈ શકશે નહીં.', 'hist.anyModel': 'કોઈ પણ મોડેલ',
    'hist.link': 'મારા પ્રશ્નોનો ઇતિહાસ ભૂંસો', 'hist.linkWith': '{name} સાથેનો મારા પ્રશ્નોનો ઇતિહાસ ભૂંસો',

    'vs.title': 'અવાજ ક્લોન કરો અને ચકાસો',
    'vs.sub': 'આખું મોડેલ બનાવ્યા વગર ક્લોન કરેલો અવાજ અજમાવો. ફક્ત બોલનારની પરવાનગીથી જ અવાજ ક્લોન કરો: રેકોર્ડિંગ Fish Audioને જાય છે, અને અહીં અવાજ ભૂંસવાથી તે ત્યાંથી પણ ભૂંસાઈ જાય છે.',
    'vs.new': '1. નવો અવાજ', 'vs.notSetUp': 'ક્લાઉડ અવાજ હજી સેટ નથી: {file}માં {key} ઉમેરો, પછી સર્વર ફરી શરૂ કરો.',
    'vs.consentText': 'આ મારો અવાજ છે, અથવા બોલનારે (અથવા તેમના વારસદારોએ) તેને ક્લોન કરવાની સંમતિ આપી છે.',
    'vs.cloudText': 'હું સંમત છું કે રેકોર્ડિંગ, અને હું જે પણ લખાણ વગાડું, તે Fish Audioને મોકલાશે.',
    'vs.namePlaceholder': 'આ અવાજને નામ આપો (જેમ કે મારો અવાજ)', 'vs.readThis': 'આ મોટેથી વાંચો:',
    'vs.script': 'આ નાનો ફકરો એટલા માટે વાંચવામાં આવી રહ્યો છે કે તેમાંથી એક ખાનગી પરીક્ષણ અવાજ બનાવી શકાય. આજે હવામાન સ્વચ્છ છે અને બગીચામાં રંગબેરંગી ફૂલો ખીલ્યાં છે. આ અવાજ ગમે ત્યારે ભૂંસી શકાય છે, અને ત્યારે તે ક્લાઉડ સેવામાંથી પણ ભૂંસાઈ જાય છે.',
    'vs.stop': '■ રોકો · {seconds} સેકન્ડ', 'vs.record': '🎙 રેકોર્ડ કરો', 'vs.upload': 'ઑડિયો અપલોડ કરો',
    'vs.hint': '6-60 સેકન્ડની સ્પષ્ટ બોલી. કોઈ પણ ઑડિયો ફોર્મેટ ચાલશે; તે તમારા બ્રાઉઝરમાં જ .wavમાં બદલાય છે.',
    'vs.making': 'અવાજ બની રહ્યો છે…', 'vs.speaking': 'બોલી રહ્યું છે…', 'vs.tooShort': 'એ {seconds} સેકન્ડ હતું; કૃપા કરીને 6-60 સેકન્ડની સ્પષ્ટ બોલી રેકોર્ડ કરો',
    'vs.deleteConfirm': 'આ અવાજ અહીં અને Fish Audio પર ભૂંસવો છે? આ પાછું થઈ શકશે નહીં.',
    'vs.yours': '2. તમારા પરીક્ષણ અવાજો', 'vs.none': 'હજી કોઈ અવાજ નથી.', 'vs.sample': '{seconds} સેકન્ડનો નમૂનો · {date}',
    'vs.legacy': 'આ પાનાના જૂના સંસ્કરણે આ ફક્ત આ જ બ્રાઉઝરમાં સાચવ્યા હતા. તે હજી Fish Audio પર છે:',
    'vs.unnamed': 'નામ વગરનો અવાજ', 'vs.deleteFish': 'Fish Audioમાંથી ભૂંસો', 'vs.test': '“{name}” ચકાસો', 'vs.quickTest': 'ઝડપી ચકાસણી',
    'vs.quickLine': 'નમસ્તે! આ ક્લોન કરેલો અવાજ કેવો સંભળાય છે તે જોવા માટે આ એક નાની ચકાસણી છે.', 'vs.typePlaceholder': 'આ અવાજમાં સાંભળવા માટે કંઈ પણ લખો…',
    'vs.synth': 'અવાજ બની રહ્યો છે…', 'vs.speak': 'બોલો', 'vs.home': '← હોમ',

    'login.eyebrow': 'ખાનગી સર્વર', 'login.signIn': 'સાઇન ઇન કરો', 'login.enterCode': 'ઍક્સેસ કોડ દાખલ કરો',
    'login.accountsNote': 'દરેક વ્યક્તિનું પોતાનું નામ અને કોડ છે, અને તેઓ ફક્ત પોતે બનાવેલા મોડેલ જુએ છે.',
    'login.codeNote': 'આ CHRONUS સર્વર સુરક્ષિત છે. કોડ માટે તેને ચલાવનારને પૂછો.',
    'login.name': 'તમારું નામ', 'login.code': 'ઍક્સેસ કોડ', 'login.checking': 'ચકાસી રહ્યા છીએ…',

    'ans.self': 'વ્યક્તિ પોતે', 'ans.family': 'પરિવાર', 'ans.friend': 'એક મિત્ર', 'ans.colleague': 'એક સહકર્મી',
    'up.title': '2. દસ્તાવેજો અપલોડ કરો',
    'up.note': 'પત્રો, ડાયરી, ઇમેઇલ, ભાષણો, ટ્રાન્સક્રિપ્ટ, ફોટા અથવા હાથે લખેલા પત્રોના સ્કેન ({types}; દરેક {mb} MB સુધી).',
    'up.audio': 'વૉઇસ નોટ અને રેકોર્ડિંગ પણ ચાલે છે: તે આ જ કમ્પ્યુટર પર લખાય છે.', 'up.dupes': 'જે લખાણ બીજી ફાઇલમાંથી આ મોડેલમાં પહેલેથી છે, તે છોડી દેવાય છે.',
    'up.who': 'આ દસ્તાવેજો કોણે લખ્યા', 'up.bySelf': '{name} દ્વારા લખાયેલું કે કહેવાયેલું', 'up.byOther': '{name} વિશે લખાયેલું',
    'up.uploading': 'અપલોડ થઈ રહ્યું છે…', 'up.choose': 'ફાઇલો પસંદ કરો', 'up.tooBig': '{file}: {mb} MB થી મોટી',
    'up.theirWords': 'તેમના શબ્દો', 'up.aboutThem': 'તેમના વિશે', 'up.known': '{count} પહેલેથી જાણીતી',
    'iv.speak': '🎙 જવાબ બોલો', 'iv.next': 'આગળ: {id}', 'iv.saved': '✓ સાચવ્યું', 'iv.answer': 'જવાબ આપો', 'iv.theirAnswer': 'તેમનો જવાબ…',
    'iv.saving': 'સાચવી રહ્યા છીએ…', 'iv.save': 'સાચવો', 'iv.replace': 'જવાબ અપાઈ ગયો છે. સાચવેલો જવાબ બદલવા અહીં લખો.', 'iv.prompt': 'તેમના શબ્દોમાં જવાબ આપો, જેમ તેઓ આપે.',
    'iv.saveAnswer': 'જવાબ સાચવો', 'iv.askNext': 'હવે પૂછો', 'iv.title': '3. ઇન્ટરવ્યૂ', 'iv.followups': '{count} આગળના પ્રશ્નો',
    'iv.intro': 'વ્યક્તિત્વના છ ભાગોમાં 25 પ્રશ્નો. શક્ય એટલા પ્રશ્નોના જવાબ આપો; થોડા જવાબો પણ દસ્તાવેજોમાં રહી ગયેલી ખામીઓ પૂરી કરે છે. દરેક જવાબ પછી CHRONUS તેમાં આવેલાં નામ, સ્થળો અને વર્ષોમાંથી સૂચવે છે કે હવે શું પૂછવું. તમે લખવાને બદલે જવાબ બોલી પણ શકો છો.',
    'iv.who': 'કોણ જવાબ આપે છે?',
    'create.voiceNotSetUp': 'ક્લાઉડ અવાજ હજી સેટ નથી: {file}માં {key} ઉમેરો (કી fish.audio/app/api-keys પર મળશે), પછી સર્વર ફરી શરૂ કરો.',
    'bk.title': '6. બેકઅપ',
    'bk.intro': '{name}ને એક એન્ક્રિપ્ટેડ .chronus ફાઇલ તરીકે ડાઉનલોડ કરો: યાદો, દસ્તાવેજો, ઇન્ટરવ્યૂના જવાબો, સંમતિનો રેકોર્ડ અને અવાજનું રેકોર્ડિંગ. તેને ફક્ત પાસવર્ડ ધરાવનાર જ ખોલી શકે. તેને કોઈ પણ CHRONUSના મોડેલ પાના પર આયાત કરો. પાસવર્ડ સાચવીને રાખો: તે પાછો મેળવી શકાતો નથી.',
    'bk.password': 'પાસવર્ડ (8+ અક્ષરો)', 'bk.passwordLabel': 'પાસવર્ડ', 'bk.repeat': 'પાસવર્ડ ફરીથી', 'bk.encrypting': 'એન્ક્રિપ્ટ થઈ રહ્યું છે…', 'bk.download': 'બેકઅપ ડાઉનલોડ કરો',
    'bk.mismatch': 'પાસવર્ડ મેળ ખાતા નથી.', 'bk.done': '✓ બેકઅપ ડાઉનલોડ થયો', 'create.notCustom': '{name} પહેલેથી બનેલું મોડેલ છે અને તેને બદલી શકાતું નથી.',
    'mem.deleteConfirm': 'આ યાદ ભૂંસવી છે? મોડેલ તેને ફરી વાપરશે નહીં. આ પાછું થઈ શકશે નહીં.', 'mem.edited': 'સુધારેલું', 'mem.back': '← ચેટ પર પાછા',
    'mem.sub': 'દરેક જવાબ આ જ યાદોમાંથી બને છે, બીજા કશામાંથી નહીં.', 'mem.subCustom': 'કોઈ યાદ સુધારો, અથવા કોઈ યાદ કે આખો દસ્તાવેજ દૂર કરો, અને મોડેલ તરત બદલાઈ જાય છે.',
    'mem.subPretrained': 'આ મોડેલ પ્રકાશિત સ્રોતોમાંથી બનેલું છે, એટલે તેની યાદો ફક્ત વાંચી શકાય છે.',
    'mem.search': 'અર્થથી શોધો, જેમ કે “બાળપણ” અથવા “પહેલી ફેક્ટરી”', 'mem.source': 'સ્રોત', 'mem.allSources': 'બધા સ્રોતો', 'mem.reviewed': 'સમીક્ષિત જવાબો',
    'mem.searchBtn': 'શોધો', 'mem.clear': 'સાફ કરો', 'mem.closest': '{count} યાદો, “{query}”ની સૌથી નજીકની પહેલાં', 'mem.docs': 'અપલોડ કરેલા દસ્તાવેજો ({count})',
    'mem.remove': 'દૂર કરો', 'mem.removeConfirm': '{file} અને તેમાંથી બનેલી દરેક યાદ દૂર કરવી છે?', 'mem.more': 'વધુ બતાવો',
    'mem.loadingHistory': 'ઇતિહાસ લોડ થઈ રહ્યો છે…', 'mem.tampered': 'આ મોડેલનો ફેરફાર-લૉગ લખાયા પછી બદલાયો છે (નોંધ {entry}).',
    'replaced.edit': 'સુધારેલું', 'replaced.delete': 'ભૂંસેલું', 'replaced.restore': 'પાછું લાવવાથી બદલાયું', 'replaced.never_quote': 'ટાંકવાની મંજૂરી બદલાઈ',
    'chart.chart': 'ચાર્ટ', 'chart.table': 'કોષ્ટક', 'chart.empty': 'હજી કંઈ નથી.',
  },
}
