"""Harvest personal data about Elon Musk from local open-source dumps and
build a curated knowledge base file (05-Prompts/personal_data_kb.md), then
embed it into ChromaDB as personal_data units.

Sources (already in the repo, no network needed):
  - 01-Raw-Data/MINIMAX-ELON/duckduckgo.json  (Wikipedia + web summaries)
  - 01-Raw-Data/MINIMAX-ELON/dossier.md        (curated raw dump)
  - 02-Cleaned-Data/MINIMAX/*.md               (cleaned MINIMAX content)
"""
import hashlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import chromadb
import pyarrow.dataset  # noqa: F401  (pyarrow DLL workaround)
from sentence_transformers import SentenceTransformer

from config import config

ROOT = Path(__file__).parent.parent
MINIMAX = ROOT / "01-Raw-Data" / "MINIMAX-ELON"
CLEANED_MINIMAX = ROOT / "02-Cleaned-Data" / "MINIMAX"
KB_PATH = ROOT / "05-Prompts" / "personal_data_kb.md"


def load_text_sources() -> list[str]:
    """Load all MINIMAX/cleaned text into a list of strings for mining."""
    texts = []
    if (MINIMAX / "dossier.md").exists():
        texts.append((MINIMAX / "dossier.md").read_text(encoding="utf-8", errors="ignore"))
    if CLEANED_MINIMAX.exists():
        for f in sorted(CLEANED_MINIMAX.glob("*.md")):
            texts.append(f.read_text(encoding="utf-8", errors="ignore"))
    dd = MINIMAX / "raw" / "duckduckgo.json"
    if dd.exists():
        try:
            data = json.loads(dd.read_text(encoding="utf-8", errors="ignore"))
            for item in data:
                texts.append(str(item.get("content", "")))
        except Exception as e:
            print(f"  [warn] duckduckgo parse failed: {e}")
    return texts


# --- The core personal-fact fields to harvest (open-source / public record) ---
# (field, label, [regex patterns], group)
PERSONAL_FIELDS = [
    ("full_name", "Full Name", [r"Elon Reeve Musk", r"Elon Musk"], "identity"),
    ("born", "Born", [r"born (?:on )?(June \d{1,2}, \d{4})", r"Born (?:on )?(June \d{1,2}, \d{4})", r"June 28, 1971"], "identity"),
    ("birth_place", "Birthplace", [r"born (?:in|at) ([A-Z][a-z]+(?:, [A-Za-z ]+)*)", r"Born (?:in|at) ([A-Z][a-z]+(?:, [A-Za-z ]+)*)", r"Pretoria"], "identity"),
    ("education", "Education", [r"Queen'?s University", r"University of Pennsylvania", r"UPenn", r"Stanford"], "identity"),
    ("family", "Family", [r"Maye Musk", r"Errol Musk", r"Kimbal", r"Tosca", r"Justine", r"Grimes", r"X AE A-XII", r"Nevada"], "family"),
    ("companies", "Companies", [r"SpaceX", r"Tesla", r"Neuralink", r"The Boring Company", r"xAI", r"Zip2", r"PayPal", r"X\.?com"], "career"),
    ("nationality", "Nationality", [r"(South African|Canadian|American)", r"citizen of"], "identity"),
    ("net_worth", "Net Worth", [r"wealthiest", r"net worth", r"\$[0-9.,]+ ?billion"], "career"),
    ("milestones", "Milestones", [r"(19\d{2}|20\d{2})"], "career"),
]
def mine_facts(texts: list[str]) -> dict:
    """Extract personal facts from the text corpus using regex + source capture."""
    facts = {f[0]: [] for f in PERSONAL_FIELDS}
    for t in texts:
        for field, label, patterns, _grp in PERSONAL_FIELDS:
            for pat in patterns:
                for m in re.finditer(pat, t, re.IGNORECASE):
                    val = m.group(0).strip()
                    snippet = t[max(0, m.start() - 60):min(len(t), m.end() + 60)].replace("\n", " ")
                    if not any(existing["value"] == val for existing in facts[field]):
                        facts[field].append({"value": val, "snippet": snippet[:200]})
    return facts


def build_kb_markdown(facts: dict) -> str:
    """Render the harvested facts into a markdown knowledge base file."""
    lines = [
        "# Elon Musk — Personal Data Knowledge Base (Open-Source / Public Record)",
        "",
        "> **Source:** Harvested from the local open-source corpus (MINIMAX ELON dumps,",
        "> Wikipedia snippets, biographies). Every fact below has at least one",
        "> verifiable public source. Generated by `06-Testing/harvest_personal_data.py`.",
        "",
        "## Profile",
        "",
    ]
    for field, label, _p, grp in PERSONAL_FIELDS:
        vals = facts.get(field, [])
        if not vals:
            lines.append(f"- **{label}**: *(not found)*")
            continue
        uniq = []
        seen = set()
        for v in vals:
            key = v["value"].casefold()
            if key not in seen:
                seen.add(key)
                uniq.append(v)
        lines.append(f"- **{label}**: {uniq[0]['value']}")
        if uniq[0].get("snippet"):
            lines.append(f"  - source: \"{uniq[0]['snippet']}\"")
        if len(uniq) > 1:
            lines.append(f"  - also: {', '.join(v['value'] for v in uniq[1:4])}")
    lines.append("")
    lines.append("---")
    lines.append("## Notes")
    lines.append("- Facts are **open-source / public record** only (no private/speculative info).")
    lines.append("- For any query asking personal facts, prefer this KB over generated answers.")
    lines.append("")
    return "\n".join(lines)


def embed_kb(kb_md: str) -> int:
    """Embed the KB as personal_data units into ChromaDB."""
    print("\nEmbedding personal data KB into ChromaDB...")
    embedder = SentenceTransformer(config.EMBEDDING_MODEL, device="cpu")
    client = chromadb.PersistentClient(path=config.CHROMA_PATH)
    col = client.get_or_create_collection(name=config.COLLECTION_NAME, metadata={"hnsw:space": "cosine"})

    # Split into line-level chunks (one fact per unit)
    chunks = []
    current = []
    for line in kb_md.splitlines():
        if line.startswith("- **") and ":" in line:
            if current:
                chunks.append("\n".join(current).strip())
            current = [line]
        elif current:
            current.append(line)
    if current:
        chunks.append("\n".join(current).strip())

    ids, docs, metadatas = [], [], []
    for chunk in chunks:
        doc = chunk.replace("\n", " ").strip()
        if not doc:
            continue
        mem_id = "pers_" + hashlib.md5(doc.encode()).hexdigest()[:16]
        ids.append(mem_id)
        docs.append(doc)
        metadatas.append({
            "source_file": "personal_data_kb.md",
            "source_type": "personal_data",
            "source_name": "Elon Musk Personal Data KB (Open Source)",
            "date": "2026",
            "topic": "personal_profile",
            "importance_score": 5,
            "person": "elon_musk",
        })

    if not docs:
        print("  No chunks to embed (KB empty).")
        return 0

    embeddings = embedder.encode(docs, normalize_embeddings=True).tolist()
    col.upsert(ids=ids, documents=docs, embeddings=embeddings, metadatas=metadatas)
    print(f"  Embedded {len(docs)} personal-data units. Collection now: {col.count()}")
    return len(docs)


def main():
    print("CHRONUS Personal Data Harvester")
    print("=" * 50)
    texts = load_text_sources()
    print(f"Loaded {len(texts)} text sources (total chars: {sum(len(t) for t in texts):,})")
    facts = mine_facts(texts)
    kb = build_kb_markdown(facts)
    KB_PATH.parent.mkdir(parents=True, exist_ok=True)
    KB_PATH.write_text(kb, encoding="utf-8")
    print(f"\nWrote {KB_PATH}")
    print("=" * 50)
    print("\nHarvested facts (non-empty fields):")
    for field, label, _p, _g in PERSONAL_FIELDS:
        vals = facts.get(field, [])
        if vals:
            print(f"  {label}: {vals[0]['value']}")
    n = embed_kb(kb)


if __name__ == "__main__":
    main()